from __future__ import annotations

from typing import Any

from binlex.formats import Image


class AstFunction:
    def __init__(self) -> None: ...
    @classmethod
    def from_dict(cls, data: Any) -> AstFunction: ...
    @classmethod
    def from_hir(cls, hir_function: Any) -> AstFunction: ...
    def optimize(self) -> None: ...
    def c(self, image: Image | None = None) -> str: ...
    def print_c(self) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def to_dict(self) -> Any: ...
    def json(self) -> str: ...


class AstModule:
    def __init__(self) -> None: ...
    @classmethod
    def from_dict(cls, data: Any) -> AstModule: ...
    @classmethod
    def from_hir(cls, hir_module: Any) -> AstModule: ...
    def optimize(self) -> None: ...
    def c(self) -> str: ...
    def print_c(self) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def to_dict(self) -> Any: ...
    def json(self) -> str: ...


__all__: list[str]
