from __future__ import annotations

from datetime import datetime
from typing import Any

from binlex.config import Config
from binlex.controlflow import (
    Block,
    BlockJsonDeserializer,
    Function,
    FunctionJsonDeserializer,
    Graph,
    Instruction,
    InstructionJsonDeserializer,
)
from binlex.core.architecture import Architecture
from binlex.core.magic import Magic
from binlex.indexing import Collection


class MetadataUser:
    def username(self) -> str: ...
    def profile_picture(self) -> str | None: ...


class MetadataItem:
    def name(self) -> str: ...
    def created_by(self) -> MetadataUser: ...
    def created_timestamp(self) -> datetime: ...
    def assigned_by(self) -> MetadataUser | None: ...
    def assigned_timestamp(self) -> datetime | None: ...


class UploadResponse:
    def ok(self) -> bool: ...
    def sha256(self) -> str | None: ...
    def error(self) -> str | None: ...


class UploadStatusResponse:
    def sha256(self) -> str: ...
    def status(self) -> str: ...
    def timestamp(self) -> datetime: ...
    def error_message(self) -> str | None: ...
    def id(self) -> str | None: ...


class SearchRow:
    def side(self) -> str: ...
    def grouped(self) -> bool: ...
    def group_end(self) -> bool: ...
    def detail_loaded(self) -> bool: ...
    def object_id(self) -> str: ...
    def timestamp(self) -> datetime: ...
    def username(self) -> str: ...
    def profile_picture(self) -> str | None: ...
    def size(self) -> int: ...
    def score(self) -> float | None: ...
    def similarity_score(self) -> float | None: ...
    def vector(self) -> list[float]: ...
    def json(self) -> dict | list | str | int | float | bool | None: ...
    def symbol(self) -> str | None: ...
    def architecture(self) -> str: ...
    def sha256(self) -> str: ...
    def collection(self) -> Collection: ...
    def address(self) -> int: ...
    def cyclomatic_complexity(self) -> int | None: ...
    def average_instructions_per_block(self) -> float | None: ...
    def instructions(self) -> int | None: ...
    def blocks(self) -> int | None: ...
    def markov(self) -> float | None: ...
    def entropy(self) -> float | None: ...
    def contiguous(self) -> bool | None: ...
    def chromosome_entropy(self) -> float | None: ...
    def embedding(self) -> str: ...
    def embeddings(self) -> int: ...
    def corpora(self) -> list[str]: ...
    def corpora_count(self) -> int: ...
    def tag_count(self) -> int: ...
    def comment_count(self) -> int: ...


class SearchResponse:
    def message(self) -> str | None: ...
    def warning(self) -> str | None: ...
    def error(self) -> str | None: ...
    def query(self) -> str: ...
    def uploaded_sha256(self) -> str | None: ...
    def page(self) -> int: ...
    def top_k(self) -> int: ...
    def total_results(self) -> int: ...
    def has_previous_page(self) -> bool: ...
    def has_next_page(self) -> bool: ...
    def sample_downloads_enabled(self) -> bool: ...
    def results(self) -> list[SearchRow]: ...


class SearchDetail:
    def detail_loaded(self) -> bool: ...
    def object_id(self) -> str: ...
    def timestamp(self) -> datetime: ...
    def username(self) -> str: ...
    def size(self) -> int: ...
    def score(self) -> float | None: ...
    def similarity_score(self) -> float | None: ...
    def vector(self) -> list[float]: ...
    def json(self) -> dict | list | str | int | float | bool | None: ...
    def symbol(self) -> str | None: ...
    def architecture(self) -> str: ...
    def sha256(self) -> str: ...
    def collection(self) -> Collection: ...
    def address(self) -> int: ...
    def cyclomatic_complexity(self) -> int | None: ...
    def average_instructions_per_block(self) -> float | None: ...
    def instructions(self) -> int | None: ...
    def blocks(self) -> int | None: ...
    def markov(self) -> float | None: ...
    def entropy(self) -> float | None: ...
    def contiguous(self) -> bool | None: ...
    def chromosome_entropy(self) -> float | None: ...
    def embedding(self) -> str: ...
    def embeddings(self) -> int: ...
    def corpora(self) -> list[str]: ...
    def corpora_count(self) -> int: ...


class TagsResponse:
    def sha256(self) -> str: ...
    def collection(self) -> Collection | None: ...
    def address(self) -> int | None: ...
    def tags(self) -> list[MetadataItem]: ...
    def page(self) -> int: ...
    def limit(self) -> int: ...
    def total_results(self) -> int: ...
    def has_next(self) -> bool: ...


class TagsCatalog:
    def tags(self) -> list[MetadataItem]: ...
    def total_results(self) -> int: ...
    def has_next(self) -> bool: ...


class SymbolsResponse:
    def sha256(self) -> str: ...
    def collection(self) -> Collection: ...
    def architecture(self) -> str: ...
    def address(self) -> int: ...
    def symbols(self) -> list[MetadataItem]: ...
    def page(self) -> int: ...
    def limit(self) -> int: ...
    def total_results(self) -> int: ...
    def has_next(self) -> bool: ...


class SymbolsCatalog:
    def symbols(self) -> list[MetadataItem]: ...
    def total_results(self) -> int: ...
    def has_next(self) -> bool: ...


class CorporaResponse:
    def sha256(self) -> str: ...
    def collection(self) -> Collection | None: ...
    def architecture(self) -> str | None: ...
    def address(self) -> int | None: ...
    def corpora(self) -> list[MetadataItem]: ...
    def page(self) -> int: ...
    def limit(self) -> int: ...
    def total_results(self) -> int: ...
    def has_next(self) -> bool: ...


class CorporaCatalog:
    def corpora(self) -> list[MetadataItem]: ...
    def total_results(self) -> int: ...


class CollectionTagSearchItem:
    def sha256(self) -> str: ...
    def collection(self) -> Collection: ...
    def address(self) -> int: ...
    def tag(self) -> str: ...
    def timestamp(self) -> datetime: ...


class CollectionTagSearchResponse:
    def items(self) -> list[CollectionTagSearchItem]: ...
    def page(self) -> int: ...
    def page_size(self) -> int: ...
    def has_next(self) -> bool: ...


class EntityComment:
    def id(self) -> int: ...
    def sha256(self) -> str: ...
    def collection(self) -> Collection: ...
    def address(self) -> int: ...
    def user(self) -> MetadataUser: ...
    def timestamp(self) -> datetime: ...
    def body(self) -> str: ...


class EntityCommentsResponse:
    def sha256(self) -> str: ...
    def collection(self) -> Collection: ...
    def address(self) -> int: ...
    def items(self) -> list[EntityComment]: ...
    def page(self) -> int: ...
    def page_size(self) -> int: ...
    def total_results(self) -> int: ...
    def has_next(self) -> bool: ...


class AdminCommentsResponse:
    def items(self) -> list[EntityComment]: ...
    def page(self) -> int: ...
    def page_size(self) -> int: ...
    def total_results(self) -> int: ...
    def has_next(self) -> bool: ...


class Captcha:
    def captcha_id(self) -> str: ...
    def image_base64(self) -> str: ...
    def expires(self) -> datetime: ...


class AuthUser:
    def username(self) -> str: ...
    def key(self) -> str: ...
    def role(self) -> str: ...
    def enabled(self) -> bool: ...
    def profile_picture(self) -> str | None: ...
    def two_factor_enabled(self) -> bool: ...
    def two_factor_required(self) -> bool: ...
    def timestamp(self) -> datetime: ...


class AuthSession:
    def authenticated(self) -> bool: ...
    def registration_enabled(self) -> bool: ...
    def bootstrap_required(self) -> bool: ...
    def two_factor_required(self) -> bool: ...
    def two_factor_setup_required(self) -> bool: ...
    def challenge_token(self) -> str | None: ...
    def user(self) -> AuthUser | None: ...
    def recovery_codes(self) -> list[str] | None: ...


class TwoFactorSetup:
    def manual_secret(self) -> str: ...
    def qr_svg(self) -> str: ...


class UsernameCheck:
    def normalized(self) -> str: ...
    def valid(self) -> bool: ...
    def available(self) -> bool: ...
    def error(self) -> str | None: ...


class UsersListResponse:
    def items(self) -> list[AuthUser]: ...
    def page(self) -> int: ...
    def limit(self) -> int: ...
    def total_results(self) -> int: ...
    def has_next(self) -> bool: ...


class AdminUserCreateResponse:
    def user(self) -> AuthUser: ...
    def key(self) -> str: ...
    def recovery_codes(self) -> list[str]: ...


class KeyRegenerateResponse:
    def key(self) -> str: ...


class RecoveryCodesResponse:
    def recovery_codes(self) -> list[str]: ...


class AdminPasswordResetResponse:
    def username(self) -> str: ...
    def password(self) -> str: ...


class SearchResult:
    def score(self) -> float: ...
    def sha256(self) -> str: ...
    def address(self) -> int: ...
    def size(self) -> int: ...
    def timestamp(self) -> datetime: ...
    def symbol(self) -> str | None: ...
    def architecture(self) -> str: ...
    def embedding(self) -> str: ...
    def embeddings(self) -> int: ...
    def collection(self) -> Collection: ...
    def vector(self) -> list[float]: ...
    def json(self) -> dict | list | str | int | float | bool | None: ...
    def username(self) -> str: ...
    def cyclomatic_complexity(self) -> int | None: ...
    def average_instructions_per_block(self) -> float | None: ...
    def instructions(self) -> int | None: ...
    def blocks(self) -> int | None: ...
    def markov(self) -> float | None: ...
    def entropy(self) -> float | None: ...
    def contiguous(self) -> bool | None: ...
    def chromosome_entropy(self) -> float | None: ...
    def corpora_count(self) -> int: ...
    def tag_count(self) -> int: ...
    def comment_count(self) -> int: ...
    def symbols(self, web: Web, page: int | None = None, limit: int | None = None) -> SymbolsResponse: ...
    def tags(self, web: Web, page: int | None = None, limit: int | None = None) -> TagsResponse: ...
    def corpora(self, web: Web, page: int | None = None, limit: int | None = None) -> CorporaResponse: ...
    def function(self, web: Web) -> FunctionJsonDeserializer | None: ...
    def block(self, web: Web) -> BlockJsonDeserializer | None: ...
    def instruction(self, web: Web) -> InstructionJsonDeserializer | None: ...


class QueryResult:
    def lhs(self) -> SearchResult | None: ...
    def rhs(self) -> SearchResult | None: ...
    def score(self) -> float: ...


class Server:
    def __init__(
        self,
        config: Config,
        url: str | None = None,
        verify: bool | None = None,
        compression: bool | None = None,
    ) -> None: ...
    def url(self) -> str: ...
    def verify(self) -> bool: ...
    def compression(self) -> bool: ...
    def version(self) -> str: ...
    def health(self) -> dict[str, str]: ...
    def analyze_file(
        self,
        path: str,
        magic: Magic | None = None,
        architecture: Architecture | None = None,
    ) -> Graph: ...
    def analyze_bytes(
        self,
        data: bytes,
        magic: Magic | None = None,
        architecture: Architecture | None = None,
    ) -> Graph: ...
    def execute_processor(
        self,
        processor: str,
        binlex_version: str,
        requires: str,
        data: Any,
    ) -> Any: ...


class Web:
    def __init__(
        self,
        config: Config,
        url: str | None = None,
        verify: bool | None = None,
        api_key: str | None = None,
    ) -> None: ...
    def url(self) -> str: ...
    def verify(self) -> bool: ...
    def api_key(self) -> str | None: ...
    def set_api_key(self, api_key: str | None) -> None: ...
    def version(self) -> str: ...
    def graph(self, sha256: str) -> Graph: ...
    def upload_sample(
        self,
        data: bytes,
        filename: str | None = None,
        format: str | None = None,
        architecture: str | None = None,
        corpora: list[str] | None = None,
        tags: list[str] | None = None,
    ) -> UploadResponse: ...
    def upload_status(self, sha256: str) -> UploadStatusResponse: ...
    def index_graph(
        self,
        sha256: str,
        graph: Graph,
        collections: list[Collection] | None = None,
        corpora: list[str] | None = None,
    ) -> bool: ...
    def index_function(
        self,
        sha256: str,
        function: Function,
        corpora: list[str] | None = None,
    ) -> bool: ...
    def index_block(
        self,
        sha256: str,
        block: Block,
        corpora: list[str] | None = None,
    ) -> bool: ...
    def index_instruction(
        self,
        sha256: str,
        instruction: Instruction,
        corpora: list[str] | None = None,
    ) -> bool: ...
    def commit_index(self) -> bool: ...
    def clear_index(self) -> bool: ...
    def search_response(
        self,
        query: str,
        top_k: int | None = None,
        page: int | None = None,
    ) -> SearchResponse: ...
    def search_detail(
        self,
        sha256: str,
        collection: Collection,
        architecture: str,
        address: int,
        symbol: str | None = None,
    ) -> SearchDetail: ...
    def collection_tags(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        page: int | None = None,
        limit: int | None = None,
    ) -> TagsResponse: ...
    def search_tags(self, query: str, limit: int | None = None) -> TagsCatalog: ...
    def add_tag(self, tag: str) -> bool: ...
    def search_corpora(self, query: str) -> CorporaCatalog: ...
    def add_corpus(self, corpus: str) -> bool: ...
    def add_collection_tag(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        tag: str,
    ) -> bool: ...
    def remove_collection_tag(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        tag: str,
    ) -> bool: ...
    def replace_collection_tags(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        tags: list[str],
    ) -> bool: ...
    def collection_symbols(
        self,
        sha256: str,
        collection: Collection,
        architecture: str,
        address: int,
        page: int | None = None,
        limit: int | None = None,
    ) -> SymbolsResponse: ...
    def search_symbols(self, query: str, limit: int | None = None) -> SymbolsCatalog: ...
    def add_symbol(self, symbol: str) -> bool: ...
    def add_collection_symbol(
        self,
        sha256: str,
        collection: Collection,
        architecture: str,
        address: int,
        symbol: str,
    ) -> bool: ...
    def remove_collection_symbol(
        self,
        sha256: str,
        collection: Collection,
        architecture: str,
        address: int,
        symbol: str,
    ) -> bool: ...
    def replace_collection_symbols(
        self,
        sha256: str,
        collection: Collection,
        architecture: str,
        address: int,
        symbols: list[str],
    ) -> bool: ...
    def collection_corpora(
        self,
        sha256: str,
        collection: Collection,
        architecture: str,
        address: int,
        page: int | None = None,
        limit: int | None = None,
    ) -> CorporaResponse: ...
    def add_collection_corpus(
        self,
        sha256: str,
        collection: Collection,
        architecture: str,
        address: int,
        corpus: str,
    ) -> bool: ...
    def remove_collection_corpus(
        self,
        sha256: str,
        collection: Collection,
        architecture: str,
        address: int,
        corpus: str,
    ) -> bool: ...
    def entity_comments(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        page: int | None = None,
        page_size: int | None = None,
    ) -> EntityCommentsResponse: ...
    def add_entity_comment(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        body: str,
    ) -> EntityComment: ...
    def delete_entity_comment(self, id: int) -> bool: ...
    def admin_comments(
        self,
        query: str = "",
        page: int | None = None,
        page_size: int | None = None,
    ) -> AdminCommentsResponse: ...
    def render_yara(self, query: str, items: list[dict[str, Any]]) -> str: ...
    def download_sample(self, sha256: str) -> bytes: ...
    def download_samples(self, sha256: list[str]) -> bytes: ...
    def download_json(
        self,
        corpus: str,
        sha256: str,
        collection: Collection,
        address: int,
    ) -> dict[str, Any] | list[Any] | str | int | float | bool | None: ...
    def auth_bootstrap(
        self,
        username: str,
        password: str,
        password_confirm: str,
    ) -> AuthSession: ...
    def auth_login(self, username: str, password: str) -> AuthSession: ...
    def auth_login_two_factor(self, challenge_token: str, code: str) -> AuthSession: ...
    def auth_login_two_factor_setup(self, challenge_token: str) -> TwoFactorSetup: ...
    def auth_login_two_factor_enable(
        self, challenge_token: str, code: str
    ) -> AuthSession: ...
    def auth_captcha(self) -> Captcha: ...
    def auth_register(
        self,
        username: str,
        password: str,
        password_confirm: str,
        captcha_id: str,
        captcha_answer: str,
    ) -> AuthSession: ...
    def auth_logout(self) -> bool: ...
    def auth_me(self) -> AuthSession: ...
    def auth_username_check(self, username: str) -> UsernameCheck: ...
    def auth_password_reset(
        self,
        username: str,
        recovery_code: str,
        new_password: str,
        password_confirm: str,
        captcha_id: str,
        captcha_answer: str,
    ) -> bool: ...
    def profile(self) -> AuthUser: ...
    def profile_password(
        self,
        current_password: str,
        new_password: str,
        password_confirm: str,
    ) -> bool: ...
    def profile_picture_upload(
        self,
        data: bytes,
        filename: str | None = None,
    ) -> AuthUser: ...
    def profile_picture_delete(self) -> AuthUser: ...
    def profile_picture_get(self, username: str) -> bytes: ...
    def profile_key_regenerate(self) -> KeyRegenerateResponse: ...
    def profile_recovery_regenerate(self) -> RecoveryCodesResponse: ...
    def profile_two_factor_setup(self) -> TwoFactorSetup: ...
    def profile_two_factor_enable(
        self, current_password: str, code: str
    ) -> AuthSession: ...
    def profile_two_factor_disable(
        self, current_password: str, code: str
    ) -> AuthUser: ...
    def profile_delete(self, password: str) -> bool: ...
    def admin_users(
        self,
        query: str = "",
        page: int | None = None,
        limit: int | None = None,
    ) -> UsersListResponse: ...
    def admin_user_create(
        self,
        username: str,
        password: str,
        password_confirm: str,
        role: str,
    ) -> AdminUserCreateResponse: ...
    def admin_user_role(self, username: str, role: str) -> AuthUser: ...
    def admin_user_enabled(self, username: str, enabled: bool) -> AuthUser: ...
    def admin_user_password_reset(self, username: str) -> AdminPasswordResetResponse: ...
    def admin_user_key_regenerate(self, username: str) -> KeyRegenerateResponse: ...
    def admin_user_delete(self, username: str) -> bool: ...
    def admin_user_picture_delete(self, username: str) -> AuthUser: ...
    def admin_user_two_factor_require(self, username: str, required: bool) -> AuthUser: ...
    def admin_user_two_factor_disable(self, username: str) -> AuthUser: ...
    def admin_user_two_factor_reset(self, username: str) -> AuthUser: ...
    def admin_delete_corpus(self, corpus: str) -> bool: ...
    def admin_delete_tag(self, tag: str) -> bool: ...
    def admin_delete_symbol(self, symbol: str) -> bool: ...
    def search(self, query: str, top_k: int = 10, page: int = 1) -> list[QueryResult]: ...


__all__ = [
    "AdminCommentsResponse",
    "AdminPasswordResetResponse",
    "AdminUserCreateResponse",
    "AuthSession",
    "AuthUser",
    "Captcha",
    "CollectionTagSearchItem",
    "CollectionTagSearchResponse",
    "CorporaCatalog",
    "CorporaResponse",
    "EntityComment",
    "EntityCommentsResponse",
    "KeyRegenerateResponse",
    "MetadataUser",
    "MetadataItem",
    "QueryResult",
    "RecoveryCodesResponse",
    "SearchDetail",
    "SearchResponse",
    "SearchResult",
    "SearchRow",
    "Server",
    "SymbolsCatalog",
    "SymbolsResponse",
    "TagsCatalog",
    "TagsResponse",
    "TwoFactorSetup",
    "UploadResponse",
    "UploadStatusResponse",
    "UsernameCheck",
    "UsersListResponse",
    "Web",
]
