from __future__ import annotations

from datetime import datetime

from binlex.config import Config
from binlex.controlflow import Block, Function, Graph, Instruction
from binlex.core.architecture import Architecture
from binlex.core.magic import Magic
from binlex.indexing import Collection


class SearchResult:
    def corpus(self) -> str: ...
    def corpora(self) -> list[str]: ...
    def score(self) -> float: ...
    def sha256(self) -> str: ...
    def address(self) -> int: ...
    def size(self) -> int: ...
    def timestamp(self) -> datetime: ...
    def symbol(self) -> str | None: ...
    def architecture(self) -> str: ...
    def embedding(self) -> str: ...
    def embeddings(self) -> int: ...
    def collection(self) -> Collection: ...
    def vector(self) -> list[float]: ...
    def json(self) -> dict | list | str | int | float | bool | None: ...


class QueryResult:
    def lhs(self) -> SearchResult | None: ...
    def rhs(self) -> SearchResult | None: ...
    def score(self) -> float: ...


class Server:
    def __init__(
        self,
        config: Config,
        url: str | None = None,
        verify: bool | None = None,
        compression: bool | None = None,
    ) -> None: ...
    def url(self) -> str: ...
    def verify(self) -> bool: ...
    def compression(self) -> bool: ...
    def health(self) -> dict[str, str]: ...
    def analyze_file(
        self,
        path: str,
        magic: Magic | None = None,
        architecture: Architecture | None = None,
    ) -> Graph: ...
    def analyze_bytes(
        self,
        data: bytes,
        magic: Magic | None = None,
        architecture: Architecture | None = None,
    ) -> Graph: ...


class Web:
    def __init__(
        self,
        config: Config,
        url: str | None = None,
        verify: bool | None = None,
        api_key: str | None = None,
    ) -> None: ...
    def url(self) -> str: ...
    def verify(self) -> bool: ...
    def api_key(self) -> str | None: ...
    def set_api_key(self, api_key: str | None) -> None: ...
    def index_graph(
        self,
        sha256: str,
        graph: Graph,
        collections: list[Collection] | None = None,
        corpora: list[str] | None = None,
    ) -> bool: ...
    def index_function(
        self,
        sha256: str,
        function: Function,
        corpora: list[str] | None = None,
    ) -> bool: ...
    def index_block(
        self,
        sha256: str,
        block: Block,
        corpora: list[str] | None = None,
    ) -> bool: ...
    def index_instruction(
        self,
        sha256: str,
        instruction: Instruction,
        corpora: list[str] | None = None,
    ) -> bool: ...
    def commit_index(self) -> bool: ...
    def clear_index(self) -> bool: ...
    def collection_tags(
        self,
        sha256: str,
        collection: Collection,
        address: int,
    ) -> list[str]: ...
    def add_collection_tag(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        tag: str,
    ) -> bool: ...
    def remove_collection_tag(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        tag: str,
    ) -> bool: ...
    def replace_collection_tags(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        tags: list[str],
    ) -> bool: ...
    def search(self, query: str, top_k: int = 10, page: int = 1) -> list[QueryResult]: ...


__all__ = ["QueryResult", "SearchResult", "Server", "Web"]
