from __future__ import annotations

from pathlib import Path
from typing import Iterator

class Pattern:
    def get_name(self) -> str: ...
    def get_pattern(self) -> str: ...
    def get_comment(self) -> str | None: ...
    def get_kind(self) -> str: ...
    def is_ascii(self) -> bool: ...
    def is_wide(self) -> bool: ...

class YARAMatch:
    def rule(self) -> str: ...
    def offset(self) -> int: ...
    def data(self) -> bytes: ...
    def size(self) -> int: ...

class YARAScanResults:
    def get_matches(self) -> list[YARAMatch]: ...
    def __iter__(self) -> Iterator[YARAMatch]: ...

class CompiledRuleSet:
    def scan(self, data: bytes) -> YARAScanResults: ...
    def scan_file(self, path: str | Path) -> YARAScanResults: ...

class Condition:
    def __str__(self) -> str: ...

class Rule:
    def __init__(self, name: str | None = None, comment: str | None = None) -> None: ...
    def get_name(self) -> str: ...
    def get_comment(self) -> str | None: ...
    def add_import(self, value: str) -> Rule: ...
    def remove_import(self, value: str) -> bool: ...
    def clear_imports(self) -> Rule: ...
    def add_tag(self, value: str) -> Rule: ...
    def remove_tag(self, value: str) -> bool: ...
    def clear_tags(self) -> Rule: ...
    def set_global(self, value: bool = True) -> Rule: ...
    def set_private(self, value: bool = True) -> Rule: ...
    def is_global(self) -> bool: ...
    def is_private(self) -> bool: ...
    def set_comment(self, value: str) -> Rule: ...
    def clear_comment(self) -> Rule: ...
    def check(self) -> bool: ...
    def set_metadata(self, key: str, value: str | int | float | bool) -> Rule: ...
    def remove_metadata(self, key: str) -> bool: ...
    def clear_metadata(self) -> Rule: ...
    def get_metadata(self) -> list[tuple[str, str | int | float | bool]]: ...
    def add_pattern(self, pattern: str, comment: str | None = None) -> str: ...
    def fragment_pattern(self, name: str, parts: int, destructive: bool = True) -> list[str]: ...
    def add_text(
        self,
        text: str,
        ascii: bool = True,
        wide: bool = False,
        nocase: bool = False,
        xor: bool = False,
        base64: bool = False,
        base64wide: bool = False,
        fullword: bool = False,
        private: bool = False,
        comment: str | None = None,
    ) -> str: ...
    def add_regex(self, regex: str, comment: str | None = None) -> str: ...
    def update_pattern(
        self,
        name: str,
        pattern: str | None = None,
        comment: str | None = ...,
    ) -> bool: ...
    def remove_pattern(self, name: str) -> bool: ...
    def clear_patterns(self) -> Rule: ...
    def get_patterns(self) -> list[Pattern]: ...
    def condition(self, value: str) -> Condition: ...
    def condition_at_least(self, minimum: int, patterns: list[str]) -> Condition: ...
    def condition_and(self, *values: Condition) -> Condition: ...
    def condition_or(self, *values: Condition) -> Condition: ...
    def condition_not(self, value: Condition) -> Condition: ...
    def set_condition(self, value: Condition) -> Rule: ...
    def add_condition(self, value: Condition) -> Rule: ...
    def clear_condition(self) -> Rule: ...
    def get_condition(self) -> Condition | None: ...
    def add_string(self, value: str, comment: str | None = None) -> str: ...
    def render(self) -> str: ...
    def print(self) -> None: ...
    def write(self, path: str | Path) -> None: ...
    def compile(self) -> CompiledRuleSet: ...
    def scan(self, data: bytes) -> YARAScanResults: ...
    def scan_file(self, path: str | Path) -> YARAScanResults: ...
    def __str__(self) -> str: ...

class RuleSet:
    def __init__(self) -> None: ...
    def add(self, rule: Rule) -> RuleSet: ...
    def remove(self, name: str) -> bool: ...
    def clear(self) -> RuleSet: ...
    def get_rules(self) -> list[Rule]: ...
    def check(self) -> bool: ...
    def compile(self) -> CompiledRuleSet: ...
    def scan(self, data: bytes) -> YARAScanResults: ...
    def scan_file(self, path: str | Path) -> YARAScanResults: ...

YARA: type[RuleSet]
YARACondition: type[Condition]
YARARule: type[Rule]
YARAPattern: type[Pattern]
YARACompiledRuleSet: type[CompiledRuleSet]
