from __future__ import annotations

from pathlib import Path
from typing import Iterator

class Pattern:
    def name(self) -> str: ...
    def pattern(self) -> str: ...
    def comment(self) -> str | None: ...
    def kind(self) -> str: ...
    def ascii(self) -> bool: ...
    def wide(self) -> bool: ...

class RuleMatch:
    def rule(self) -> str: ...
    def offset(self) -> int: ...
    def data(self) -> bytes: ...
    def size(self) -> int: ...

class ScanResults:
    def matches(self) -> list[RuleMatch]: ...
    def __iter__(self) -> Iterator[RuleMatch]: ...

class CompiledRuleSet:
    def scan(self, data: bytes) -> ScanResults: ...
    def scan_file(self, path: str | Path) -> ScanResults: ...

class Rule:
    def __init__(self, name: str | None = None, comment: str | None = None) -> None: ...
    def name(self) -> str: ...
    def comment(self) -> str | None: ...
    def comment_set(self, value: str) -> Rule: ...
    def comment_clear(self) -> Rule: ...
    def check(self) -> bool: ...
    def meta(self, key: str, value: str | int | float | bool) -> Rule: ...
    def meta_set(self, key: str, value: str | int | float | bool) -> Rule: ...
    def meta_remove(self, key: str) -> bool: ...
    def meta_clear(self) -> Rule: ...
    def metadata(self) -> list[tuple[str, str | int | float | bool]]: ...
    def pattern(self, pattern: str, comment: str | None = None) -> Rule: ...
    def pattern_add(self, pattern: str, comment: str | None = None) -> str: ...
    def text_add(
        self,
        text: str,
        ascii: bool = True,
        wide: bool = False,
        comment: str | None = None,
    ) -> str: ...
    def regex_add(self, regex: str, comment: str | None = None) -> str: ...
    def pattern_update(
        self,
        name: str,
        pattern: str | None = None,
        comment: str | None = ...,
    ) -> bool: ...
    def remove(self, name: str) -> bool: ...
    def pattern_clear(self) -> Rule: ...
    def patterns(self) -> list[Pattern]: ...
    def condition(self, value: str) -> Rule: ...
    def condition_clear(self) -> Rule: ...
    def condition_value(self) -> str | None: ...
    def condition_all_of_them(self) -> Rule: ...
    def condition_number_of_them(self, n: int) -> Rule: ...
    def condition_any_of(self, names: list[str]) -> Rule: ...
    def condition_all_of(self, names: list[str]) -> Rule: ...
    def condition_at_least(self, n: int, names: list[str]) -> Rule: ...
    def string_add(self, value: str, comment: str | None = None) -> str: ...
    def render(self) -> str: ...
    def print(self) -> None: ...
    def write(self, path: str | Path) -> None: ...
    def compile(self) -> CompiledRuleSet: ...
    def scan(self, data: bytes) -> ScanResults: ...
    def scan_file(self, path: str | Path) -> ScanResults: ...
    def __str__(self) -> str: ...

class RuleSet:
    def __init__(self) -> None: ...
    def add(self, rule: Rule) -> RuleSet: ...
    def remove(self, name: str) -> bool: ...
    def clear(self) -> RuleSet: ...
    def rules(self) -> list[Rule]: ...
    def check(self) -> bool: ...
    def compile(self) -> CompiledRuleSet: ...
    def scan(self, data: bytes) -> ScanResults: ...
    def scan_file(self, path: str | Path) -> ScanResults: ...
