from __future__ import annotations

from typing import Literal

from binlex.config import Config
from .png import PNG
from .svg import SVG
from .terminal import Terminal

DigraphIntensity = Literal["linear", "log", "sqrt"]

class Imaging:
    def __init__(self, data: bytes, config: Config) -> None: ...
    @classmethod
    def _from_binding(cls, binding: object) -> Imaging: ...
    def linear(
        self,
        cell_size: int = 1,
        fixed_width: int = 16,
    ) -> ImagingRenderer: ...
    def bitmap(
        self,
        cell_size: int = 1,
        fixed_width: int = 16,
    ) -> ImagingRenderer: ...
    def digraph(
        self,
        cell_size: int = 1,
        axis_size: int = 256,
        stride: int = 1,
        offset: int = 0,
        window_size: int | None = None,
        intensity: DigraphIntensity = "log",
    ) -> ImagingRenderer: ...
    def entropy(
        self,
        window_size: int = 64,
        cell_size: int = 1,
        fixed_width: int = 64,
    ) -> ImagingRenderer: ...
    def hilbert(self, cell_size: int = 1) -> ImagingRenderer: ...

class ImagingRenderer:
    @classmethod
    def _from_binding(cls, binding: object) -> ImagingRenderer: ...
    def grayscale(self) -> ImagingPalette: ...
    def heatmap(self) -> ImagingPalette: ...
    def bluegreen(self) -> ImagingPalette: ...
    def redblack(self) -> ImagingPalette: ...

class ImagingPalette:
    @classmethod
    def _from_binding(cls, binding: object) -> ImagingPalette: ...
    def fit(self, width: int, height: int) -> ImagingNormalized: ...
    def fill(self, width: int, height: int) -> ImagingNormalized: ...
    def exact(self, width: int, height: int) -> ImagingNormalized: ...
    def png(self) -> PNG: ...
    def svg(self) -> SVG: ...
    def terminal(self) -> Terminal: ...

class ImagingNormalized:
    @classmethod
    def _from_binding(cls, binding: object) -> ImagingNormalized: ...
    def png(self) -> PNG: ...
    def svg(self) -> SVG: ...
    def terminal(self) -> Terminal: ...

__all__ = [
    "DigraphIntensity",
    "Imaging",
    "ImagingNormalized",
    "ImagingPalette",
    "ImagingRenderer",
]
