from __future__ import annotations

from binlex.config import Config
from .png import PNG
from .svg import SVG
from .terminal import Terminal

class Imaging:
    def __init__(self, data: bytes, config: Config) -> None: ...
    @classmethod
    def _from_binding(cls, binding: object) -> Imaging: ...
    def linear(
        self,
        cell_size: int | None = None,
        fixed_width: int | None = None,
    ) -> ImagingRenderer: ...

class ImagingRenderer:
    @classmethod
    def _from_binding(cls, binding: object) -> ImagingRenderer: ...
    def grayscale(self) -> ImagingPalette: ...
    def heatmap(self) -> ImagingPalette: ...
    def bluegreen(self) -> ImagingPalette: ...
    def redblack(self) -> ImagingPalette: ...

class ImagingPalette:
    @classmethod
    def _from_binding(cls, binding: object) -> ImagingPalette: ...
    def png(self) -> PNG: ...
    def svg(self) -> SVG: ...
    def terminal(self) -> Terminal: ...

__all__ = ["Imaging", "ImagingPalette", "ImagingRenderer"]
