from __future__ import annotations

from binlex import Config
from binlex.hashing import AHash, DHash, MinHash32, PHash, SHA256, TLSH
from .palette import Palette

class PNG:
    def __init__(
        self,
        data: bytes,
        palette: Palette,
        config: Config,
        cell_size: int = 1,
        fixed_width: int = 16,
    ) -> None: ...
    def bytes(self) -> bytes: ...
    def write(self, file_path: str) -> None: ...
    def print(self) -> None: ...
    def sha256(self) -> SHA256 | None: ...
    def tlsh(self) -> TLSH | None: ...
    def minhash(self) -> MinHash32 | None: ...
    def ahash(self) -> AHash | None: ...
    def dhash(self) -> DHash | None: ...
    def phash(self) -> PHash | None: ...

__all__ = ["PNG"]
