from __future__ import annotations

from .palette import Palette

class RenderCell:
    @property
    def index(self) -> int: ...
    @property
    def address(self) -> int: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def rgb(self) -> tuple[int, int, int]: ...

class Render:
    def __init__(
        self,
        data: bytes,
        palette: Palette,
        cell_size: int = 1,
        fixed_width: int = 16,
    ) -> None: ...
    @property
    def total_width(self) -> int: ...
    @property
    def total_height(self) -> int: ...
    @property
    def total_cells(self) -> int: ...
    @property
    def fixed_width(self) -> int: ...
    @property
    def cells(self) -> list[RenderCell]: ...

__all__ = ["Render", "RenderCell"]
