from __future__ import annotations

from binlex import Config
from binlex.hashing import AHash, DHash, PHash
from .palette import Palette

class Terminal:
    def __init__(
        self,
        data: bytes,
        palette: Palette,
        config: Config,
        cell_size: int = 1,
        fixed_width: int = 16,
    ) -> None: ...
    def print(self) -> None: ...
    def sha256(self) -> str | None: ...
    def tlsh(self) -> str | None: ...
    def minhash(self) -> str | None: ...
    def ahash(self) -> AHash | None: ...
    def dhash(self) -> DHash | None: ...
    def phash(self) -> PHash | None: ...
    @staticmethod
    def rgb_to_ansi256(r: int, g: int, b: int) -> int: ...

__all__ = ["Terminal"]
