from __future__ import annotations


class Lifter:
    def __init__(self, config: object, triple: str | None = None) -> None: ...
    def lift_instruction(self, instruction: object) -> Lifter | None: ...
    def lift_block(self, block: object, abi: object | None = None) -> Lifter | None: ...
    def lift_function(self, function: object, abi: object | None = None) -> Lifter | None: ...
    def clear(self) -> Lifter | None: ...
    def ir(self) -> str: ...
    def print(self) -> None: ...
    def __str__(self) -> str: ...


__all__: list[str]
