from typing import Any

from binlex.architecture import Architecture
from binlex.controlflow import Block, Function, Graph, Instruction


class Collection:
    Instruction: "Collection"
    Block: "Collection"
    Function: "Collection"


class SearchResult:
    @property
    def score(self) -> float: ...
    @property
    def sha256(self) -> str: ...
    @property
    def address(self) -> int: ...
    @property
    def object_id(self) -> str: ...
    @property
    def architecture(self) -> str: ...
    @property
    def collection(self) -> Collection: ...
    def graph(self) -> Graph: ...
    def function(self) -> Function | None: ...
    def block(self) -> Block | None: ...
    def instruction(self) -> Instruction | None: ...


class LocalStore:
    def __init__(self, root: str, config: Any) -> None: ...
    def put(self, data: bytes) -> str: ...
    def get(self, sha256: str) -> bytes: ...
    def index(
        self,
        corpus: str,
        sha256: str,
        graph: Graph,
        attributes: Any | None = None,
    ) -> None: ...
    def graph(self, corpus: str, sha256: str) -> Graph: ...
    def search(
        self,
        corpus: str,
        collection: Collection,
        architecture: Architecture,
        vector: list[float],
        limit: int = 10,
    ) -> list[SearchResult]: ...
