services:
  binlex-python:
    image: binlex-python:${BINLEX_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/binlex-python.Dockerfile
      args:
        BINLEX_IMAGE_VERSION: ${BINLEX_VERSION:-latest}

  binlex-mcp:
    image: binlex-mcp:${BINLEX_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/binlex-mcp.Dockerfile
      args:
        BINLEX_IMAGE_VERSION: ${BINLEX_VERSION:-latest}
