services:
  binlex-python:
    image: binlex-python:${BINLEX_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/binlex-python.Dockerfile
      args:
        BINLEX_IMAGE_VERSION: ${BINLEX_VERSION:-latest}
    command: python3
