def normalize_l2(values: list[float]) -> list[float]: ...
def mean(values: list[float]) -> float: ...
def max_or_zero(values: list[float]) -> float: ...
def weighted_mean(values: list[float], weights: list[float]) -> float: ...
def weighted_histogram(
    values: list[float],
    weights: list[float],
    buckets: int,
    scale: float,
) -> list[float]: ...
def downsample_vector(values: list[float], dimensions: int) -> list[float]: ...
