from __future__ import annotations

class Architecture:
    @staticmethod
    def from_value(value: int) -> Architecture: ...
    @staticmethod
    def from_string(s: str) -> Architecture: ...
    @property
    def value(self) -> int: ...
    def __str__(self) -> str: ...

class Config:
    def __init__(self) -> None: ...

__all__: list[str]
