from __future__ import annotations

class _ConfigEnabled:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class _ConfigTLSH(_ConfigEnabled):
    @property
    def minimum_byte_size(self) -> int: ...
    @minimum_byte_size.setter
    def minimum_byte_size(self, value: int) -> None: ...

class _ConfigMinhash(_ConfigEnabled):
    @property
    def number_of_hashes(self) -> int: ...
    @number_of_hashes.setter
    def number_of_hashes(self, value: int) -> None: ...
    @property
    def shingle_size(self) -> int: ...
    @shingle_size.setter
    def shingle_size(self, value: int) -> None: ...
    @property
    def maximum_byte_size_enabled(self) -> bool: ...
    @maximum_byte_size_enabled.setter
    def maximum_byte_size_enabled(self, value: bool) -> None: ...
    @property
    def maximum_byte_size(self) -> int: ...
    @maximum_byte_size.setter
    def maximum_byte_size(self, value: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

class _ConfigHashing:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...

class _ConfigHeuristics:
    @property
    def features(self) -> _ConfigEnabled: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...

class _ConfigBlockInstructions(_ConfigEnabled): ...
class _ConfigFunctionBlocks(_ConfigEnabled): ...

class _ConfigChromosomesHashing(_ConfigHashing): ...
class _ConfigChromosomesHeuristics(_ConfigHeuristics): ...
class _ConfigFunctionsHashing(_ConfigHashing): ...
class _ConfigFunctionsHeuristics(_ConfigHeuristics): ...
class _ConfigBlocksHashing(_ConfigHashing): ...
class _ConfigBlocksHeuristics(_ConfigHeuristics): ...
class _ConfigInstructionsHashing(_ConfigHashing): ...
class _ConfigInstructionsHeuristics(_ConfigHeuristics): ...
class _ConfigFormatsFileHashing(_ConfigHashing): ...
class _ConfigFormatsFileHeuristics(_ConfigHeuristics): ...

class ConfigChromosomes:
    @property
    def hashing(self) -> _ConfigChromosomesHashing: ...
    @property
    def heuristics(self) -> _ConfigChromosomesHeuristics: ...

class ConfigFunctions(_ConfigEnabled):
    @property
    def blocks(self) -> _ConfigFunctionBlocks: ...
    @property
    def hashing(self) -> _ConfigFunctionsHashing: ...
    @property
    def heuristics(self) -> _ConfigFunctionsHeuristics: ...

class ConfigBlocks(_ConfigEnabled):
    @property
    def instructions(self) -> _ConfigBlockInstructions: ...
    @property
    def hashing(self) -> _ConfigBlocksHashing: ...
    @property
    def heuristics(self) -> _ConfigBlocksHeuristics: ...

class ConfigInstructions(_ConfigEnabled):
    @property
    def hashing(self) -> _ConfigInstructionsHashing: ...
    @property
    def heuristics(self) -> _ConfigInstructionsHeuristics: ...

class ConfigFormatsFile:
    @property
    def hashing(self) -> _ConfigFormatsFileHashing: ...
    @property
    def heuristics(self) -> _ConfigFormatsFileHeuristics: ...

class ConfigFormats:
    @property
    def file(self) -> ConfigFormatsFile: ...

class ConfigDisassemblerSweep(_ConfigEnabled): ...

class ConfigDisassembler:
    @property
    def sweep(self) -> ConfigDisassemblerSweep: ...

class ConfigMmapCache(_ConfigEnabled): ...

class ConfigMmap:
    @property
    def directory(self) -> str: ...
    @directory.setter
    def directory(self, value: str) -> None: ...
    @property
    def cache(self) -> ConfigMmapCache: ...

class ConfigGeneral:
    @property
    def threads(self) -> int: ...
    @threads.setter
    def threads(self, value: int) -> None: ...
    @property
    def minimal(self) -> bool: ...
    @minimal.setter
    def minimal(self, value: bool) -> None: ...
    @property
    def debug(self) -> bool: ...
    @debug.setter
    def debug(self, value: bool) -> None: ...

class Config:
    def __init__(self) -> None: ...
    @property
    def general(self) -> ConfigGeneral: ...
    @property
    def formats(self) -> ConfigFormats: ...
    @property
    def blocks(self) -> ConfigBlocks: ...
    @property
    def instructions(self) -> ConfigInstructions: ...
    @property
    def functions(self) -> ConfigFunctions: ...
    @property
    def chromosomes(self) -> ConfigChromosomes: ...
    @property
    def mmap(self) -> ConfigMmap: ...
    @property
    def disassembler(self) -> ConfigDisassembler: ...
    def enable_minimal(self) -> None: ...
    def disable_hashing(self) -> None: ...
    def disable_heuristics(self) -> None: ...
    def disable_chromosome_heuristics(self) -> None: ...
    def disable_chromosome_hashing(self) -> None: ...
    def disable_block_hashing(self) -> None: ...
    def disable_instruction_hashing(self) -> None: ...
    def disable_function_hashing(self) -> None: ...
    def disable_function_heuristics(self) -> None: ...
    def disable_block_heuristics(self) -> None: ...
    def disable_instruction_heuristics(self) -> None: ...
    def from_default(self) -> None: ...
    def to_string(self) -> str: ...
    def print(self) -> None: ...
    def write_default(self) -> None: ...
    def write_to_file(self, file_path: str) -> None: ...

__all__: list[str]
