from __future__ import annotations

class _ConfigEnabled:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class _ConfigTLSH(_ConfigEnabled):
    @property
    def minimum_byte_size(self) -> int: ...
    @minimum_byte_size.setter
    def minimum_byte_size(self, value: int) -> None: ...

class _ConfigMinhash(_ConfigEnabled):
    @property
    def number_of_hashes(self) -> int: ...
    @number_of_hashes.setter
    def number_of_hashes(self, value: int) -> None: ...
    @property
    def shingle_size(self) -> int: ...
    @shingle_size.setter
    def shingle_size(self, value: int) -> None: ...
    @property
    def maximum_byte_size_enabled(self) -> bool: ...
    @maximum_byte_size_enabled.setter
    def maximum_byte_size_enabled(self, value: bool) -> None: ...
    @property
    def maximum_byte_size(self) -> int: ...
    @maximum_byte_size.setter
    def maximum_byte_size(self, value: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

class _ConfigHashing:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...

class _ConfigHeuristics:
    @property
    def entropy(self) -> _ConfigEnabled: ...

class _ConfigChromosomeHeuristics(_ConfigHeuristics):
    @property
    def features(self) -> _ConfigEnabled: ...

class _ConfigBlockInstructions(_ConfigEnabled): ...
class _ConfigFunctionBlocks(_ConfigEnabled): ...

class _ConfigChromosomesHashing(_ConfigHashing): ...
class _ConfigChromosomesHeuristics(_ConfigChromosomeHeuristics): ...
class _ConfigFunctionsHashing(_ConfigHashing): ...
class _ConfigFunctionsHeuristics(_ConfigHeuristics): ...
class _ConfigBlocksHashing(_ConfigHashing): ...
class _ConfigBlocksHeuristics(_ConfigHeuristics): ...
class _ConfigFormatsFileHashing:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
class _ConfigFormatsFileHeuristics(_ConfigHeuristics): ...

class ConfigChromosomes:
    @property
    def hashing(self) -> _ConfigChromosomesHashing: ...
    @property
    def heuristics(self) -> _ConfigChromosomesHeuristics: ...

class ConfigFunctions(_ConfigEnabled):
    @property
    def blocks(self) -> _ConfigFunctionBlocks: ...
    @property
    def hashing(self) -> _ConfigFunctionsHashing: ...
    @property
    def heuristics(self) -> _ConfigFunctionsHeuristics: ...

class ConfigBlocks(_ConfigEnabled):
    @property
    def instructions(self) -> _ConfigBlockInstructions: ...
    @property
    def hashing(self) -> _ConfigBlocksHashing: ...
    @property
    def heuristics(self) -> _ConfigBlocksHeuristics: ...

class ConfigInstructions(_ConfigEnabled):
    pass

class ConfigFormatsFile:
    @property
    def hashing(self) -> _ConfigFormatsFileHashing: ...
    @property
    def heuristics(self) -> _ConfigFormatsFileHeuristics: ...

class ConfigFormats:
    @property
    def file(self) -> ConfigFormatsFile: ...

class ConfigDisassemblerSweep(_ConfigEnabled): ...

class ConfigDisassembler:
    @property
    def sweep(self) -> ConfigDisassemblerSweep: ...

class ConfigMmapCache(_ConfigEnabled): ...

class ConfigMmap:
    @property
    def directory(self) -> str: ...
    @directory.setter
    def directory(self, value: str) -> None: ...
    @property
    def cache(self) -> ConfigMmapCache: ...

class ConfigGeneral:
    @property
    def threads(self) -> int: ...
    @threads.setter
    def threads(self, value: int) -> None: ...
    @property
    def minimal(self) -> bool: ...
    @minimal.setter
    def minimal(self, value: bool) -> None: ...
    @property
    def debug(self) -> bool: ...
    @debug.setter
    def debug(self, value: bool) -> None: ...

class ConfigProcessors:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...
    @property
    def path(self) -> str | None: ...
    @path.setter
    def path(self, value: str | None) -> None: ...
    @property
    def processes(self) -> int: ...
    @processes.setter
    def processes(self, value: int) -> None: ...
    @property
    def compression(self) -> bool: ...
    @compression.setter
    def compression(self, value: bool) -> None: ...
    @property
    def restart_on_crash(self) -> bool: ...
    @restart_on_crash.setter
    def restart_on_crash(self, value: bool) -> None: ...
    @property
    def max_payload_bytes(self) -> int: ...
    @max_payload_bytes.setter
    def max_payload_bytes(self, value: int) -> None: ...
    @property
    def idle_timeout_ms(self) -> int: ...
    @idle_timeout_ms.setter
    def idle_timeout_ms(self, value: int) -> None: ...
    @property
    def max_queue_depth(self) -> int: ...
    @max_queue_depth.setter
    def max_queue_depth(self, value: int) -> None: ...

class Config:
    def __init__(self) -> None: ...
    @property
    def general(self) -> ConfigGeneral: ...
    @property
    def processors(self) -> ConfigProcessors: ...
    @property
    def formats(self) -> ConfigFormats: ...
    @property
    def blocks(self) -> ConfigBlocks: ...
    @property
    def instructions(self) -> ConfigInstructions: ...
    @property
    def functions(self) -> ConfigFunctions: ...
    @property
    def chromosomes(self) -> ConfigChromosomes: ...
    @property
    def mmap(self) -> ConfigMmap: ...
    @property
    def disassembler(self) -> ConfigDisassembler: ...
    def enable_minimal(self) -> None: ...
    def disable_hashing(self) -> None: ...
    def disable_heuristics(self) -> None: ...
    def disable_chromosome_heuristics(self) -> None: ...
    def disable_chromosome_hashing(self) -> None: ...
    def disable_block_hashing(self) -> None: ...
    def disable_function_hashing(self) -> None: ...
    def disable_function_heuristics(self) -> None: ...
    def disable_block_heuristics(self) -> None: ...
    def from_default(self) -> None: ...
    def to_string(self) -> str: ...
    def print(self) -> None: ...
    def write_default(self) -> None: ...
    def write_to_file(self, file_path: str) -> None: ...

class Magic:
    @staticmethod
    def from_file(path: str) -> Magic: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Magic: ...
    @staticmethod
    def from_value(value: int) -> Magic: ...
    @staticmethod
    def from_string(s: str) -> Magic: ...
    @property
    def value(self) -> int: ...
    def __str__(self) -> str: ...

__all__: list[str]
