from __future__ import annotations

from binlex.controlflow import Block, Function, Graph, Instruction


class Disassembler:
    def __init__(self, graph: Graph) -> None: ...
    def disassemble_instruction(self, address: int) -> Instruction: ...
    def disassemble_function(self, address: int) -> Function: ...
    def disassemble_block(self, address: int) -> Block: ...
    def disassemble(self, addresses: set[int]) -> None: ...


__all__: list[str]
