from __future__ import annotations

class MemoryMappedFile:
    def __init__(self, path: str, cache: bool) -> None: ...
    def is_cached(self) -> bool: ...
    def path(self) -> str: ...
    def write(self, data: bytes) -> int: ...
    def write_padding(self, length: int) -> None: ...
    def seek_to_end(self) -> int: ...
    def seek(self, offset: int) -> int: ...
    def size(self) -> int: ...
    def mmap(self) -> memoryview: ...
    def mmap_mut(self) -> memoryview: ...

class LZ4String: ...

__all__: list[str]
