from __future__ import annotations

from typing import Optional


class AHash:
    def __init__(self, bytes: bytes) -> None: ...
    def hexdigest(self) -> Optional[str]: ...
    def vector(self) -> Optional[list[float]]: ...
    def compare(self, other: AHash) -> Optional[float]: ...
    def compare_hexdigest(self, other: str) -> Optional[float]: ...
    @staticmethod
    def compare_hexdigests(lhs: str, rhs: str) -> Optional[float]: ...


class DHash:
    def __init__(self, bytes: bytes) -> None: ...
    def hexdigest(self) -> Optional[str]: ...
    def vector(self) -> Optional[list[float]]: ...
    def compare(self, other: DHash) -> Optional[float]: ...
    def compare_hexdigest(self, other: str) -> Optional[float]: ...
    @staticmethod
    def compare_hexdigests(lhs: str, rhs: str) -> Optional[float]: ...


class PHash:
    def __init__(self, bytes: bytes) -> None: ...
    def hexdigest(self) -> Optional[str]: ...
    def vector(self) -> Optional[list[float]]: ...
    def compare(self, other: PHash) -> Optional[float]: ...
    def compare_hexdigest(self, other: str) -> Optional[float]: ...
    @staticmethod
    def compare_hexdigests(lhs: str, rhs: str) -> Optional[float]: ...


class SHA256:
    def __init__(self, bytes: bytes) -> None: ...
    def hexdigest(self) -> Optional[str]: ...
    def vector(self) -> Optional[list[float]]: ...
    def compare(self, other: SHA256) -> Optional[float]: ...
    def compare_hexdigest(self, other: str) -> Optional[float]: ...
    @staticmethod
    def compare_hexdigests(lhs: str, rhs: str) -> Optional[float]: ...


class MinHash32:
    def __init__(
        self,
        bytes: bytes,
        num_hashes: int,
        shingle_size: int,
        seed: int,
    ) -> None: ...
    def hexdigest(self) -> Optional[str]: ...
    def vector(self) -> Optional[list[float]]: ...
    def compare(self, other: MinHash32) -> Optional[float]: ...
    def compare_hexdigest(self, other: str) -> Optional[float]: ...
    @staticmethod
    def compare_hexdigests(lhs: str, rhs: str) -> Optional[float]: ...


class TLSH:
    def __init__(self, bytes: bytes) -> None: ...
    def hexdigest(self, mininum_byte_size: int) -> Optional[str]: ...
    def vector(self, mininum_byte_size: int) -> Optional[list[float]]: ...
    def compare(self, other: TLSH, mininum_byte_size: int) -> Optional[float]: ...
    def compare_hexdigest(self, other: str, mininum_byte_size: int) -> Optional[float]: ...
    @staticmethod
    def compare_hexdigests(lhs: str, rhs: str) -> Optional[float]: ...


__all__ = ["AHash", "DHash", "MinHash32", "PHash", "SHA256", "TLSH"]
