from __future__ import annotations

from typing import Optional


class AHash:
    def __init__(self, bytes: bytes) -> None: ...
    def hexdigest(self) -> Optional[str]: ...
    @staticmethod
    def compare(lhs: str, rhs: str) -> Optional[float]: ...


class DHash:
    def __init__(self, bytes: bytes) -> None: ...
    def hexdigest(self) -> Optional[str]: ...
    @staticmethod
    def compare(lhs: str, rhs: str) -> Optional[float]: ...


class PHash:
    def __init__(self, bytes: bytes) -> None: ...
    def hexdigest(self) -> Optional[str]: ...
    @staticmethod
    def compare(lhs: str, rhs: str) -> Optional[float]: ...


class SHA256:
    def __init__(self, bytes: bytes) -> None: ...
    def hexdigest(self) -> Optional[str]: ...


class MinHash32:
    def __init__(
        self,
        bytes: bytes,
        num_hashes: int,
        shingle_size: int,
        seed: int,
    ) -> None: ...
    def hexdigest(self) -> Optional[str]: ...
    @staticmethod
    def compare(lhs: str, rhs: str) -> float: ...


class TLSH:
    def __init__(self, bytes: bytes) -> None: ...
    def hexdigest(self, mininum_byte_size: int) -> Optional[str]: ...
    @staticmethod
    def compare(lhs: str, rhs: str) -> Optional[float]: ...


__all__ = ["AHash", "DHash", "MinHash32", "PHash", "SHA256", "TLSH"]
