from typing import Any

from binlex import Config


class LocalStore:
    def __init__(self, config: Config) -> None: ...
    @staticmethod
    def with_root(root: str) -> "LocalStore": ...
    @property
    def root(self) -> str: ...
    def object_put(self, path: str, payload: bytes) -> None: ...
    def object_get(self, path: str) -> bytes: ...
    def object_exists(self, path: str) -> bool: ...
    def object_put_json(self, path: str, value: Any) -> None: ...
    def object_get_json(self, path: str) -> Any: ...
    def object_list_json(self, prefix: str) -> list[Any]: ...
    def object_list(self, prefix: str) -> list[str]: ...
    def object_delete(self, path: str) -> None: ...
    def object_delete_prefix(self, prefix: str) -> None: ...
    def sample_put(self, data: bytes) -> str: ...
    def sample_get(self, sha256: str) -> bytes: ...
    def sample_exists(self, sha256: str) -> bool: ...
    def sample_json_put(self, sha256: str, name: str, value: Any) -> None: ...
    def sample_json_get(self, sha256: str, name: str) -> Any: ...
