from typing import Any


class ObjectStore:
    def __init__(self, root: str) -> None: ...
    @property
    def root(self) -> str: ...
    def put_bytes(self, key: str, payload: bytes) -> None: ...
    def get_bytes(self, key: str) -> bytes: ...
    def exists(self, key: str) -> bool: ...
    def put_json(self, key: str, value: Any) -> None: ...
    def get_json(self, key: str) -> Any: ...
    def list_json_prefix(self, prefix: str) -> list[Any]: ...
    def delete_prefix(self, prefix: str) -> None: ...
