from __future__ import annotations

from typing import Any


class MirTypeKind: ...
class MirTerminatorKind: ...
class MirCompareOp:
    Eq: MirCompareOp
    Ne: MirCompareOp
    Ult: MirCompareOp
    Ule: MirCompareOp
    Ugt: MirCompareOp
    Uge: MirCompareOp
    Slt: MirCompareOp
    Sle: MirCompareOp
    Sgt: MirCompareOp
    Sge: MirCompareOp


class MirCastOp:
    ZeroExtend: MirCastOp
    SignExtend: MirCastOp
    Truncate: MirCastOp
    Bitcast: MirCastOp


class MirType:
    @classmethod
    def void(cls) -> MirType: ...
    @classmethod
    def integer(cls, bits: int) -> MirType: ...
    @classmethod
    def float(cls, bits: int) -> MirType: ...
    @classmethod
    def pointer(cls, pointee: MirType) -> MirType: ...
    @classmethod
    def memory(cls) -> MirType: ...
    @classmethod
    def type_definition(cls, name: str) -> MirType: ...
    @classmethod
    def structure(
        cls,
        name: str,
        members: list[MirStructureMember] | None = None,
    ) -> MirType: ...
    @classmethod
    def union(
        cls,
        name: str,
        members: list[MirUnionMember] | None = None,
    ) -> MirType: ...
    @classmethod
    def kind(self) -> MirTypeKind: ...


class MirVoid(MirType):
    def __init__(self) -> None: ...


class MirInteger(MirType):
    def __init__(self, bits: int) -> None: ...


class MirFloat(MirType):
    def __init__(self, bits: int) -> None: ...


class MirPointer(MirType):
    def __init__(self, pointee: Any) -> None: ...


class MirMemory(MirType):
    def __init__(self) -> None: ...


class MirTypeDefinition(MirType):
    def __init__(self, name: str) -> None: ...


class MirStructure(MirType):
    def __init__(self, name: str, members: list[Any] | None = None) -> None: ...


class MirUnion(MirType):
    def __init__(self, name: str, members: list[Any] | None = None) -> None: ...


class MirStructureMember:
    def __init__(self, name: str, ty: MirType) -> None: ...
    @classmethod
    def name(self) -> str: ...


class MirUnionMember:
    def __init__(self, name: str, ty: MirType) -> None: ...
    @classmethod
    def name(self) -> str: ...


class MirValue:
    @classmethod
    def named(cls, name: str, ty: MirType) -> MirValue: ...
    @classmethod
    def integer(cls, value: int, bits: int) -> MirValue: ...
    @classmethod
    def boolean(cls, value: bool) -> MirValue: ...
    @classmethod
    def null(cls, ty: MirType) -> MirValue: ...
    @classmethod
    def undef(cls, ty: MirType) -> MirValue: ...
    @classmethod


class MirNamedValue(MirValue):
    def __init__(self, name: str, ty: Any) -> None: ...


class MirIntegerValue(MirValue):
    def __init__(self, value: int, bits: int) -> None: ...


class MirBooleanValue(MirValue):
    def __init__(self, value: bool) -> None: ...


class MirNullValue(MirValue):
    def __init__(self, ty: Any) -> None: ...


class MirUndefValue(MirValue):
    def __init__(self, ty: Any) -> None: ...


class MirAddressSpace:
    @classmethod
    def default_space(cls) -> MirAddressSpace: ...
    @classmethod
    def stack(cls) -> MirAddressSpace: ...
    @classmethod
    def heap(cls) -> MirAddressSpace: ...
    @classmethod
    def global_space(cls) -> MirAddressSpace: ...
    @classmethod
    def heap_object(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def global_object(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def io(cls) -> MirAddressSpace: ...
    @classmethod
    def local(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def argument(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def spill(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def incoming(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def saved_frame(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def return_address(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def named(cls, name: str) -> MirAddressSpace: ...


class MirBlockParameter:
    def __init__(self, ty: MirType, name: str | None = None) -> None: ...


class MirOperation:
    @classmethod
    def copy(
        cls,
        value: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def add(
        cls,
        lhs: MirValue,
        rhs: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def sub(
        cls,
        lhs: MirValue,
        rhs: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def mul(
        cls,
        lhs: MirValue,
        rhs: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def load(
        cls,
        address_space: MirAddressSpace,
        address: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def store(
        cls,
        address_space: MirAddressSpace,
        address: MirValue,
        value: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def icmp(
        cls,
        op: MirCompareOp,
        lhs: MirValue,
        rhs: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def cast(
        cls,
        op: MirCastOp,
        value: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def call(
        cls,
        target: str,
        arguments: list[MirValue] | None = None,
        result_types: list[MirType] | None = None,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def intrinsic(
        cls,
        name: str,
        arguments: list[MirValue] | None = None,
        result_types: list[MirType] | None = None,
        result: str | None = None,
    ) -> MirOperation: ...


class MirAddOperation(MirOperation):
    def __init__(self, lhs: Any, rhs: Any, ty: Any, result: str | None = None) -> None: ...


class MirCopyOperation(MirOperation):
    def __init__(self, value: Any, ty: Any, result: str | None = None) -> None: ...


class MirSubOperation(MirOperation):
    def __init__(self, lhs: Any, rhs: Any, ty: Any, result: str | None = None) -> None: ...


class MirMulOperation(MirOperation):
    def __init__(self, lhs: Any, rhs: Any, ty: Any, result: str | None = None) -> None: ...


class MirLoadOperation(MirOperation):
    def __init__(self, address_space: Any, address: Any, ty: Any, result: str | None = None) -> None: ...


class MirStoreOperation(MirOperation):
    def __init__(self, address_space: Any, address: Any, value: Any, ty: Any, result: str | None = None) -> None: ...


class MirCompareOperation(MirOperation):
    def __init__(self, op: MirCompareOp, lhs: Any, rhs: Any, ty: Any, result: str | None = None) -> None: ...


class MirCastOperation(MirOperation):
    def __init__(self, op: MirCastOp, value: Any, ty: Any, result: str | None = None) -> None: ...


class MirCallOperation(MirOperation):
    def __init__(
        self,
        target: str,
        arguments: list[Any] | None = None,
        result_types: list[Any] | None = None,
        result: str | None = None,
    ) -> None: ...


class MirIntrinsicOperation(MirOperation):
    def __init__(
        self,
        name: str,
        arguments: list[Any] | None = None,
        result_types: list[Any] | None = None,
        result: str | None = None,
    ) -> None: ...


class MirTerminator:
    @classmethod
    def jump(cls, target: str, arguments: list[MirValue] | None = None) -> MirTerminator: ...
    @classmethod
    def cond_br(
        cls,
        condition: MirValue,
        then_target: str,
        else_target: str,
        then_arguments: list[MirValue] | None = None,
        else_arguments: list[MirValue] | None = None,
    ) -> MirTerminator: ...
    @classmethod
    def return_(cls, values: list[MirValue] | None = None) -> MirTerminator: ...
    @classmethod
    def trap(cls) -> MirTerminator: ...
    @classmethod
    def unreachable(cls) -> MirTerminator: ...
    def kind(self) -> MirTerminatorKind: ...


class MirJumpTerminator(MirTerminator):
    def __init__(self, target: str, arguments: list[Any] | None = None) -> None: ...


class MirCondBrTerminator(MirTerminator):
    def __init__(
        self,
        condition: Any,
        then_target: str,
        else_target: str,
        then_arguments: list[Any] | None = None,
        else_arguments: list[Any] | None = None,
    ) -> None: ...


class MirReturnTerminator(MirTerminator):
    def __init__(self, values: list[Any] | None = None) -> None: ...


class MirTrapTerminator(MirTerminator):
    def __init__(self) -> None: ...


class MirUnreachableTerminator(MirTerminator):
    def __init__(self) -> None: ...


class MirBlock:
    def __init__(self, name: str) -> None: ...
    @classmethod
    def from_lir(cls, lir_block: Any, name: str | None = None) -> MirBlock: ...
    def append_parameter(self, parameter: MirBlockParameter) -> None: ...
    def append_operation(self, operation: MirOperation) -> None: ...
    def set_terminator(self, terminator: MirTerminator) -> None: ...
    def name(self) -> str: ...


class MirFunction:
    def __init__(self, name: str | None = None) -> None: ...
    @classmethod
    @classmethod
    def from_lir(cls, lir_function: Any, name: str | None = None) -> MirFunction: ...
    def append_block(self, block: MirBlock) -> None: ...
    def blocks(self) -> list[MirBlock]: ...
    def verify(self) -> None: ...
    def optimize_register_state(self) -> None: ...
    def optimize_returns(self) -> None: ...
    def optimize_blocks(self) -> None: ...
    def optimize_abi(self) -> None: ...
    def optimize_subexpressions(self) -> None: ...
    def optimize_flags(self) -> None: ...
    def optimize_liveness(self) -> None: ...
    def optimize_undefs(self) -> None: ...
    def optimize_intrinsics(self) -> None: ...
    def optimize_cse(self) -> None: ...
    def optimize_stack(self) -> None: ...
    def optimize_stack_pointers(self) -> None: ...
    def optimize_stack_slots(self) -> None: ...
    def optimize_calls(self) -> None: ...
    def optimize_call_clobbers(self) -> None: ...
    def optimize_memory_aliases(self) -> None: ...
    def optimize_branches(self) -> None: ...
    def optimize_memory_state(self) -> None: ...
    def optimize_constants(self) -> None: ...
    def optimize_dead_effects(self) -> None: ...
    def optimize_copy_propagation(self) -> None: ...
    def optimize_targets(self) -> None: ...
    def optimize_ssa(self) -> None: ...
    def optimize_ssa_liveness(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...


class MirModule:
    def __init__(self, name: str | None = None) -> None: ...
    @classmethod
    @classmethod
    def from_lir(cls, lir_module: Any, name: str | None = None) -> MirModule: ...
    @classmethod
    def from_text(cls, text: str) -> MirModule: ...
    @classmethod
    def from_bytecode(cls, bytecode: bytes) -> MirModule: ...
    def append_function(self, function: MirFunction) -> None: ...
    def functions(self) -> list[MirFunction]: ...
    def verify(self) -> None: ...
    def optimize_register_state(self) -> None: ...
    def optimize_returns(self) -> None: ...
    def optimize_blocks(self) -> None: ...
    def optimize_abi(self) -> None: ...
    def optimize_subexpressions(self) -> None: ...
    def optimize_flags(self) -> None: ...
    def optimize_liveness(self) -> None: ...
    def optimize_undefs(self) -> None: ...
    def optimize_intrinsics(self) -> None: ...
    def optimize_cse(self) -> None: ...
    def optimize_stack(self) -> None: ...
    def optimize_stack_pointers(self) -> None: ...
    def optimize_stack_slots(self) -> None: ...
    def optimize_calls(self) -> None: ...
    def optimize_call_clobbers(self) -> None: ...
    def optimize_memory_aliases(self) -> None: ...
    def optimize_branches(self) -> None: ...
    def optimize_memory_state(self) -> None: ...
    def optimize_constants(self) -> None: ...
    def optimize_dead_effects(self) -> None: ...
    def optimize_copy_propagation(self) -> None: ...
    def optimize_targets(self) -> None: ...
    def optimize_ssa(self) -> None: ...
    def optimize_ssa_liveness(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def bytecode(self) -> bytes: ...
    def mlir(self) -> MirMlirModule: ...
    def operation_names(self) -> list[str]: ...
    def operation_count(self) -> int: ...
    def operation_records(self) -> list[dict[str, object]]: ...
    def print(self) -> None: ...


class MirMlirModule:
    def __init__(self, module: Any) -> None: ...
    @classmethod
    def from_text(cls, text: str) -> MirMlirModule: ...
    @classmethod
    def from_bytecode(cls, bytecode: bytes) -> MirMlirModule: ...
    def optimize_copy_propagation(self) -> None: ...
    def optimize_constants(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def bytecode(self) -> bytes: ...
    def operation_names(self) -> list[str]: ...
    def operation_count(self) -> int: ...
    def operation_records(self) -> list[dict[str, object]]: ...
    def print(self) -> None: ...


__all__: list[str]
