from datetime import datetime

from binlex.config import Config
from binlex.indexing.local import Collection


class SampleStatus:
    PENDING: "SampleStatus"
    PROCESSING: "SampleStatus"
    COMPLETE: "SampleStatus"
    FAILED: "SampleStatus"
    CANCELED: "SampleStatus"


class SampleStatusRecord:
    def sha256(self) -> str: ...
    def status(self) -> SampleStatus: ...
    def timestamp(self) -> datetime: ...
    def error_message(self) -> str | None: ...
    def id(self) -> str | None: ...


class RoleRecord:
    def name(self) -> str: ...
    def timestamp(self) -> datetime: ...


class UserRecord:
    def username(self) -> str: ...
    def role(self) -> str: ...
    def enabled(self) -> bool: ...
    def reserved(self) -> bool: ...
    def timestamp(self) -> datetime: ...


class TokenRecord:
    def id(self) -> str: ...
    def token(self) -> str: ...
    def enabled(self) -> bool: ...
    def timestamp(self) -> datetime: ...
    def expires(self) -> datetime: ...


class CollectionTagRecord:
    def sha256(self) -> str: ...
    def collection(self) -> Collection: ...
    def address(self) -> int: ...
    def tag(self) -> str: ...
    def timestamp(self) -> datetime: ...


class SampleCommentRecord:
    def sha256(self) -> str: ...
    def comment(self) -> str: ...
    def timestamp(self) -> datetime: ...


class CollectionCommentRecord:
    def sha256(self) -> str: ...
    def collection(self) -> Collection: ...
    def address(self) -> int: ...
    def comment(self) -> str: ...
    def timestamp(self) -> datetime: ...


class LocalDB:
    def __init__(self, config: Config, path: str | None = None) -> None: ...
    def sample_status_get(self, sha256: str) -> SampleStatusRecord | None: ...
    def sample_status_set(
        self,
        sha256: str,
        status: SampleStatus,
        timestamp: datetime,
        id: str | None = None,
        error_message: str | None = None,
    ) -> None: ...
    def sample_status_delete(self, sha256: str) -> None: ...
    def sample_comment_add(
        self,
        sha256: str,
        comment: str,
        timestamp: datetime | None = None,
    ) -> None: ...
    def sample_comment_remove(self, sha256: str, comment: str) -> None: ...
    def sample_comment_replace(
        self,
        sha256: str,
        comments: list[str],
        timestamp: datetime | None = None,
    ) -> None: ...
    def sample_comment_search(
        self,
        query: str,
        page: int = 1,
        page_size: int = 50,
    ) -> list[SampleCommentRecord]: ...
    def collection_tag_add(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        tag: str,
        timestamp: datetime,
    ) -> None: ...
    def collection_tag_remove(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        tag: str,
    ) -> None: ...
    def collection_tag_replace(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        tags: list[str],
        timestamp: datetime,
    ) -> None: ...
    def collection_tag_search(
        self,
        query: str,
        collection: Collection | None = None,
        page: int = 1,
        page_size: int = 50,
    ) -> list[CollectionTagRecord]: ...
    def collection_comment_add(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        comment: str,
        timestamp: datetime | None = None,
    ) -> None: ...
    def collection_comment_remove(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        comment: str,
    ) -> None: ...
    def collection_comment_replace(
        self,
        sha256: str,
        collection: Collection,
        address: int,
        comments: list[str],
        timestamp: datetime | None = None,
    ) -> None: ...
    def collection_comment_search(
        self,
        query: str,
        collection: Collection | None = None,
        page: int = 1,
        page_size: int = 50,
    ) -> list[CollectionCommentRecord]: ...
    def role_create(self, name: str, timestamp: datetime | None = None) -> RoleRecord: ...
    def role_get(self, name: str) -> RoleRecord | None: ...
    def role_search(
        self,
        query: str,
        page: int = 1,
        limit: int = 50,
    ) -> list[RoleRecord]: ...
    def role_delete(self, name: str) -> bool: ...
    def user_create(
        self,
        username: str,
        role: str,
        timestamp: datetime | None = None,
    ) -> tuple[UserRecord, str]: ...
    def user_disable(self, username: str) -> bool: ...
    def user_enable(self, username: str) -> bool: ...
    def user_reset(
        self,
        username: str,
        timestamp: datetime | None = None,
    ) -> str: ...
    def user_get(self, username: str) -> UserRecord | None: ...
    def user_search(
        self,
        query: str,
        page: int = 1,
        limit: int = 50,
    ) -> list[UserRecord]: ...
    def auth_check(self, api_key: str) -> bool: ...
    def auth_user(self, api_key: str) -> UserRecord | None: ...
    def token_create(self, ttl_seconds: int) -> tuple[TokenRecord, str]: ...
    def token_check(self, token: str) -> bool: ...
    def token_disable(self, id: str) -> bool: ...
    def token_clear(self) -> int: ...


__all__ = [
    "Collection",
    "CollectionCommentRecord",
    "CollectionTagRecord",
    "LocalDB",
    "RoleRecord",
    "SampleCommentRecord",
    "SampleStatus",
    "SampleStatusRecord",
    "TokenRecord",
    "UserRecord",
]
