from typing import Any


class Milvus:
    def __init__(self, uri: str, token: str | None = None) -> None: ...
    @property
    def uri(self) -> str: ...
    @property
    def token(self) -> str | None: ...
    def ensure_collection(
        self,
        database: str,
        collection: str,
        fields: list[dict[str, Any]],
    ) -> None: ...
    def upsert(self, database: str, collection: str, row: Any) -> None: ...
