from typing import Any


class SQLite:
    def __init__(self, path: str) -> None: ...
    @property
    def path(self) -> str: ...
    def execute_batch(self, sql: str) -> None: ...
    def execute(self, sql: str, params: list[object] | None = None) -> int: ...
    def query(self, sql: str, params: list[object] | None = None) -> list[dict[str, Any]]: ...


__all__ = ["SQLite"]
