from __future__ import annotations

from enum import Enum
from typing import Any

from binlex import Configuration
from binlex.controlflow import Block, Function, Instruction
from binlex.semantics import SemanticAbi, SemanticCpu, Semantics

from . import llvm
from . import vex

class UnsupportedCapabilityError(RuntimeError): ...

class LifterBackend(str, Enum):
    DEFAULT: str
    LLVM: str
    VEX: str

class Lifter:
    @property
    def backend(self) -> LifterBackend: ...
    @property
    def cpu(self) -> SemanticCpu: ...
    @property
    def configuration(self) -> Configuration: ...
    def __init__(self, cpu: SemanticCpu, configuration: Configuration, backend: LifterBackend = LifterBackend.DEFAULT, triple: str | None = None) -> None: ...
    def lift_instruction(self, instruction: Instruction) -> Lifter | None: ...
    def lift_block(self, block: Block, abi: SemanticAbi | None = None) -> Lifter | None: ...
    def lift_function(self, function: Function, abi: SemanticAbi | None = None) -> Lifter | None: ...
    def lift_block_semantics(self, semantics: Semantics, abi: SemanticAbi | None = None) -> Lifter | None: ...
    def lift_function_semantics(self, semantics: Semantics, abi: SemanticAbi | None = None, name: str | None = None) -> Lifter | None: ...
    def create_function(self, name: str, abi: SemanticAbi | None = None) -> llvm.LiftedFunction: ...
    def functions(self) -> list[llvm.LiftedFunction]: ...
    def clear(self) -> Lifter | None: ...
    def ir(self) -> str: ...
    def set_ir(self, ir: str) -> Lifter | None: ...
    def set_bitcode(self, bitcode: bytes) -> Lifter | None: ...
    def print(self) -> None: ...
    def bitcode(self) -> bytes: ...
    def object(self) -> bytes: ...
    def verify(self) -> Any: ...
    def optimize_mem2reg(self) -> Lifter | None: ...
    def optimize_instcombine(self) -> Lifter | None: ...
    def optimize_cfg(self) -> Lifter | None: ...
    def optimize_gvn(self) -> Lifter | None: ...
    def optimize_sroa(self) -> Lifter | None: ...
    def optimize_dce(self) -> Lifter | None: ...

__all__: list[str]
