from __future__ import annotations

from enum import Enum
from typing import Any

from binlex import Architecture, Configuration
from binlex.controlflow import Block, Function, Instruction
from binlex.semantics import InstructionSemantics

from . import llvm
from . import vex

class UnsupportedCapabilityError(RuntimeError): ...

class LifterBackend(str, Enum):
    DEFAULT: str
    LLVM: str
    VEX: str

class Lifter:
    @property
    def backend(self) -> LifterBackend: ...
    @property
    def architecture(self) -> Architecture: ...
    @property
    def configuration(self) -> Configuration: ...
    def __init__(self, architecture: Architecture, configuration: Configuration, backend: LifterBackend = LifterBackend.DEFAULT) -> None: ...
    def lift_instruction(self, instruction: Instruction) -> Lifter | None: ...
    def lift_block(self, block: Block) -> Lifter | None: ...
    def lift_function(self, function: Function) -> Lifter | None: ...
    def lift_semantics(self, semantics: list[InstructionSemantics]) -> Lifter | None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def bitcode(self) -> bytes: ...
    def object(self) -> bytes: ...
    def verify(self) -> Any: ...
    def optimizers(self) -> Optimizers: ...
    def mem2reg(self) -> Lifter: ...
    def instcombine(self) -> Lifter: ...
    def cfg(self) -> Lifter: ...
    def gvn(self) -> Lifter: ...
    def sroa(self) -> Lifter: ...
    def dce(self) -> Lifter: ...

class Optimizers:
    def optimizers(self) -> Optimizers: ...
    def mem2reg(self) -> Optimizers: ...
    def instcombine(self) -> Optimizers: ...
    def cfg(self) -> Optimizers: ...
    def gvn(self) -> Optimizers: ...
    def sroa(self) -> Optimizers: ...
    def dce(self) -> Optimizers: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def bitcode(self) -> bytes: ...
    def object(self) -> bytes: ...
    def verify(self) -> Any: ...

__all__: list[str]
