from __future__ import annotations

from binlex import Config
from binlex.controlflow import Block, Function, Instruction

class Optimizers:
    def optimizers(self) -> Optimizers: ...
    def mem2reg(self) -> Optimizers: ...
    def instcombine(self) -> Optimizers: ...
    def cfg(self) -> Optimizers: ...
    def gvn(self) -> Optimizers: ...
    def sroa(self) -> Optimizers: ...
    def dce(self) -> Optimizers: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def bitcode(self) -> bytes: ...
    def normalized(self) -> Lifter: ...
    def verify(self) -> bool: ...
    def __str__(self) -> str: ...

class Lifter:
    def __init__(self, config: Config) -> None: ...
    def lift_instruction(self, instruction: Instruction) -> Lifter: ...
    def lift_block(self, block: Block) -> Lifter: ...
    def lift_function(self, function: Function) -> Lifter: ...
    def optimizers(self) -> Optimizers: ...
    def mem2reg(self) -> Lifter: ...
    def instcombine(self) -> Lifter: ...
    def cfg(self) -> Lifter: ...
    def gvn(self) -> Lifter: ...
    def sroa(self) -> Lifter: ...
    def dce(self) -> Lifter: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def bitcode(self) -> bytes: ...
    def normalized(self) -> Lifter: ...
    def verify(self) -> bool: ...
    def __str__(self) -> str: ...


__all__ = ["Lifter", "Optimizers"]
