from __future__ import annotations

from binlex import Configuration
from binlex.controlflow import Block, Function, Instruction
from binlex.ir.lir import LirAbi


class Lifter:
    def __init__(self, config: Configuration, triple: str | None = None) -> None: ...
    def lift_instruction(self, instruction: Instruction) -> Lifter | None: ...
    def lift_block(self, block: Block, abi: LirAbi | None = None) -> Lifter | None: ...
    def lift_function(self, function: Function, abi: LirAbi | None = None) -> Lifter | None: ...
    def clear(self) -> Lifter | None: ...
    def ir(self) -> str: ...
    def print(self) -> None: ...
    def __str__(self) -> str: ...


__all__ = ["Lifter"]
