from __future__ import annotations

from binlex import Config
from binlex.controlflow import Block, Function, Instruction


class Lifter:
    def __init__(self, config: Config) -> None: ...
    def lift_instruction(self, instruction: Instruction) -> Lifter | None: ...
    def lift_block(self, block: Block) -> Lifter | None: ...
    def lift_function(self, function: Function) -> Lifter | None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def __str__(self) -> str: ...


__all__ = ["Lifter"]
