from __future__ import annotations

from binlex import Architecture, Config

class LifterJsonDeserializer:
    def __init__(self, string: str, config: Config) -> None: ...
    def architecture(self) -> Architecture: ...
    def address(self) -> int: ...
    def bytes(self) -> bytes: ...
    def ir_string(self) -> str: ...
    def ir(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def process(self) -> dict[str, object]: ...
    def print(self) -> None: ...

class Lifter:
    def __init__(self, architecture: Architecture, bytes: bytes, address: int, config: Config) -> None: ...
    def architecture(self) -> Architecture: ...
    def address(self) -> int: ...
    def bytes(self) -> bytes: ...
    def ir(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def print(self) -> None: ...

__all__: list[str]
