from __future__ import annotations

from typing import Any

from binlex import Configuration
from binlex.irs.lir import LirBlock, LirCpu, LirFunction, LirModule


class NativeFunction:
    def name(self) -> str: ...
    def address(self) -> int: ...
    def __call__(self, *args: Any) -> Any: ...


class LlvmBlock:
    @classmethod
    def from_lir(
        cls,
        lir_block: LirBlock,
        cpu: LirCpu,
        config: Configuration,
        triple: str | None = None,
    ) -> LlvmBlock: ...
    def name(self) -> str: ...
    def text(self) -> str | None: ...
    def print(self) -> bool: ...


class LlvmFunction:
    def __init__(self, name: str | None = None) -> None: ...
    @classmethod
    def from_lir(
        cls,
        lir_function: LirFunction,
        cpu: LirCpu,
        config: Configuration,
        triple: str | None = None,
    ) -> LlvmFunction: ...
    def name(self) -> str: ...
    def set_name(self, name: str) -> LlvmFunction | None: ...
    def blocks(self) -> list[LlvmBlock]: ...
    def append_block(self, block: object, name: str | None = None) -> LlvmFunction | None: ...
    def append_block_lir(self, lir: LirBlock, name: str | None = None) -> LlvmFunction | None: ...
    def set_lir(self, lir: LirFunction) -> LlvmFunction | None: ...
    def optimize_mem2reg(self) -> LlvmFunction | None: ...
    def optimize_instcombine(self) -> LlvmFunction | None: ...
    def optimize_cfg(self) -> LlvmFunction | None: ...
    def optimize_gvn(self) -> LlvmFunction | None: ...
    def optimize_sroa(self) -> LlvmFunction | None: ...
    def optimize_dce(self) -> LlvmFunction | None: ...
    def text(self) -> str | None: ...
    def set_text(self, text: str) -> LlvmFunction | None: ...
    def set_bitcode(self, bitcode: bytes) -> LlvmFunction | None: ...
    def print(self) -> bool: ...
    def bitcode(self) -> bytes | None: ...
    def object(self) -> bytes | None: ...
    def jit(
        self,
        return_type: object | None = None,
        parameter_types: list[object] | None = None,
        links: dict[str, object] | None = None,
    ) -> NativeFunction | None: ...


class LlvmModule:
    def __init__(self, name: str | None, cpu: Any, triple: str | None = None) -> None: ...
    def from_lir(
        self,
        lir_module: LirModule,
        config: Configuration,
    ) -> LlvmModule | None: ...
    def set_abi(self, abi: object | None = None) -> LlvmModule | None: ...
    def append_block_lir(self, lir: LirBlock) -> LlvmModule | None: ...
    def append_function_lir(self, lir: LirFunction, name: str | None = None) -> LlvmModule | None: ...
    def append_function(self, function: LlvmFunction) -> LlvmModule: ...
    def functions(self) -> list[LlvmFunction]: ...
    def clear(self) -> LlvmModule | None: ...
    def optimize(self) -> LlvmModule: ...
    def optimize_mem2reg(self) -> LlvmModule | None: ...
    def optimize_instcombine(self) -> LlvmModule | None: ...
    def optimize_cfg(self) -> LlvmModule | None: ...
    def optimize_gvn(self) -> LlvmModule | None: ...
    def optimize_sroa(self) -> LlvmModule | None: ...
    def optimize_dce(self) -> LlvmModule | None: ...
    def text(self) -> str: ...
    def set_text(self, text: str) -> LlvmModule | None: ...
    def set_bitcode(self, bitcode: bytes) -> LlvmModule | None: ...
    def print(self) -> None: ...
    def bitcode(self) -> bytes: ...
    def object(self) -> bytes: ...
    def verify(self) -> bool | None: ...
    def __str__(self) -> str: ...


__all__: list[str]
