from __future__ import annotations

from typing import Any

from binlex.formats import Image


class AstValue:
    @classmethod
    @classmethod
    def named(cls, name: str, ty: Any) -> AstValue: ...
    @classmethod
    def integer(cls, value: int, bits: int) -> AstValue: ...
    @classmethod
    def boolean(cls, value: bool) -> AstValue: ...
    @classmethod
    def null(cls, ty: Any) -> AstValue: ...
    @classmethod
    def undef(cls, ty: Any) -> AstValue: ...


class AstNamedValue(AstValue):
    def __init__(self, name: str, ty: Any) -> None: ...


class AstIntegerValue(AstValue):
    def __init__(self, value: int, bits: int) -> None: ...


class AstBooleanValue(AstValue):
    def __init__(self, value: bool) -> None: ...


class AstNullValue(AstValue):
    def __init__(self, ty: Any) -> None: ...


class AstUndefValue(AstValue):
    def __init__(self, ty: Any) -> None: ...


class AstType:
    @classmethod
    def void(cls) -> AstType: ...
    @classmethod
    def integer(cls, bits: int) -> AstType: ...
    @classmethod
    def float(cls, bits: int) -> AstType: ...
    @classmethod
    def pointer(cls, pointee: AstType) -> AstType: ...
    @classmethod
    def function(
        cls,
        parameters: list[AstType] | None = None,
        returns: list[AstType] | None = None,
    ) -> AstType: ...
    @classmethod
    def memory(cls) -> AstType: ...
    @classmethod
    def type_definition(cls, name: str) -> AstType: ...
    @classmethod
    def structure(
        cls,
        name: str,
        members: list[AstStructureMember] | None = None,
    ) -> AstType: ...
    @classmethod
    def union(
        cls,
        name: str,
        members: list[AstUnionMember] | None = None,
    ) -> AstType: ...
    @classmethod


class AstVoid(AstType):
    def __init__(self) -> None: ...


class AstInteger(AstType):
    def __init__(self, bits: int) -> None: ...


class AstFloat(AstType):
    def __init__(self, bits: int) -> None: ...


class AstPointer(AstType):
    def __init__(self, pointee: AstType) -> None: ...


class AstFunctionType(AstType):
    def __init__(
        self,
        parameters: list[AstType] | None = None,
        returns: list[AstType] | None = None,
    ) -> None: ...


class AstTypeDefinition(AstType):
    def __init__(self, name: str) -> None: ...


class AstStructure(AstType):
    def __init__(
        self,
        name: str,
        members: list[AstStructureMember] | None = None,
    ) -> None: ...


class AstUnion(AstType):
    def __init__(
        self,
        name: str,
        members: list[AstUnionMember] | None = None,
    ) -> None: ...


class AstMemory(AstType):
    def __init__(self) -> None: ...


class AstStructureMember:
    def __init__(self, name: str, ty: AstType) -> None: ...
    @classmethod
    def name(self) -> str: ...


class AstUnionMember:
    def __init__(self, name: str, ty: AstType) -> None: ...
    @classmethod
    def name(self) -> str: ...


class AstExpression:
    @classmethod
    @classmethod
    def value(cls, value: AstValue) -> AstExpression: ...
    @classmethod
    def call(
        cls,
        target: AstTarget,
        arguments: list[AstExpression] | None = None,
        return_types: list[Any] | None = None,
    ) -> AstExpression: ...
    @classmethod
    def member(cls, base: AstExpression, name: str, ty: AstType) -> AstExpression: ...


class AstValueExpression(AstExpression):
    def __init__(self, value: AstValue) -> None: ...


class AstCallExpression(AstExpression):
    def __init__(
        self,
        target: AstTarget,
        arguments: list[AstExpression] | None = None,
        return_types: list[AstType] | None = None,
    ) -> None: ...


class AstMemberExpression(AstExpression):
    def __init__(self, base: AstExpression, name: str, ty: AstType) -> None: ...


class AstUnaryExpression(AstExpression):
    def __init__(self, op: str, value: AstExpression, ty: AstType) -> None: ...


class AstBinaryExpression(AstExpression):
    def __init__(self, op: str, lhs: AstExpression, rhs: AstExpression, ty: AstType) -> None: ...


class AstCastExpression(AstExpression):
    def __init__(self, op: str, value: AstExpression, ty: AstType) -> None: ...


class AstLoadExpression(AstExpression):
    def __init__(self, address_space: Any, address: AstExpression, ty: AstType) -> None: ...


class AstAddressOfExpression(AstExpression):
    def __init__(self, place: AstPlace, ty: AstType) -> None: ...


class AstDereferenceExpression(AstExpression):
    def __init__(self, pointer: AstExpression, ty: AstType) -> None: ...


class AstIndexExpression(AstExpression):
    def __init__(self, base: AstExpression, index: AstExpression, ty: AstType) -> None: ...


class AstCompareExpression(AstExpression):
    def __init__(self, op: str, lhs: AstExpression, rhs: AstExpression, ty: AstType) -> None: ...


class AstSelectExpression(AstExpression):
    def __init__(
        self,
        condition: AstExpression,
        when_true: AstExpression,
        when_false: AstExpression,
        ty: AstType,
    ) -> None: ...


class AstPlace:
    @classmethod
    @classmethod
    def named(cls, name: str, ty: Any) -> AstPlace: ...


class AstNamedPlace(AstPlace):
    def __init__(self, name: str, ty: AstType) -> None: ...


class AstDereferencePlace(AstPlace):
    def __init__(self, pointer: AstExpression, ty: AstType) -> None: ...


class AstIndexPlace(AstPlace):
    def __init__(self, base: AstExpression, index: AstExpression, ty: AstType) -> None: ...


class AstTarget:
    @classmethod
    @classmethod
    def direct(cls, name: str) -> AstTarget: ...
    @classmethod
    def indirect(cls, expression: AstExpression) -> AstTarget: ...


class AstStatement:
    @classmethod
    @classmethod
    def assign(cls, target: AstPlace, value: AstExpression) -> AstStatement: ...
    @classmethod
    def expr(cls, value: AstExpression) -> AstStatement: ...
    @classmethod
    def comment(cls, comment: str) -> AstStatement: ...
    @classmethod
    def return_(cls, values: list[AstExpression] | None = None) -> AstStatement: ...
    @classmethod
    def label(cls, name: str) -> AstStatement: ...
    @classmethod
    def goto(cls, target: AstTarget) -> AstStatement: ...
    @classmethod
    def break_(cls) -> AstStatement: ...
    @classmethod
    def continue_(cls) -> AstStatement: ...
    @classmethod
    def trap(cls) -> AstStatement: ...
    @classmethod
    def unreachable(cls) -> AstStatement: ...


class AstAssignStatement(AstStatement):
    def __init__(self, target: AstPlace, value: AstExpression) -> None: ...


class AstReturnStatement(AstStatement):
    def __init__(self, values: list[AstExpression] | None = None) -> None: ...


class AstCommentStatement(AstStatement):
    def __init__(self, comment: str) -> None: ...


class AstExpressionStatement(AstStatement):
    def __init__(self, value: AstExpression) -> None: ...


class AstLabelStatement(AstStatement):
    def __init__(self, name: str) -> None: ...


class AstGotoStatement(AstStatement):
    def __init__(self, target: AstTarget) -> None: ...


class AstBreakStatement(AstStatement):
    def __init__(self) -> None: ...


class AstContinueStatement(AstStatement):
    def __init__(self) -> None: ...


class AstBlock:
    def __init__(self, statements: list[AstStatement] | None = None) -> None: ...
    @classmethod
    def statements(self) -> list[AstStatement]: ...
    def append_statement(self, statement: AstStatement) -> None: ...
    def append_comment(self, comment: str) -> None: ...


class AstParameter:
    def __init__(self, name: str, ty: Any, comment: str | None = None) -> None: ...
    @classmethod
    def name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def comment(self) -> str | None: ...
    def set_comment(self, comment: str | None) -> None: ...


class AstLocal:
    def __init__(
        self,
        name: str,
        ty: Any,
        init: AstExpression | None = None,
        display_name: str | None = None,
        comment: str | None = None,
    ) -> None: ...
    @classmethod
    def name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def display_name(self) -> str | None: ...
    def set_display_name(self, display_name: str | None) -> None: ...
    def rename(self, display_name: str) -> None: ...
    def comment(self) -> str | None: ...
    def set_comment(self, comment: str | None) -> None: ...


class AstFunction:
    def __init__(self, name: str | None = None) -> None: ...
    @classmethod
    @classmethod
    def from_hir(cls, hir_function: Any) -> AstFunction: ...
    def optimize(self) -> None: ...
    def comment(self) -> str | None: ...
    def set_comment(self, comment: str | None) -> None: ...
    def set_returns(self, returns: list[AstType]) -> None: ...
    def append_return(self, ty: AstType) -> None: ...
    def parameters(self) -> list[AstParameter]: ...
    def locals(self) -> list[AstLocal]: ...
    def blocks(self) -> list[AstBlock]: ...
    def append_parameter(self, parameter: AstParameter) -> None: ...
    def append_local(self, local: AstLocal) -> None: ...
    def append_block(self, block: AstBlock) -> None: ...
    def rename_local(self, name: str, display_name: str) -> bool: ...
    def set_local_comment(self, name: str, comment: str | None) -> bool: ...
    def c(self, image: Image | None = None) -> str: ...
    def print_c(self, image: Image | None = None) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...


class AstModule:
    def __init__(self, name: str | None = None) -> None: ...
    @classmethod
    @classmethod
    def from_hir(cls, hir_module: Any) -> AstModule: ...
    def optimize(self) -> None: ...
    def functions(self) -> list[AstFunction]: ...
    def append_function(self, function: AstFunction) -> None: ...
    def c(self) -> str: ...
    def print_c(self) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...


__all__: list[str]
