from __future__ import annotations

from typing import Any

from binlex import Configuration
from binlex.ir.lir import LirBlock, LirFunction, LirModule


class NativeFunction:
    def name(self) -> str: ...
    def address(self) -> int: ...
    def __call__(self, *args: Any) -> Any: ...


class LlvmBlock:
    @classmethod
    def from_lir(
        cls,
        lir_block: LirBlock,
        name: str | None = None,
        triple: str | None = None,
        config: Configuration | None = None,
    ) -> LlvmBlock: ...
    def name(self) -> str: ...
    def ir(self) -> str | None: ...
    def text(self) -> str | None: ...
    def print(self) -> bool: ...


class LlvmFunction:
    @classmethod
    def from_lir(
        cls,
        lir_function: LirFunction,
        name: str | None = None,
        triple: str | None = None,
        config: Configuration | None = None,
    ) -> LlvmFunction: ...
    def name(self) -> str: ...
    def set_name(self, name: str) -> LlvmFunction | None: ...
    def blocks(self) -> list[LlvmBlock]: ...
    def optimize_mem2reg(self) -> LlvmFunction | None: ...
    def optimize_instcombine(self) -> LlvmFunction | None: ...
    def optimize_cfg(self) -> LlvmFunction | None: ...
    def optimize_gvn(self) -> LlvmFunction | None: ...
    def optimize_sroa(self) -> LlvmFunction | None: ...
    def optimize_dce(self) -> LlvmFunction | None: ...
    def ir(self) -> str | None: ...
    def text(self) -> str | None: ...
    def set_ir(self, ir: str) -> LlvmFunction | None: ...
    def set_bitcode(self, bitcode: bytes) -> LlvmFunction | None: ...
    def print(self) -> bool: ...
    def bitcode(self) -> bytes | None: ...
    def object(self) -> bytes | None: ...
    def jit(
        self,
        return_type: object | None = None,
        parameter_types: list[object] | None = None,
        links: dict[str, object] | None = None,
    ) -> NativeFunction | None: ...


class LlvmModule:
    def __init__(self, cpu: Any, config: Configuration, triple: str | None = None) -> None: ...
    @classmethod
    def from_lir(
        cls,
        lir_module: LirModule,
        name: str | None = None,
        triple: str | None = None,
        config: Configuration | None = None,
    ) -> LlvmModule: ...
    def lift_instruction(self, instruction: object) -> LlvmModule | None: ...
    def lift_block(self, block: object, abi: object | None = None) -> LlvmModule | None: ...
    def lift_function(self, function: object, abi: object | None = None) -> LlvmModule | None: ...
    def lift_block_semantics(self, semantics: object, abi: object | None = None) -> LlvmModule | None: ...
    def lift_function_semantics(self, semantics: object, abi: object | None = None, name: str | None = None) -> LlvmModule | None: ...
    def create_function(self, name: str, abi: object | None = None) -> LlvmFunction: ...
    def functions(self) -> list[LlvmFunction]: ...
    def clear(self) -> LlvmModule | None: ...
    def optimize(self) -> LlvmModule: ...
    def optimize_mem2reg(self) -> LlvmModule | None: ...
    def optimize_instcombine(self) -> LlvmModule | None: ...
    def optimize_cfg(self) -> LlvmModule | None: ...
    def optimize_gvn(self) -> LlvmModule | None: ...
    def optimize_sroa(self) -> LlvmModule | None: ...
    def optimize_dce(self) -> LlvmModule | None: ...
    def ir(self) -> str: ...
    def text(self) -> str: ...
    def set_ir(self, ir: str) -> LlvmModule | None: ...
    def set_bitcode(self, bitcode: bytes) -> LlvmModule | None: ...
    def print(self) -> None: ...
    def bitcode(self) -> bytes: ...
    def object(self) -> bytes: ...
    def verify(self) -> bool | None: ...
    def __str__(self) -> str: ...


__all__: list[str]
