from __future__ import annotations

from binlex import Configuration
from binlex.irs.lir import LirModule


class VexModule:
    def __init__(self, name: str | None = None) -> None: ...
    def from_lir(self, module: LirModule, config: Configuration) -> VexModule | None: ...
    def name(self) -> str | None: ...
    def functions(self) -> list[VexFunction]: ...
    def append_function(self, function: VexFunction) -> VexModule: ...
    def clear(self) -> VexModule | None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def __str__(self) -> str: ...


class VexFunction:
    def __init__(self, name: str | None = None) -> None: ...
    def name(self) -> str | None: ...
    def blocks(self) -> list[VexBlock]: ...
    def append_block(self, block: VexBlock) -> VexFunction: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def __str__(self) -> str: ...


class VexBlock:
    def __init__(self, name: str | None = None) -> None: ...
    def name(self) -> str | None: ...
    def statements(self) -> list[VexStatement]: ...
    def append_statement(self, statement: VexStatement) -> VexBlock: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def __str__(self) -> str: ...


class VexStatement:
    def __init__(self, text: str) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def __str__(self) -> str: ...


__all__: list[str]
