from __future__ import annotations

from typing import Any

from binlex.core import Architecture


class LirCpuRegister:
    def __init__(self, name: str, bits: int) -> None: ...
    def name(self) -> str: ...
    def bits(self) -> int: ...


class LirCpuAlias:
    def __init__(
        self,
        name: str,
        parent: str,
        offset: int,
        bits: int,
        write_policy: str | None = None,
    ) -> None: ...
    def name(self) -> str: ...
    def parent(self) -> str: ...
    def offset(self) -> int: ...
    def bits(self) -> int: ...
    def write_policy(self) -> str: ...


class LirCpuProgramCounter:
    def __init__(self, name: str, bits: int) -> None: ...
    def name(self) -> str: ...
    def bits(self) -> int: ...


class LirMemoryIndexed:
    def __init__(self, name: str) -> None: ...
    def name(self) -> str: ...


class LirMemoryStack:
    def __init__(self, name: str) -> None: ...
    def name(self) -> str: ...


class LirMemoryAddressed:
    def __init__(self, name: str, address_bits: int, endian: LirCpuEndian) -> None: ...
    def name(self) -> str: ...
    def address_bits(self) -> int: ...
    def endian(self) -> LirCpuEndian: ...


class LirCpuEndian:
    Little: "LirCpuEndian"
    Big: "LirCpuEndian"


class LirCpuKind:
    I386: "LirCpuKind"
    Amd64: "LirCpuKind"
    Arm64: "LirCpuKind"
    Cil: "LirCpuKind"


class LirCpu:
    def __init__(
        self,
        *,
        name: str,
        address_bits: int,
        endian: LirCpuEndian,
        registers: list[LirCpuRegister] | None = None,
        aliases: list[LirCpuAlias] | None = None,
        program_counter: LirCpuProgramCounter | None = None,
        memory: list[
            LirMemoryIndexed | LirMemoryStack | LirMemoryAddressed
        ] | None = None,
    ) -> None: ...
    def kind(self) -> LirCpuKind | None: ...
    def name(self) -> str: ...
    def address_bits(self) -> int: ...
    def endian(self) -> LirCpuEndian: ...


class LirCpuI386(LirCpu):
    def __init__(self) -> None: ...


class LirCpuAmd64(LirCpu):
    def __init__(self) -> None: ...


class LirCpuArm64(LirCpu):
    def __init__(self) -> None: ...


class LirCpuCil(LirCpu):
    def __init__(self) -> None: ...


class LirAbiKind:
    SysV: "LirAbiKind"
    Windows64: "LirAbiKind"
    Cdecl: "LirAbiKind"
    Stdcall: "LirAbiKind"
    Fastcall: "LirAbiKind"
    LinuxSyscall: "LirAbiKind"
    WindowsSyscall: "LirAbiKind"


class LirAbiTrap:
    def __init__(
        self,
        kind: LirTrapKind,
        argument_registers: list[LirLocation] | None = None,
        number_register: LirLocation | None = None,
        result_registers: list[LirLocation] | None = None,
        shadow_registers: list[LirLocation] | None = None,
    ) -> None: ...


class LirAbi:
    def __init__(
        self,
        *,
        name: str,
        cpu: LirCpu,
        function_arguments: list[LirLocation] | None = None,
        return_locations: list[LirLocation] | None = None,
        function_return_bits: int | None = None,
        traps: list[LirAbiTrap] | None = None,
    ) -> None: ...


class LirAbiSysv(LirAbi):
    def __init__(self, cpu: LirCpu) -> None: ...


class LirAbiWindows64(LirAbi):
    def __init__(self, cpu: LirCpu) -> None: ...


class LirAbiCdecl(LirAbi):
    def __init__(self, cpu: LirCpu) -> None: ...


class LirAbiStdcall(LirAbi):
    def __init__(self, cpu: LirCpu) -> None: ...


class LirAbiFastcall(LirAbi):
    def __init__(self, cpu: LirCpu) -> None: ...


class LirAbiLinuxSyscall(LirAbi):
    def __init__(self, cpu: LirCpu) -> None: ...


class LirAbiWindowsSyscall(LirAbi):
    def __init__(self, cpu: LirCpu) -> None: ...


class LirStatus:
    Partial: LirStatus
    Complete: LirStatus
    def __str__(self) -> str: ...


class LirLocationKind:
    Register: LirLocationKind
    Flag: LirLocationKind
    ProgramCounter: LirLocationKind
    Temporary: LirLocationKind
    Memory: LirLocationKind
    def __str__(self) -> str: ...


class LirEffectKind:
    Set: LirEffectKind
    Store: LirEffectKind
    MemorySet: LirEffectKind
    MemoryCopy: LirEffectKind
    AtomicCmpXchg: LirEffectKind
    WriteProperty: LirEffectKind
    WriteElement: LirEffectKind
    Push: LirEffectKind
    Pop: LirEffectKind
    Fence: LirEffectKind
    Trap: LirEffectKind
    Intrinsic: LirEffectKind
    Nop: LirEffectKind
    def __str__(self) -> str: ...


class LirExpressionKind:
    Const: LirExpressionKind
    Function: LirExpressionKind
    DataAddress: LirExpressionKind
    AddressOf: LirExpressionKind
    Read: LirExpressionKind
    Load: LirExpressionKind
    Unary: LirExpressionKind
    Binary: LirExpressionKind
    Cast: LirExpressionKind
    Compare: LirExpressionKind
    Select: LirExpressionKind
    Extract: LirExpressionKind
    Concat: LirExpressionKind
    Undefined: LirExpressionKind
    Poison: LirExpressionKind
    Intrinsic: LirExpressionKind
    Null: LirExpressionKind
    Allocate: LirExpressionKind
    ReadProperty: LirExpressionKind
    ReadElement: LirExpressionKind
    def __str__(self) -> str: ...


class LirTerminatorKind:
    FallThrough: LirTerminatorKind
    Jump: LirTerminatorKind
    Branch: LirTerminatorKind
    Call: LirTerminatorKind
    Return: LirTerminatorKind
    Unreachable: LirTerminatorKind
    Trap: LirTerminatorKind
    def __str__(self) -> str: ...


class LirOperationUnary:
    Not: LirOperationUnary
    Neg: LirOperationUnary
    BitReverse: LirOperationUnary
    ByteSwap: LirOperationUnary
    CountLeadingZeros: LirOperationUnary
    CountTrailingZeros: LirOperationUnary
    PopCount: LirOperationUnary
    Sqrt: LirOperationUnary
    Abs: LirOperationUnary
    def __str__(self) -> str: ...


class LirOperationBinary:
    Add: LirOperationBinary
    AddWithCarry: LirOperationBinary
    Sub: LirOperationBinary
    SubWithBorrow: LirOperationBinary
    Mul: LirOperationBinary
    UMulHigh: LirOperationBinary
    SMulHigh: LirOperationBinary
    UDiv: LirOperationBinary
    SDiv: LirOperationBinary
    URem: LirOperationBinary
    SRem: LirOperationBinary
    And: LirOperationBinary
    Or: LirOperationBinary
    Xor: LirOperationBinary
    Shl: LirOperationBinary
    LShr: LirOperationBinary
    AShr: LirOperationBinary
    RotateLeft: LirOperationBinary
    RotateRight: LirOperationBinary
    MinUnsigned: LirOperationBinary
    MinSigned: LirOperationBinary
    MaxUnsigned: LirOperationBinary
    MaxSigned: LirOperationBinary
    def __str__(self) -> str: ...


class LirOperationCast:
    ZeroExtend: LirOperationCast
    SignExtend: LirOperationCast
    Truncate: LirOperationCast
    Bitcast: LirOperationCast
    IntToFloat: LirOperationCast
    FloatToInt: LirOperationCast
    FloatExtend: LirOperationCast
    FloatTruncate: LirOperationCast
    def __str__(self) -> str: ...


class LirOperationCompare:
    Eq: LirOperationCompare
    Ne: LirOperationCompare
    Ult: LirOperationCompare
    Ule: LirOperationCompare
    Ugt: LirOperationCompare
    Uge: LirOperationCompare
    Slt: LirOperationCompare
    Sle: LirOperationCompare
    Sgt: LirOperationCompare
    Sge: LirOperationCompare
    Ordered: LirOperationCompare
    Unordered: LirOperationCompare
    Oeq: LirOperationCompare
    One: LirOperationCompare
    Olt: LirOperationCompare
    Ole: LirOperationCompare
    Ogt: LirOperationCompare
    Oge: LirOperationCompare
    Ueq: LirOperationCompare
    Une: LirOperationCompare
    UltFp: LirOperationCompare
    UleFp: LirOperationCompare
    UgtFp: LirOperationCompare
    UgeFp: LirOperationCompare
    def __str__(self) -> str: ...


class LirAddressSpace:
    Default: LirAddressSpace
    Stack: LirAddressSpace
    Heap: LirAddressSpace
    Global: LirAddressSpace
    Io: LirAddressSpace
    @staticmethod
    def cpu_memory(name: str) -> LirAddressSpace: ...
    @staticmethod
    def segment(name: str) -> LirAddressSpace: ...
    @staticmethod
    def named(name: str) -> LirAddressSpace: ...
    def __str__(self) -> str: ...


class LirFenceKind:
    Acquire: LirFenceKind
    Release: LirFenceKind
    AcquireRelease: LirFenceKind
    SequentiallyConsistent: LirFenceKind
    @staticmethod
    def named(name: str) -> LirFenceKind: ...
    def __str__(self) -> str: ...


class LirTrapKind:
    Breakpoint: LirTrapKind
    DivideError: LirTrapKind
    Overflow: LirTrapKind
    InvalidOpcode: LirTrapKind
    GeneralProtection: LirTrapKind
    PageFault: LirTrapKind
    AlignmentFault: LirTrapKind
    Syscall: LirTrapKind
    Interrupt: LirTrapKind
    @staticmethod
    def named(name: str) -> LirTrapKind: ...
    def __str__(self) -> str: ...


class LirDiagnosticKind:
    UnsupportedInstruction: LirDiagnosticKind
    UnsupportedOperandForm: LirDiagnosticKind
    UnsupportedRegisterClass: LirDiagnosticKind
    UnsupportedVectorForm: LirDiagnosticKind
    UnsupportedFloatingPointForm: LirDiagnosticKind
    UnsupportedAtomicForm: LirDiagnosticKind
    PartialFlags: LirDiagnosticKind
    PartialMemoryModel: LirDiagnosticKind
    PartialExceptionModel: LirDiagnosticKind
    @staticmethod
    def named(name: str) -> LirDiagnosticKind: ...
    def __str__(self) -> str: ...


class LirTemporary:
    def __init__(self, id: int, bits: int, name: str | None = None) -> None: ...
    @classmethod
    def id(self) -> int: ...
    def bits(self) -> int: ...
    def name(self) -> str | None: ...
    def set_id(self, id: int) -> None: ...
    def set_bits(self, bits: int) -> None: ...
    def set_name(self, name: str | None) -> None: ...
    def print(self) -> None: ...


class LirDiagnostic:
    def __init__(self, kind: LirDiagnosticKind, message: str) -> None: ...
    @classmethod
    def kind(self) -> LirDiagnosticKind: ...
    def message(self) -> str: ...
    def set_kind(self, kind: LirDiagnosticKind) -> None: ...
    def set_message(self, message: str) -> None: ...
    def print(self) -> None: ...


class LirEncoding:
    def __init__(
        self,
        architecture: str,
        mnemonic: str,
        disassembly: str,
        address: int,
        bytes: bytes | None = None,
    ) -> None: ...
    @classmethod
    def architecture(self) -> str: ...
    def mnemonic(self) -> str: ...
    def disassembly(self) -> str: ...
    def address(self) -> int: ...
    def bytes(self) -> bytes: ...
    def set_architecture(self, architecture: str) -> None: ...
    def set_mnemonic(self, mnemonic: str) -> None: ...
    def set_disassembly(self, disassembly: str) -> None: ...
    def set_address(self, address: int) -> None: ...
    def set_bytes(self, bytes: bytes) -> None: ...
    def print(self) -> None: ...


class LirLocation:
    @classmethod
    @classmethod
    def register(cls, name: str, bits: int) -> LirLocation: ...
    @classmethod
    def flag(cls, name: str, bits: int) -> LirLocation: ...
    @classmethod
    def program_counter(cls, bits: int) -> LirLocation: ...
    @classmethod
    def temporary(cls, id: int, bits: int) -> LirLocation: ...
    @classmethod
    def memory(
        cls,
        address_space: LirAddressSpace,
        addr: LirExpression,
        bits: int,
    ) -> LirLocation: ...
    @classmethod
    def indexed_memory(
        cls, name: str, index: LirExpression, bits: int
    ) -> LirLocation: ...
    @classmethod
    def stack_memory(cls, name: str, offset: int, bits: int) -> LirLocation: ...
    def kind(self) -> LirLocationKind: ...
    def bits(self) -> int: ...
    def name(self) -> str | None: ...
    def set_kind(self, kind: LirLocationKind) -> None: ...
    def set_bits(self, bits: int) -> None: ...
    def set_name(self, name: str) -> None: ...
    def print(self) -> None: ...


class LirLocationRegister(LirLocation):
    def __init__(self, name: str, bits: int) -> None: ...


class LirLocationFlag(LirLocation):
    def __init__(self, name: str, bits: int) -> None: ...


class LirLocationProgramCounter(LirLocation):
    def __init__(self, bits: int) -> None: ...


class LirLocationTemporary(LirLocation):
    def __init__(self, id: int, bits: int) -> None: ...


class LirLocationMemory(LirLocation):
    def __init__(self, address_space: LirAddressSpace, addr: Any, bits: int) -> None: ...


class LirLocationIndexedMemory(LirLocation):
    def __init__(self, name: str, index: Any, bits: int) -> None: ...


class LirLocationStackMemory(LirLocation):
    def __init__(self, name: str, offset: int, bits: int) -> None: ...


class LirExpression:
    @classmethod
    @classmethod
    def const(cls, value: int, bits: int) -> LirExpression: ...
    @classmethod
    def function(cls, name: str, bits: int) -> LirExpression: ...
    @classmethod
    def data_address(cls, name: str, bits: int) -> LirExpression: ...
    @classmethod
    def address_of(cls, location: LirLocation, bits: int) -> LirExpression: ...
    @classmethod
    def read(cls, location: LirLocation) -> LirExpression: ...
    @classmethod
    def load(
        cls, address_space: LirAddressSpace, address: LirExpression, bits: int
    ) -> LirExpression: ...
    @classmethod
    def unary(
        cls, operation: LirOperationUnary, operand: LirExpression, bits: int
    ) -> LirExpression: ...
    @classmethod
    def binary(
        cls,
        operation: LirOperationBinary,
        lhs: LirExpression,
        rhs: LirExpression,
        bits: int,
    ) -> LirExpression: ...
    @classmethod
    def cast(
        cls, operation: LirOperationCast, operand: LirExpression, bits: int
    ) -> LirExpression: ...
    @classmethod
    def compare(
        cls,
        operation: LirOperationCompare,
        lhs: LirExpression,
        rhs: LirExpression,
    ) -> LirExpression: ...
    @classmethod
    def select(
        cls,
        condition: LirExpression,
        when_true: LirExpression,
        when_false: LirExpression,
        bits: int,
    ) -> LirExpression: ...
    @classmethod
    def extract(
        cls, operand: LirExpression, offset: int, bits: int
    ) -> LirExpression: ...
    @classmethod
    def concat(cls, parts: list[LirExpression], bits: int) -> LirExpression: ...
    @classmethod
    def undefined(cls, bits: int) -> LirExpression: ...
    @classmethod
    def poison(cls, bits: int) -> LirExpression: ...
    @classmethod
    def intrinsic(
        cls, name: str, operands: list[LirExpression], bits: int
    ) -> LirExpression: ...
    @classmethod
    def null(cls, bits: int) -> LirExpression: ...
    @classmethod
    def allocate(cls, kind: str, bits: int) -> LirExpression: ...
    @classmethod
    def read_property(
        cls, reference: LirExpression, name: str, bits: int
    ) -> LirExpression: ...
    @classmethod
    def read_element(
        cls, reference: LirExpression, index: LirExpression, bits: int
    ) -> LirExpression: ...
    def kind(self) -> LirExpressionKind: ...
    def operation(
        self,
    ) -> (
        LirOperationBinary
        | LirOperationUnary
        | LirOperationCast
        | LirOperationCompare
        | None
    ): ...
    def bits(self) -> int: ...
    def left(self) -> LirExpression | None: ...
    def right(self) -> LirExpression | None: ...
    def argument(self) -> LirExpression | None: ...
    def condition(self) -> LirExpression | None: ...
    def when_true(self) -> LirExpression | None: ...
    def when_false(self) -> LirExpression | None: ...
    def address(self) -> LirExpression | None: ...
    def address_space(self) -> LirAddressSpace | None: ...
    def location(self) -> LirLocation | None: ...
    def offset(self) -> int | None: ...
    def parts(self) -> list[LirExpression] | None: ...
    def name(self) -> str | None: ...
    def arguments(self) -> list[LirExpression] | None: ...
    def value(self) -> int | None: ...
    def set_kind(self, kind: LirExpressionKind) -> None: ...
    def set_operation(
        self,
        operation: LirOperationBinary | LirOperationUnary | LirOperationCast | LirOperationCompare,
    ) -> None: ...
    def set_bits(self, bits: int) -> None: ...
    def set_left(self, expression: LirExpression) -> None: ...
    def set_right(self, expression: LirExpression) -> None: ...
    def set_argument(self, expression: LirExpression) -> None: ...
    def set_condition(self, expression: LirExpression) -> None: ...
    def set_when_true(self, expression: LirExpression) -> None: ...
    def set_when_false(self, expression: LirExpression) -> None: ...
    def set_address(self, expression: LirExpression) -> None: ...
    def set_address_space(self, space: LirAddressSpace) -> None: ...
    def set_location(self, location: LirLocation) -> None: ...
    def set_offset(self, offset: int) -> None: ...
    def set_parts(self, parts: list[LirExpression]) -> None: ...
    def set_name(self, name: str) -> None: ...
    def set_arguments(self, arguments: list[LirExpression]) -> None: ...
    def set_value(self, value: int) -> None: ...
    def print(self) -> None: ...


class LirExpressionConst(LirExpression):
    def __init__(self, value: int, bits: int) -> None: ...


class LirExpressionFunction(LirExpression):
    def __init__(self, name: str, bits: int) -> None: ...


class LirExpressionDataAddress(LirExpression):
    def __init__(self, name: str, bits: int) -> None: ...


class LirExpressionAddressOf(LirExpression):
    def __init__(self, location: Any, bits: int) -> None: ...


class LirExpressionRead(LirExpression):
    def __init__(self, location: Any) -> None: ...


class LirExpressionLoad(LirExpression):
    def __init__(self, address_space: LirAddressSpace, addr: Any, bits: int) -> None: ...


class LirExpressionUnary(LirExpression):
    def __init__(self, op: LirOperationUnary, arg: Any, bits: int) -> None: ...


class LirExpressionBinary(LirExpression):
    def __init__(self, op: LirOperationBinary, left: Any, right: Any, bits: int) -> None: ...


class LirExpressionCast(LirExpression):
    def __init__(self, op: LirOperationCast, arg: Any, bits: int) -> None: ...


class LirExpressionCompare(LirExpression):
    def __init__(self, op: LirOperationCompare, left: Any, right: Any, bits: int) -> None: ...


class LirExpressionSelect(LirExpression):
    def __init__(self, condition: Any, when_true: Any, when_false: Any, bits: int) -> None: ...


class LirExpressionExtract(LirExpression):
    def __init__(self, arg: Any, lsb: int, bits: int) -> None: ...


class LirExpressionConcat(LirExpression):
    def __init__(self, parts: list[Any], bits: int) -> None: ...


class LirExpressionUndefined(LirExpression):
    def __init__(self, bits: int) -> None: ...


class LirExpressionPoison(LirExpression):
    def __init__(self, bits: int) -> None: ...


class LirExpressionIntrinsic(LirExpression):
    def __init__(self, name: str, args: list[Any], bits: int) -> None: ...


class LirExpressionNull(LirExpression):
    def __init__(self, bits: int) -> None: ...


class LirExpressionAllocate(LirExpression):
    def __init__(self, kind: str, bits: int) -> None: ...


class LirExpressionReadProperty(LirExpression):
    def __init__(self, reference: Any, name: str, bits: int) -> None: ...


class LirExpressionReadElement(LirExpression):
    def __init__(self, reference: Any, index: Any, bits: int) -> None: ...


class LirEffect:
    @classmethod
    @classmethod
    def set(
        cls, location: LirLocation, expression: LirExpression
    ) -> LirEffect: ...
    @classmethod
    def store(
        cls,
        address_space: LirAddressSpace,
        address: LirExpression,
        value: LirExpression,
        bits: int,
    ) -> LirEffect: ...
    @classmethod
    def write_property(
        cls,
        reference: LirExpression,
        name: str,
        expression: LirExpression,
        bits: int,
    ) -> LirEffect: ...
    @classmethod
    def write_element(
        cls,
        reference: LirExpression,
        index: LirExpression,
        expression: LirExpression,
        bits: int,
    ) -> LirEffect: ...
    @classmethod
    def push(cls, stack: str, expression: LirExpression) -> LirEffect: ...
    @classmethod
    def pop(cls, stack: str, dst: LirLocation) -> LirEffect: ...
    @classmethod
    def fence(cls, kind: LirFenceKind) -> LirEffect: ...
    @classmethod
    def trap(cls, kind: LirTrapKind) -> LirEffect: ...
    @classmethod
    def intrinsic(
        cls,
        name: str,
        operands: list[LirExpression],
        outputs: list[LirLocation],
    ) -> LirEffect: ...
    @classmethod
    def nop(cls) -> LirEffect: ...
    def kind(self) -> LirEffectKind: ...
    def expression(self) -> LirExpression | None: ...
    def location(self) -> LirLocation | None: ...
    def set_kind(self, kind: LirEffectKind) -> None: ...
    def set_expression(self, expression: LirExpression) -> None: ...
    def set_location(self, location: LirLocation) -> None: ...
    def print(self) -> None: ...


class LirEffectSet(LirEffect):
    def __init__(self, dst: Any, expression: Any) -> None: ...


class LirEffectStore(LirEffect):
    def __init__(self, address_space: LirAddressSpace, addr: Any, expression: Any, bits: int) -> None: ...


class LirEffectWriteProperty(LirEffect):
    def __init__(self, reference: Any, name: str, expression: Any, bits: int) -> None: ...


class LirEffectWriteElement(LirEffect):
    def __init__(self, reference: Any, index: Any, expression: Any, bits: int) -> None: ...


class LirEffectPush(LirEffect):
    def __init__(self, stack: str, expression: Any) -> None: ...


class LirEffectPop(LirEffect):
    def __init__(self, stack: str, dst: Any) -> None: ...


class LirEffectFence(LirEffect):
    def __init__(self, kind: LirFenceKind) -> None: ...


class LirEffectTrap(LirEffect):
    def __init__(self, kind: LirTrapKind) -> None: ...


class LirEffectIntrinsic(LirEffect):
    def __init__(self, name: str, args: list[Any] | None = None, outputs: list[Any] | None = None) -> None: ...


class LirEffectNop(LirEffect):
    def __init__(self) -> None: ...


class LirTerminator:
    @classmethod
    @classmethod
    def fallthrough(cls) -> LirTerminator: ...
    @classmethod
    def jump(cls, target: LirExpression) -> LirTerminator: ...
    @classmethod
    def branch(
        cls,
        condition: LirExpression,
        true_target: LirExpression,
        false_target: LirExpression,
    ) -> LirTerminator: ...
    @classmethod
    def call(
        cls,
        target: LirExpression,
        return_target: LirExpression | None = None,
        does_return: bool | None = None,
    ) -> LirTerminator: ...
    @classmethod
    def return_(cls, expression: LirExpression | None = None) -> LirTerminator: ...
    @classmethod
    def unreachable(cls) -> LirTerminator: ...
    @classmethod
    def trap(cls) -> LirTerminator: ...
    def kind(self) -> LirTerminatorKind: ...
    def condition(self) -> LirExpression | None: ...
    def true_target(self) -> LirExpression | None: ...
    def false_target(self) -> LirExpression | None: ...
    def target(self) -> LirExpression | None: ...
    def return_target(self) -> LirExpression | None: ...
    def does_return(self) -> bool | None: ...
    def return_expression(self) -> LirExpression | None: ...
    def set_kind(self, kind: LirTerminatorKind) -> None: ...
    def set_condition(self, expression: LirExpression) -> None: ...
    def set_true_target(self, expression: LirExpression) -> None: ...
    def set_false_target(self, expression: LirExpression) -> None: ...
    def set_target(self, expression: LirExpression) -> None: ...
    def set_return_target(self, expression: LirExpression | None) -> None: ...
    def set_does_return(self, does_return: bool | None) -> None: ...
    def set_return_expression(self, expression: LirExpression | None) -> None: ...
    def print(self) -> None: ...


class LirTerminatorFallThrough(LirTerminator):
    def __init__(self) -> None: ...


class LirTerminatorJump(LirTerminator):
    def __init__(self, target: Any) -> None: ...


class LirTerminatorBranch(LirTerminator):
    def __init__(self, condition: Any, true_target: Any, false_target: Any) -> None: ...


class LirTerminatorCall(LirTerminator):
    def __init__(
        self,
        target: Any,
        return_target: Any | None = None,
        does_return: bool | None = None,
    ) -> None: ...


class LirTerminatorReturn(LirTerminator):
    def __init__(self, expression: Any | None = None) -> None: ...


class LirTerminatorUnreachable(LirTerminator):
    def __init__(self) -> None: ...


class LirTerminatorTrap(LirTerminator):
    def __init__(self) -> None: ...


class Lir:
    def __init__(
        self,
        version: int,
        status: LirStatus,
        abi: LirAbi | None = None,
        encoding: LirEncoding | None = None,
        temporaries: list[LirTemporary] | None = None,
        effects: list[LirEffect] | None = None,
        terminator: LirTerminator | None = None,
        diagnostics: list[LirDiagnostic] | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> None: ...
    @classmethod
    def version(self) -> int: ...
    def status(self) -> LirStatus: ...
    def abi(self) -> LirAbi | None: ...
    def encoding(self) -> LirEncoding | None: ...
    def temporaries(self) -> list[LirTemporary]: ...
    def effects(self) -> list[LirEffect]: ...
    def terminator(self) -> LirTerminator: ...
    def diagnostics(self) -> list[LirDiagnostic]: ...
    def metadata(self) -> dict[str, Any]: ...
    def set_version(self, version: int) -> None: ...
    def set_status(self, status: LirStatus) -> None: ...
    def set_metadata(self, metadata: dict[str, Any]) -> None: ...
    def get_metadata_value(self, key: str) -> Any | None: ...
    def set_metadata_value(self, key: str, value: Any) -> None: ...
    def remove_metadata_value(self, key: str) -> None: ...
    def set_abi(self, abi: LirAbi | None) -> None: ...
    def set_encoding(self, encoding: LirEncoding | None) -> None: ...
    def set_temporaries(self, temporaries: list[LirTemporary]) -> None: ...
    def set_effects(self, effects: list[LirEffect]) -> None: ...
    def set_terminator(self, terminator: LirTerminator) -> None: ...
    def set_diagnostics(self, diagnostics: list[LirDiagnostic]) -> None: ...
    def optimize_constants(self) -> None: ...
    def optimize_identities(self) -> None: ...
    def optimize_casts(self) -> None: ...
    def optimize_noops(self) -> None: ...
    def optimize_branches(self) -> None: ...
    def optimize_intrinsics(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def print(self) -> None: ...
    def __str__(self) -> str: ...


class LirExecutor:
    def __init__(self) -> None: ...
    def step(self, lir: Any, state: Any) -> list[LirExecutorState]: ...
    def run(
        self,
        lir: Any,
        state: Any,
        steps: int | None = None,
    ) -> list[LirExecutorState]: ...
    def run_with_hooks(
        self,
        lir: Any,
        state: Any,
        steps: int | None = None,
    ) -> list[LirExecutorState]: ...
    def set_breakpoint(self, address: int) -> None: ...
    def remove_breakpoint(self, address: int) -> None: ...
    def clear_breakpoints(self) -> None: ...
    def breakpoints(self) -> list[int]: ...
    def add_hook(self, address: int, hook: Any) -> None: ...
    def remove_hook(self, address: int) -> None: ...
    def clear_hooks(self) -> None: ...
    def hooks(self) -> list[int]: ...


class LirExecutorState:
    def __init__(self, cpu: Any) -> None: ...
    def symbolize_register(self, name: str, bits: int, symbol: str | None = None) -> None: ...
    def set_register(self, name: str, bits: int, value: int) -> None: ...
    def symbolic_register(self, name: str, bits: int) -> str | None: ...
    def evaluate_register(self, name: str, bits: int) -> int | None: ...
    def program_counter(self) -> int | None: ...
    def map_memory(self, address: int, size: int) -> None: ...
    def map_image(self, image: Any) -> None: ...
    def write_memory(self, address: int, data: bytes | bytearray | list[int]) -> None: ...
    def symbolize_memory(self, address: int, size: int, name: str | None = None) -> None: ...
    def symbolic_memory(self, address: int, size: int) -> str: ...
    def evaluate_memory(self, address: int, size: int) -> int | None: ...
    def read_memory(self, address: int, size: int) -> bytes | None: ...
    def slice_from_register(self, name: str, bits: int) -> Slice: ...
    def slice_from_memory(self, address: int, size: int) -> Slice: ...
    def constraints(self) -> list[str]: ...
    def satisfiable(self) -> bool: ...
    def model(self) -> dict[str, str]: ...


class SliceInstruction:
    def architecture(self) -> str: ...
    def mnemonic(self) -> str: ...
    def disassembly(self) -> str: ...
    def address(self) -> int: ...
    def bytes(self) -> bytes: ...


class SliceNode:
    def instruction(self) -> SliceInstruction | None: ...
    def location(self) -> str: ...
    def value(self) -> str: ...
    def parents(self) -> list[SliceNode]: ...


class Slice:
    def nodes(self) -> list[SliceNode]: ...
    def number_of_nodes(self) -> int: ...
    def is_empty(self) -> bool: ...


class LirData:
    def __init__(self, name: str, bytes: bytes | bytearray | list[int]) -> None: ...
    @classmethod
    def name(self) -> str: ...
    def bytes(self) -> bytes: ...
    def set_name(self, name: str) -> None: ...
    def set_bytes(self, bytes: bytes | bytearray | list[int]) -> None: ...
    def print(self) -> None: ...


class LirBlock:
    def __init__(
        self,
        name: str | None = None,
    ) -> None: ...
    @classmethod
    def name(self) -> str | None: ...
    def instructions(self) -> list[Lir]: ...
    def set_name(self, name: str | None) -> None: ...
    def append_instruction(self, instruction: Lir) -> None: ...
    def optimize_constants(self) -> None: ...
    def optimize_identities(self) -> None: ...
    def optimize_casts(self) -> None: ...
    def optimize_noops(self) -> None: ...
    def optimize_branches(self) -> None: ...
    def optimize_intrinsics(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...


class LirFunction:
    def __init__(
        self,
        name: str | None = None,
        abi: LirAbi | None = None,
    ) -> None: ...
    @classmethod
    def name(self) -> str | None: ...
    def abi(self) -> LirAbi | None: ...
    def blocks(self) -> list[LirBlock]: ...
    def set_name(self, name: str | None) -> None: ...
    def set_abi(self, abi: LirAbi | None) -> None: ...
    def append_block(self, block: LirBlock) -> None: ...
    def optimize_constants(self) -> None: ...
    def optimize_identities(self) -> None: ...
    def optimize_casts(self) -> None: ...
    def optimize_noops(self) -> None: ...
    def optimize_branches(self) -> None: ...
    def optimize_intrinsics(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...


class LirModule:
    def __init__(
        self,
        name: str | None = None,
    ) -> None: ...
    @classmethod
    @classmethod
    def from_text(cls, text: str) -> LirModule: ...
    @classmethod
    def from_bytecode(cls, bytecode: bytes) -> LirModule: ...
    def name(self) -> str | None: ...
    def functions(self) -> list[LirFunction]: ...
    def data(self) -> list[LirData]: ...
    def set_name(self, name: str | None) -> None: ...
    def append_function(self, function: LirFunction) -> None: ...
    def append_data(self, data: LirData) -> None: ...
    def optimize_constants(self) -> None: ...
    def optimize_identities(self) -> None: ...
    def optimize_casts(self) -> None: ...
    def optimize_noops(self) -> None: ...
    def optimize_branches(self) -> None: ...
    def optimize_intrinsics(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def bytecode(self) -> bytes: ...
    def mlir(self) -> LirMlirModule: ...
    def operation_names(self) -> list[str]: ...
    def operation_count(self) -> int: ...
    def operation_records(self) -> list[dict[str, object]]: ...
    def print(self) -> None: ...
    def print(self) -> None: ...


class LirMlirModule:
    def __init__(self, module: Any) -> None: ...
    @classmethod
    def from_text(cls, text: str) -> LirMlirModule: ...
    @classmethod
    def from_bytecode(cls, bytecode: bytes) -> LirMlirModule: ...
    def normalize_status(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def bytecode(self) -> bytes: ...
    def operation_names(self) -> list[str]: ...
    def operation_count(self) -> int: ...
    def operation_records(self) -> list[dict[str, object]]: ...
    def print(self) -> None: ...

__all__: list[str]
