from __future__ import annotations

from typing import Any


class MirCompareOp:
    Eq: MirCompareOp
    Ne: MirCompareOp
    Ult: MirCompareOp
    Ule: MirCompareOp
    Ugt: MirCompareOp
    Uge: MirCompareOp
    Slt: MirCompareOp
    Sle: MirCompareOp
    Sgt: MirCompareOp
    Sge: MirCompareOp


class MirCastOp:
    ZeroExtend: MirCastOp
    SignExtend: MirCastOp
    Truncate: MirCastOp
    Bitcast: MirCastOp


class MirTypeKind:
    Void: MirTypeKind
    Integer: MirTypeKind
    Float: MirTypeKind
    Pointer: MirTypeKind
    Memory: MirTypeKind
    Custom: MirTypeKind


class MirTerminatorKind:
    Jump: MirTerminatorKind
    CondBr: MirTerminatorKind
    Return: MirTerminatorKind
    Trap: MirTerminatorKind
    Unreachable: MirTerminatorKind


class MirType:
    @classmethod
    def void(cls) -> MirType: ...
    @classmethod
    def integer(cls, bits: int) -> MirType: ...
    @classmethod
    def float(cls, bits: int) -> MirType: ...
    @classmethod
    def pointer(cls, pointee: MirType) -> MirType: ...
    @classmethod
    def memory(cls) -> MirType: ...
    @classmethod
    def custom(cls, name: str) -> MirType: ...
    @classmethod
    def from_dict(cls, data: Any) -> MirType: ...
    def kind(self) -> MirTypeKind: ...
    def to_dict(self) -> Any: ...
    def json(self) -> str: ...


class MirValue:
    @classmethod
    def named(cls, name: str, ty: MirType) -> MirValue: ...
    @classmethod
    def integer(cls, value: int, bits: int) -> MirValue: ...
    @classmethod
    def boolean(cls, value: bool) -> MirValue: ...
    @classmethod
    def null(cls, ty: MirType) -> MirValue: ...
    @classmethod
    def undef(cls, ty: MirType) -> MirValue: ...
    @classmethod
    def from_dict(cls, data: Any) -> MirValue: ...
    def to_dict(self) -> Any: ...
    def json(self) -> str: ...


class MirAddressSpace:
    @classmethod
    def default_space(cls) -> MirAddressSpace: ...
    @classmethod
    def stack(cls) -> MirAddressSpace: ...
    @classmethod
    def heap(cls) -> MirAddressSpace: ...
    @classmethod
    def global_space(cls) -> MirAddressSpace: ...
    @classmethod
    def heap_object(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def global_object(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def io(cls) -> MirAddressSpace: ...
    @classmethod
    def local(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def argument(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def spill(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def incoming(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def saved_frame(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def return_address(cls, name: str) -> MirAddressSpace: ...
    @classmethod
    def named(cls, name: str) -> MirAddressSpace: ...


class MirBlockParameter:
    def __init__(self, ty: MirType, name: str | None = None) -> None: ...


class MirOperation:
    @classmethod
    def add(
        cls,
        lhs: MirValue,
        rhs: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def sub(
        cls,
        lhs: MirValue,
        rhs: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def mul(
        cls,
        lhs: MirValue,
        rhs: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def load(
        cls,
        address_space: MirAddressSpace,
        address: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def store(
        cls,
        address_space: MirAddressSpace,
        address: MirValue,
        value: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def icmp(
        cls,
        op: MirCompareOp,
        lhs: MirValue,
        rhs: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def cast(
        cls,
        op: MirCastOp,
        value: MirValue,
        ty: MirType,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def call(
        cls,
        target: str,
        arguments: list[MirValue] | None = None,
        result_types: list[MirType] | None = None,
        result: str | None = None,
    ) -> MirOperation: ...
    @classmethod
    def intrinsic(
        cls,
        name: str,
        arguments: list[MirValue] | None = None,
        result_types: list[MirType] | None = None,
        result: str | None = None,
    ) -> MirOperation: ...


class MirTerminator:
    @classmethod
    def jump(cls, target: str, arguments: list[MirValue] | None = None) -> MirTerminator: ...
    @classmethod
    def cond_br(
        cls,
        condition: MirValue,
        then_target: str,
        else_target: str,
        then_arguments: list[MirValue] | None = None,
        else_arguments: list[MirValue] | None = None,
    ) -> MirTerminator: ...
    @classmethod
    def return_(cls, values: list[MirValue] | None = None) -> MirTerminator: ...
    @classmethod
    def trap(cls) -> MirTerminator: ...
    @classmethod
    def unreachable(cls) -> MirTerminator: ...
    def kind(self) -> MirTerminatorKind: ...


class MirBlock:
    def __init__(self, name: str) -> None: ...
    def append_parameter(self, parameter: MirBlockParameter) -> None: ...
    def append_operation(self, operation: MirOperation) -> None: ...
    def set_terminator(self, terminator: MirTerminator) -> None: ...
    def name(self) -> str: ...
    def json(self) -> str: ...


class Mir:
    def __init__(self, name: str | None = None) -> None: ...
    @classmethod
    def from_dict(cls, data: Any) -> Mir: ...
    @classmethod
    def from_lir(cls, lir_module: Any, name: str | None = None) -> Mir: ...
    def append_block(self, block: MirBlock) -> None: ...
    def blocks(self) -> list[MirBlock]: ...
    def verify(self) -> None: ...
    def optimize_register_state(self) -> None: ...
    def optimize_returns(self) -> None: ...
    def optimize_blocks(self) -> None: ...
    def optimize_abi(self) -> None: ...
    def optimize_subexpressions(self) -> None: ...
    def optimize_flags(self) -> None: ...
    def optimize_liveness(self) -> None: ...
    def optimize_undefs(self) -> None: ...
    def optimize_intrinsics(self) -> None: ...
    def optimize_cse(self) -> None: ...
    def optimize_stack(self) -> None: ...
    def optimize_stack_pointers(self) -> None: ...
    def optimize_stack_slots(self) -> None: ...
    def optimize_calls(self) -> None: ...
    def optimize_call_clobbers(self) -> None: ...
    def optimize_memory_aliases(self) -> None: ...
    def optimize_branches(self) -> None: ...
    def optimize_memory_state(self) -> None: ...
    def optimize_constants(self) -> None: ...
    def optimize_dead_effects(self) -> None: ...
    def optimize_copy_propagation(self) -> None: ...
    def optimize_targets(self) -> None: ...
    def optimize_ssa(self) -> None: ...
    def optimize_ssa_liveness(self) -> None: ...
    def optimize_simplify(self) -> None: ...
    def text(self) -> str: ...
    def json(self) -> str: ...
    def to_dict(self) -> Any: ...


__all__: list[str]
