from __future__ import annotations

from typing import Any


class HirValue:
    @classmethod
    @classmethod
    def named(cls, name: str, ty: Any) -> HirValue: ...
    @classmethod
    def integer(cls, value: int, bits: int) -> HirValue: ...
    @classmethod
    def boolean(cls, value: bool) -> HirValue: ...
    @classmethod
    def null(cls, ty: Any) -> HirValue: ...
    @classmethod
    def undef(cls, ty: Any) -> HirValue: ...


class HirNamedValue(HirValue):
    def __init__(self, name: str, ty: Any) -> None: ...


class HirIntegerValue(HirValue):
    def __init__(self, value: int, bits: int) -> None: ...


class HirBooleanValue(HirValue):
    def __init__(self, value: bool) -> None: ...


class HirNullValue(HirValue):
    def __init__(self, ty: Any) -> None: ...


class HirUndefValue(HirValue):
    def __init__(self, ty: Any) -> None: ...


class HirExpression:
    @classmethod
    @classmethod
    def value(cls, value: HirValue) -> HirExpression: ...
    @classmethod
    def call(
        cls,
        target: HirTarget,
        arguments: list[HirExpression] | None = None,
        return_types: list[Any] | None = None,
    ) -> HirExpression: ...
    @classmethod
    def intrinsic(
        cls,
        name: str,
        arguments: list[HirExpression] | None = None,
        return_types: list[Any] | None = None,
    ) -> HirExpression: ...


class HirValueExpression(HirExpression):
    def __init__(self, value: Any) -> None: ...


class HirCallExpression(HirExpression):
    def __init__(
        self,
        target: Any,
        arguments: list[Any] | None = None,
        return_types: list[Any] | None = None,
    ) -> None: ...


class HirIntrinsicExpression(HirExpression):
    def __init__(
        self,
        name: str,
        arguments: list[Any] | None = None,
        return_types: list[Any] | None = None,
    ) -> None: ...


class HirPlace:
    @classmethod
    @classmethod
    def named(cls, name: str, ty: Any) -> HirPlace: ...


class HirNamedPlace(HirPlace):
    def __init__(self, name: str, ty: Any) -> None: ...


class HirTarget:
    @classmethod
    @classmethod
    def direct(cls, name: str) -> HirTarget: ...
    @classmethod
    def indirect(cls, expression: HirExpression) -> HirTarget: ...


class HirDirectTarget(HirTarget):
    def __init__(self, name: str) -> None: ...


class HirIndirectTarget(HirTarget):
    def __init__(self, expression: Any) -> None: ...


class HirStatement:
    @classmethod
    @classmethod
    def assign(cls, target: HirPlace, value: HirExpression) -> HirStatement: ...
    @classmethod
    def expr(cls, value: HirExpression) -> HirStatement: ...
    @classmethod
    def return_(cls, values: list[HirExpression] | None = None) -> HirStatement: ...
    @classmethod
    def label(cls, name: str) -> HirStatement: ...
    @classmethod
    def goto(cls, target: HirTarget) -> HirStatement: ...
    @classmethod
    def break_(cls) -> HirStatement: ...
    @classmethod
    def continue_(cls) -> HirStatement: ...
    @classmethod
    def trap(cls) -> HirStatement: ...
    @classmethod
    def unreachable(cls) -> HirStatement: ...


class HirAssignStatement(HirStatement):
    def __init__(self, target: Any, value: Any) -> None: ...


class HirExpressionStatement(HirStatement):
    def __init__(self, value: Any) -> None: ...


class HirReturnStatement(HirStatement):
    def __init__(self, values: list[Any] | None = None) -> None: ...


class HirLabelStatement(HirStatement):
    def __init__(self, name: str) -> None: ...


class HirGotoStatement(HirStatement):
    def __init__(self, target: Any) -> None: ...


class HirBreakStatement(HirStatement):
    def __init__(self) -> None: ...


class HirContinueStatement(HirStatement):
    def __init__(self) -> None: ...


class HirTrapStatement(HirStatement):
    def __init__(self) -> None: ...


class HirUnreachableStatement(HirStatement):
    def __init__(self) -> None: ...


class HirParameter:
    def __init__(self, name: str, ty: Any) -> None: ...
    @classmethod


class HirLocal:
    def __init__(self, name: str, ty: Any, init: HirExpression | None = None) -> None: ...
    @classmethod


class HirBlock:
    def __init__(self, statements: list[HirStatement] | None = None) -> None: ...
    @classmethod
    def statements(self) -> list[HirStatement]: ...
    def append_statement(self, statement: HirStatement) -> None: ...


class HirFunction:
    def __init__(self, name: str | None = None) -> None: ...
    @classmethod
    @classmethod
    def from_mir(cls, mir_function: Any, name: str | None = None) -> HirFunction: ...
    @classmethod
    def from_lir(cls, lir_function: Any, name: str | None = None) -> HirFunction: ...
    def append_parameter(self, parameter: HirParameter) -> None: ...
    def append_local(self, local: HirLocal) -> None: ...
    def append_block(self, block: HirBlock) -> None: ...
    def blocks(self) -> list[HirBlock]: ...
    def verify(self) -> None: ...
    def optimize_inline_temps(self) -> None: ...
    def optimize_algebraic(self) -> None: ...
    def optimize_condition_idioms(self) -> None: ...
    def optimize_boolean(self) -> None: ...
    def optimize_load_hoisting(self) -> None: ...
    def optimize_call_arguments(self) -> None: ...
    def optimize_memory_forms(self) -> None: ...
    def optimize_pointer_reads(self) -> None: ...
    def optimize_cfg(self) -> None: ...
    def optimize_locals(self) -> None: ...
    def optimize(self) -> None: ...
    def ast(self) -> Any: ...
    def c(self) -> str: ...
    def print_c(self) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...


class HirModule:
    def __init__(self, name: str | None = None) -> None: ...
    @classmethod
    @classmethod
    def from_mir(cls, mir_module: Any, name: str | None = None) -> HirModule: ...
    @classmethod
    def from_lir(cls, lir_module: Any, name: str | None = None) -> HirModule: ...
    @classmethod
    def from_text(cls, text: str) -> HirModule: ...
    @classmethod
    def from_bytecode(cls, bytecode: bytes) -> HirModule: ...
    def append_function(self, function: HirFunction) -> None: ...
    def functions(self) -> list[HirFunction]: ...
    def verify(self) -> None: ...
    def optimize_inline_temps(self) -> None: ...
    def optimize_algebraic(self) -> None: ...
    def optimize_condition_idioms(self) -> None: ...
    def optimize_boolean(self) -> None: ...
    def optimize_load_hoisting(self) -> None: ...
    def optimize_call_arguments(self) -> None: ...
    def optimize_memory_forms(self) -> None: ...
    def optimize_pointer_reads(self) -> None: ...
    def optimize_cfg(self) -> None: ...
    def optimize_locals(self) -> None: ...
    def optimize(self) -> None: ...
    def ast(self) -> Any: ...
    def c(self) -> str: ...
    def print_c(self) -> None: ...
    def text(self) -> str: ...
    def bytecode(self) -> bytes: ...
    def mlir(self) -> HirMlirModule: ...
    def operation_names(self) -> list[str]: ...
    def operation_count(self) -> int: ...
    def operation_records(self) -> list[dict[str, object]]: ...
    def print(self) -> None: ...


class HirMlirModule:
    def __init__(self, module: Any) -> None: ...
    @classmethod
    def from_text(cls, text: str) -> HirMlirModule: ...
    @classmethod
    def from_bytecode(cls, bytecode: bytes) -> HirMlirModule: ...
    def optimize_assignments(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def bytecode(self) -> bytes: ...
    def operation_names(self) -> list[str]: ...
    def operation_count(self) -> int: ...
    def operation_records(self) -> list[dict[str, object]]: ...
    def print(self) -> None: ...


__all__: list[str]
