from __future__ import annotations

from typing import Callable, Optional

from binlex.semantics import Semantic, SemanticCpu


class SliceInstruction:
    def architecture(self) -> str: ...
    def mnemonic(self) -> str: ...
    def disassembly(self) -> str: ...
    def address(self) -> int: ...
    def bytes(self) -> list[int]: ...


class SliceNode:
    def instruction(self) -> SliceInstruction | None: ...
    def location(self) -> str: ...
    def value(self) -> str: ...
    def parents(self) -> list["SliceNode"]: ...


class Slice:
    def nodes(self) -> list[SliceNode]: ...
    def number_of_nodes(self) -> int: ...
    def is_empty(self) -> bool: ...


class CpuState:
    def __init__(self, cpu: SemanticCpu) -> None: ...
    def symbolize_register(self, name: str, bits: int, symbol: Optional[str] = None) -> None: ...
    def set_register(self, name: str, bits: int, value: int) -> None: ...
    def symbolic_register(self, name: str, bits: int) -> Optional[str]: ...
    def evaluate_register(self, name: str, bits: int) -> Optional[int]: ...
    def program_counter(self) -> Optional[int]: ...
    def map_memory(self, address: int, size: int) -> None: ...
    def write_memory(self, address: int, data: bytes | bytearray | list[int]) -> None: ...
    def symbolize_memory(self, address: int, size: int, name: Optional[str] = None) -> None: ...
    def symbolic_memory(self, address: int, size: int) -> str: ...
    def evaluate_memory(self, address: int, size: int) -> Optional[int]: ...
    def read_memory(self, address: int, size: int) -> Optional[bytes]: ...
    def slice_from_register(self, name: str, bits: int) -> Slice: ...
    def slice_from_memory(self, address: int, size: int) -> Slice: ...
    def constraints(self) -> list[str]: ...
    def satisfiable(self) -> bool: ...
    def model(self) -> dict[str, str]: ...


class Executor:
    def __init__(self) -> None: ...
    def step(self, semantics: Semantic, state: CpuState) -> list[CpuState]: ...
    def run(
        self,
        semantics: list[Semantic],
        state: CpuState,
        steps: Optional[int] = None,
    ) -> list[CpuState]: ...
    def set_breakpoint(self, address: int) -> None: ...
    def remove_breakpoint(self, address: int) -> None: ...
    def clear_breakpoints(self) -> None: ...
    def breakpoints(self) -> list[int]: ...
    def add_hook(self, address: int, hook: Callable[[int, CpuState], list[CpuState]]) -> None: ...
    def remove_hook(self, address: int) -> None: ...
    def clear_hooks(self) -> None: ...
    def hooks(self) -> list[int]: ...
