from __future__ import annotations

from typing import Optional

from binlex import Architecture, Config
from binlex.genetics import Chromosome
from binlex.hashing import MinHash32, SHA256, TLSH
from binlex.imaging import Imaging
from binlex.lifters.llvm import Lifter as LlvmLifter
from binlex.lifters.vex import Lifter as VexLifter
from binlex.semantics import InstructionSemantics

class _Lifters:
    def llvm(self) -> LlvmLifter: ...
    def vex(self) -> VexLifter: ...

class Function:
    def __init__(self, address: int, cfg: Graph) -> None: ...
    def address(self) -> int: ...
    def architecture(self) -> Architecture: ...
    def chromosome(self) -> Chromosome | None: ...
    def cyclomatic_complexity(self) -> int: ...
    def average_instructions_per_block(self) -> float: ...
    def blocks(self) -> list[Block]: ...
    def bytes(self) -> bytes | None: ...
    def imaging(self) -> Imaging | None: ...
    def prologue(self) -> bool: ...
    def edges(self) -> int: ...
    def entropy(self) -> float | None: ...
    def number_of_instructions(self) -> int: ...
    def number_of_blocks(self) -> int: ...
    def functions(self) -> dict[int, int]: ...
    def processors(self) -> dict[str, object]: ...
    def processor(self, name: str) -> dict[str, object]: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def minhash(self) -> MinHash32 | None: ...
    def markov(self) -> dict[int, float]: ...
    def size(self) -> int: ...
    def contiguous(self) -> bool: ...
    def end(self) -> int | None: ...
    def print(self) -> None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def lifters(self) -> _Lifters: ...

class BlockJsonDeserializer:
    """Deserialize a serialized block JSON payload into typed accessors."""

    def __init__(self, string: str, config: Config) -> None: ...
    def functions(self) -> dict[int, int]: ...
    def architecture(self) -> Architecture: ...
    def bytes(self) -> bytes: ...
    def address(self) -> int: ...
    def minhash(self) -> MinHash32 | None: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def edges(self) -> int: ...
    def blocks(self) -> set[int]: ...
    def to(self) -> set[int]: ...
    def conditional(self) -> bool: ...
    def entropy(self) -> float | None: ...
    def next(self) -> int | None: ...
    def size(self) -> int: ...
    def number_of_instructions(self) -> int: ...
    def chromosome(self) -> Chromosome | None: ...
    def imaging(self) -> Imaging: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def print(self) -> None: ...

class Block:
    def __init__(self, address: int, cfg: Graph) -> None: ...
    def address(self) -> int: ...
    def architecture(self) -> Architecture: ...
    def chromosome(self) -> Chromosome | None: ...
    def instructions(self) -> list[Instruction]: ...
    def bytes(self) -> bytes: ...
    def imaging(self) -> Imaging: ...
    def prologue(self) -> bool: ...
    def edges(self) -> int: ...
    def next(self) -> int | None: ...
    def to(self) -> set[int]: ...
    def entropy(self) -> float | None: ...
    def blocks(self) -> set[int]: ...
    def number_of_instructions(self) -> int: ...
    def functions(self) -> dict[int, int]: ...
    def processors(self) -> dict[str, object]: ...
    def processor(self, name: str) -> dict[str, object]: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def minhash(self) -> MinHash32 | None: ...
    def end(self) -> int: ...
    def size(self) -> int: ...
    def print(self) -> None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def lifters(self) -> _Lifters: ...

class Instruction:
    def __init__(self, address: int, cfg: Graph) -> None: ...
    @property
    def address(self) -> int: ...
    def chromosome(self) -> Chromosome | None: ...
    def blocks(self) -> set[int]: ...
    def next(self) -> int | None: ...
    def to(self) -> set[int]: ...
    def has_indirect_target(self) -> bool: ...
    def functions(self) -> set[int]: ...
    def size(self) -> int: ...
    def imaging(self) -> Imaging: ...
    def processors(self) -> dict[str, object]: ...
    def processor(self, name: str) -> dict[str, object]: ...
    def semantics(self) -> InstructionSemantics | None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def print(self) -> None: ...
    def lifters(self) -> _Lifters: ...

class InstructionJsonDeserializer:
    def __init__(self, string: str, config: Config) -> None: ...
    def architecture(self) -> Architecture: ...
    def address(self) -> int: ...
    def bytes(self) -> bytes: ...
    def size(self) -> int: ...
    def blocks(self) -> set[int]: ...
    def next(self) -> int | None: ...
    def to(self) -> set[int]: ...
    def has_indirect_target(self) -> bool: ...
    def functions(self) -> set[int]: ...
    def chromosome(self) -> Chromosome: ...
    def imaging(self) -> Imaging: ...
    def processors(self) -> dict[str, object] | None: ...
    def processor(self, name: str) -> object: ...
    def semantics(self) -> InstructionSemantics | None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def print(self) -> None: ...

class FunctionJsonDeserializer:
    """Deserialize a serialized function JSON payload into typed accessors."""

    def __init__(self, string: str, config: Config) -> None: ...
    def blocks(self) -> list[int]: ...
    def functions(self) -> dict[int, int]: ...
    def size(self) -> int: ...
    def contiguous(self) -> bool: ...
    def architecture(self) -> Architecture: ...
    def bytes(self) -> bytes | None: ...
    def address(self) -> int: ...
    def number_of_instructions(self) -> int: ...
    def number_of_blocks(self) -> int: ...
    def average_instructions_per_block(self) -> float: ...
    def entropy(self) -> float | None: ...
    def edges(self) -> int: ...
    def sha256(self) -> str | None: ...
    def minhash(self) -> str | None: ...
    def tlsh(self) -> str | None: ...
    def markov(self) -> dict[int, float] | None: ...
    def chromosome(self) -> Chromosome | None: ...
    def imaging(self) -> Imaging | None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def print(self) -> None: ...

class GraphQueue:
    """Track discovery and processing state for instructions, blocks, or functions."""

    def insert_invalid(self, address: int) -> None: ...
    def is_invalid(self, address: int) -> bool: ...
    def valid_addresses(self) -> set[int]: ...
    def invalid_addresses(self) -> set[int]: ...
    def processed_addresses(self) -> set[int]: ...
    def is_valid(self, address: int) -> bool: ...
    def insert_valid(self, address: int) -> None: ...
    def insert_processed_extend(self, addresses: set[int]) -> None: ...
    def insert_processed(self, address: int) -> None: ...
    def is_processed(self, address: int) -> bool: ...
    def enqueue_extend(self, addresses: set[int]) -> None: ...
    def enqueue(self, address: int) -> bool: ...
    def dequeue(self) -> Optional[int]: ...
    def dequeue_all(self) -> set[int]: ...

class Graph:
    def __init__(self, architecture: Architecture, config: Config) -> None: ...
    def instructions(self) -> list[Instruction]: ...
    def blocks(self) -> list[Block]: ...
    def functions(self) -> list[Function]: ...
    def mutations(self) -> int: ...
    @property
    def queue_instructions(self) -> GraphQueue: ...
    @property
    def queue_blocks(self) -> GraphQueue: ...
    @property
    def queue_functions(self) -> GraphQueue: ...
    def set_block(self, address: int) -> bool: ...
    def set_function(self, address: int) -> bool: ...
    def extend_instruction_edges(self, address: int, addresses: set[int]) -> bool: ...
    def get_instruction(self, address: int) -> Instruction | None: ...

__all__: list[str]
