from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Optional

from binlex import Architecture, Configuration
from binlex.embeddings import EmbeddingBackend
from binlex.formats import Image, Symbol
from binlex.genetics import Chromosome
from binlex.hashing import MinHash32, SHA256, SSDeep, TLSH
from binlex.irs import llvm, vex
from binlex.irs.lir import LirBlock, LirFunction, LirInstruction

class Reference:
    def __init__(self, location: int, address: int) -> None: ...
    def location(self) -> int: ...
    def address(self) -> int: ...

class EntityKind:
    Instruction: EntityKind
    Block: EntityKind
    Function: EntityKind

class FunctionCallee:
    def address(self) -> int: ...
    def function(self) -> Function: ...

class FunctionCaller:
    def address(self) -> int: ...
    def function(self) -> Function: ...

class Function:
    def __init__(self, address: int, cfg: Graph) -> None: ...
    def address(self) -> int: ...
    def kind(self) -> EntityKind: ...
    def architecture(self) -> Architecture: ...
    def chromosome(self) -> Chromosome | None: ...
    def cyclomatic_complexity(self) -> int: ...
    def average_instructions_per_block(self) -> float: ...
    def blocks(self) -> list[Block]: ...
    def bytes(self) -> bytes | None: ...
    def prologue(self) -> bool: ...
    def edges(self) -> int: ...
    def entropy(self) -> float | None: ...
    def number_of_instructions(self) -> int: ...
    def number_of_blocks(self) -> int: ...
    def callees(self) -> list[FunctionCallee]: ...
    def callers(self) -> list[FunctionCaller]: ...
    def embedding(
        self,
        backend: EmbeddingBackend | None = None,
        dimensions: int | None = None,
    ) -> list[float] | None: ...
    def llvm(self) -> llvm.LlvmModule: ...
    def vex(self) -> vex.VexModule: ...
    def lir(self) -> LirFunction: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def ssdeep(self) -> SSDeep | None: ...
    def minhash(self) -> MinHash32 | None: ...
    def markov(self) -> dict[int, float]: ...
    def size(self) -> int: ...
    def contiguous(self) -> bool: ...
    def end(self) -> int | None: ...

class Block:
    def __init__(self, address: int, cfg: Graph) -> None: ...
    def address(self) -> int: ...
    def kind(self) -> EntityKind: ...
    def architecture(self) -> Architecture: ...
    def chromosome(self) -> Chromosome: ...
    def instructions(self) -> list[Instruction]: ...
    def bytes(self) -> bytes: ...
    def prologue(self) -> bool: ...
    def edges(self) -> int: ...
    def fallthrough(self) -> int | None: ...
    def branches(self) -> set[int]: ...
    def is_conditional(self) -> bool: ...
    def entropy(self) -> float: ...
    def successors(self) -> list[Block]: ...
    def predecessors(self) -> list[Block]: ...
    def successor_references(self) -> list[Reference]: ...
    def predecessor_references(self) -> list[Reference]: ...
    def callees(self) -> list[Function]: ...
    def callee_references(self) -> list[Reference]: ...
    def number_of_instructions(self) -> int: ...
    def embedding(
        self,
        backend: EmbeddingBackend | None = None,
        dimensions: int | None = None,
    ) -> list[float] | None: ...
    def llvm(self) -> llvm.LlvmModule: ...
    def vex(self) -> vex.VexModule: ...
    def lir(self) -> LirBlock: ...
    def tlsh(self) -> TLSH: ...
    def sha256(self) -> SHA256: ...
    def ssdeep(self) -> SSDeep: ...
    def minhash(self) -> MinHash32 | None: ...
    def end(self) -> int: ...
    def size(self) -> int: ...

class Instruction:
    def __init__(self, address: int, cfg: Graph) -> None: ...
    def address(self) -> int: ...
    def kind(self) -> EntityKind: ...
    def bytes(self) -> bytes: ...
    def mnemonic(self) -> str: ...
    def disassembly(self) -> str: ...
    def operands(self) -> list[Operand]: ...
    def chromosome(self) -> Chromosome: ...
    def successor_blocks(self) -> list[Block]: ...
    def successor_block_references(self) -> list[Reference]: ...
    def fallthrough(self) -> int | None: ...
    def branches(self) -> set[int]: ...
    def successors(self) -> set[int]: ...
    def has_indirect_target(self) -> bool: ...
    def is_conditional(self) -> bool: ...
    def callees(self) -> list[Function]: ...
    def callee_references(self) -> list[Reference]: ...
    def size(self) -> int: ...
    def embedding(
        self,
        backend: EmbeddingBackend | None = None,
        dimensions: int | None = None,
    ) -> list[float] | None: ...
    def llvm(self) -> llvm.LlvmModule: ...
    def vex(self) -> vex.VexModule: ...
    def lir(self) -> LirInstruction: ...
    def set_lir(self, lir: LirInstruction) -> Instruction: ...

class OperandKind:
    Register: OperandKind
    Immediate: OperandKind
    Memory: OperandKind
    Float: OperandKind
    Special: OperandKind

class Operand:
    @classmethod
    def kind(self) -> OperandKind: ...
    def is_register(self) -> bool: ...
    def is_immediate(self) -> bool: ...
    def is_memory(self) -> bool: ...
    def is_float(self) -> bool: ...
    def is_special(self) -> bool: ...
    def name(self) -> str | None: ...
    def value(self) -> int | float | None: ...
    def base(self) -> str | None: ...
    def index(self) -> str | None: ...
    def scale(self) -> int | None: ...
    def displacement(self) -> int | None: ...
    def segment(self) -> str | None: ...
    def space(self) -> str | None: ...
    def special_kind(self) -> str | None: ...
    def fields(self) -> dict[str, object] | None: ...

class GraphQueue:
    """Track discovery and processing state for instructions, blocks, or functions."""

    def insert_invalid(self, address: int) -> None: ...
    def is_invalid(self, address: int) -> bool: ...
    def valid_addresses(self) -> set[int]: ...
    def invalid_addresses(self) -> set[int]: ...
    def processed_addresses(self) -> set[int]: ...
    def is_valid(self, address: int) -> bool: ...
    def insert_valid(self, address: int) -> None: ...
    def insert_processed_extend(self, addresses: set[int]) -> None: ...
    def insert_processed(self, address: int) -> None: ...
    def is_processed(self, address: int) -> bool: ...
    def enqueue_extend(self, addresses: set[int]) -> None: ...
    def enqueue(self, address: int) -> bool: ...
    def dequeue(self) -> Optional[int]: ...
    def dequeue_all(self) -> set[int]: ...

class GraphState:
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class Graph:
    def __init__(
        self,
        architecture: Architecture,
        image: Image,
        config: Configuration,
        metadata: Mapping[str, object] | Sequence[Symbol | Mapping[str, object]] | None = None,
    ) -> None: ...
    @classmethod
    def from_state(cls, state: object) -> Graph: ...
    def state(self) -> GraphState: ...
    def __getstate__(self) -> GraphState: ...
    def __setstate__(self, state: GraphState) -> None: ...
    def architecture(self) -> Architecture: ...
    def image(self) -> Image: ...
    def configuration(self) -> Configuration: ...
    def executable_virtual_address_ranges(self) -> dict[int, int]: ...
    def instructions(self) -> list[Instruction]: ...
    def blocks(self) -> list[Block]: ...
    def functions(self) -> list[Function]: ...
    def instruction(self, address: int) -> Instruction | None: ...
    def block(self, address: int) -> Block | None: ...
    def function(self, address: int) -> Function | None: ...
    def mutations(self) -> int: ...
    @property
    def queue_instructions(self) -> GraphQueue: ...
    @property
    def queue_blocks(self) -> GraphQueue: ...
    @property
    def queue_functions(self) -> GraphQueue: ...
    def set_block(self, address: int) -> bool: ...
    def set_function(self, address: int) -> bool: ...
    def extend_instruction_edges(self, address: int, addresses: set[int]) -> bool: ...
    def metadata(self) -> dict[str, object]: ...
    def metadata_value(self, key: str): ...
    def replace_metadata(self, metadata) -> None: ...
    def extend_metadata(self, metadata) -> None: ...
    def symbols(self) -> dict[int, str]: ...
    def symbol(self, address: int) -> str | None: ...
    def insert_symbol(self, address: int, name: str) -> str | None: ...
    def replace_symbols(self, symbols) -> None: ...
    def extend_symbols(self, symbols) -> None: ...

__all__: list[str]
