from __future__ import annotations

from typing import Optional

from binlex import Architecture, Configuration
from binlex.embeddings import EmbeddingBackend
from binlex.genetics import Chromosome
from binlex.hashing import MinHash32, SHA256, SSDeep, TLSH
from binlex.lifters import Lifter, LifterBackend
from binlex.semantics import Semantic

class Reference:
    def __init__(self, location: int, address: int) -> None: ...
    def location(self) -> int: ...
    def address(self) -> int: ...
    def to_dict(self) -> dict[str, int]: ...

class Function:
    def __init__(self, address: int, cfg: Graph) -> None: ...
    def address(self) -> int: ...
    def architecture(self) -> Architecture: ...
    def chromosome(self) -> Chromosome | None: ...
    def cyclomatic_complexity(self) -> int: ...
    def average_instructions_per_block(self) -> float: ...
    def blocks(self) -> list[Block]: ...
    def bytes(self) -> bytes | None: ...
    def prologue(self) -> bool: ...
    def edges(self) -> int: ...
    def entropy(self) -> float | None: ...
    def number_of_instructions(self) -> int: ...
    def number_of_blocks(self) -> int: ...
    def callees(self) -> list[Function]: ...
    def callers(self) -> list[Function]: ...
    def callee_references(self) -> dict[int, int]: ...
    def caller_references(self) -> dict[int, int]: ...
    def processors(self) -> dict[str, object]: ...
    def processor(self, name: str) -> dict[str, object]: ...
    def embedding(
        self,
        backend: EmbeddingBackend | None = None,
        dimensions: int | None = None,
    ) -> list[float] | None: ...
    def lift(self, backend: LifterBackend | None = None) -> Lifter | None: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def ssdeep(self) -> SSDeep | None: ...
    def minhash(self) -> MinHash32 | None: ...
    def markov(self) -> dict[int, float]: ...
    def size(self) -> int: ...
    def contiguous(self) -> bool: ...
    def end(self) -> int | None: ...
    def print(self) -> None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...

class BlockJsonDeserializer:
    """Deserialize a serialized block JSON payload into typed accessors."""

    def __init__(self, string: str, config: Configuration) -> None: ...
    def callee_references(self) -> list[Reference]: ...
    def architecture(self) -> Architecture: ...
    def bytes(self) -> bytes: ...
    def address(self) -> int: ...
    def minhash(self) -> MinHash32 | None: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def ssdeep(self) -> str | None: ...
    def edges(self) -> int: ...
    def successor_references(self) -> list[Reference]: ...
    def predecessor_references(self) -> list[Reference]: ...
    def branches(self) -> set[int]: ...
    def conditional(self) -> bool: ...
    def entropy(self) -> float | None: ...
    def fallthrough(self) -> int | None: ...
    def size(self) -> int: ...
    def number_of_instructions(self) -> int: ...
    def chromosome(self) -> Chromosome | None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def print(self) -> None: ...

class Block:
    def __init__(self, address: int, cfg: Graph) -> None: ...
    def address(self) -> int: ...
    def architecture(self) -> Architecture: ...
    def chromosome(self) -> Chromosome: ...
    def instructions(self) -> list[Instruction]: ...
    def bytes(self) -> bytes: ...
    def prologue(self) -> bool: ...
    def edges(self) -> int: ...
    def fallthrough(self) -> int | None: ...
    def branches(self) -> set[int]: ...
    def entropy(self) -> float: ...
    def successors(self) -> list[Block]: ...
    def predecessors(self) -> list[Block]: ...
    def successor_references(self) -> list[Reference]: ...
    def predecessor_references(self) -> list[Reference]: ...
    def callees(self) -> list[Function]: ...
    def callee_references(self) -> list[Reference]: ...
    def number_of_instructions(self) -> int: ...
    def processors(self) -> dict[str, object]: ...
    def processor(self, name: str) -> dict[str, object]: ...
    def embedding(
        self,
        backend: EmbeddingBackend | None = None,
        dimensions: int | None = None,
    ) -> list[float] | None: ...
    def lift(self, backend: LifterBackend | None = None) -> Lifter | None: ...
    def tlsh(self) -> TLSH: ...
    def sha256(self) -> SHA256: ...
    def ssdeep(self) -> SSDeep: ...
    def minhash(self) -> MinHash32 | None: ...
    def end(self) -> int: ...
    def size(self) -> int: ...
    def print(self) -> None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...

class Instruction:
    def __init__(self, address: int, cfg: Graph) -> None: ...
    def address(self) -> int: ...
    def bytes(self) -> bytes: ...
    def mnemonic(self) -> str: ...
    def disassembly(self) -> str: ...
    def operands(self) -> list[Operand]: ...
    def chromosome(self) -> Chromosome: ...
    def successor_blocks(self) -> list[Block]: ...
    def successor_block_references(self) -> list[Reference]: ...
    def fallthrough(self) -> int | None: ...
    def branches(self) -> set[int]: ...
    def successors(self) -> set[int]: ...
    def has_indirect_target(self) -> bool: ...
    def is_conditional(self) -> bool: ...
    def callees(self) -> list[Function]: ...
    def callee_references(self) -> list[Reference]: ...
    def size(self) -> int: ...
    def processors(self) -> dict[str, object]: ...
    def processor(self, name: str) -> dict[str, object]: ...
    def embedding(
        self,
        backend: EmbeddingBackend | None = None,
        dimensions: int | None = None,
    ) -> list[float] | None: ...
    def lift(self, backend: LifterBackend | None = None) -> Lifter | None: ...
    def semantic(self) -> Semantic | None: ...
    def set_semantics(self, semantics: Semantic) -> Instruction: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def print(self) -> None: ...

class InstructionJsonDeserializer:
    def __init__(self, string: str, config: Configuration) -> None: ...
    def architecture(self) -> Architecture: ...
    def address(self) -> int: ...
    def mnemonic(self) -> str: ...
    def disassembly(self) -> str: ...
    def operands(self) -> list[Operand]: ...
    def bytes(self) -> bytes: ...
    def size(self) -> int: ...
    def successor_block_references(self) -> list[Reference]: ...
    def fallthrough(self) -> int | None: ...
    def branches(self) -> set[int]: ...
    def successors(self) -> set[int]: ...
    def has_indirect_target(self) -> bool: ...
    def is_conditional(self) -> bool: ...
    def callees(self) -> set[int]: ...
    def callee_references(self) -> list[Reference]: ...
    def chromosome(self) -> Chromosome: ...
    def processors(self) -> dict[str, object] | None: ...
    def processor(self, name: str) -> object: ...
    def semantic(self) -> Semantic | None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def print(self) -> None: ...

class OperandKind:
    Register: OperandKind
    Immediate: OperandKind
    Memory: OperandKind
    Float: OperandKind
    Special: OperandKind

class Operand:
    @classmethod
    def from_dict(cls, data: dict[str, object]) -> Operand: ...
    def kind(self) -> OperandKind: ...
    def is_register(self) -> bool: ...
    def is_immediate(self) -> bool: ...
    def is_memory(self) -> bool: ...
    def is_float(self) -> bool: ...
    def is_special(self) -> bool: ...
    def name(self) -> str | None: ...
    def value(self) -> int | float | None: ...
    def base(self) -> str | None: ...
    def index(self) -> str | None: ...
    def scale(self) -> int | None: ...
    def displacement(self) -> int | None: ...
    def segment(self) -> str | None: ...
    def space(self) -> str | None: ...
    def special_kind(self) -> str | None: ...
    def fields(self) -> dict[str, object] | None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def print(self) -> None: ...

class FunctionJsonDeserializer:
    """Deserialize a serialized function JSON payload into typed accessors."""

    def __init__(self, string: str, config: Configuration) -> None: ...
    def blocks(self) -> list[int]: ...
    def callee_references(self) -> dict[int, int]: ...
    def caller_references(self) -> dict[int, int]: ...
    def size(self) -> int: ...
    def contiguous(self) -> bool: ...
    def architecture(self) -> Architecture: ...
    def bytes(self) -> bytes | None: ...
    def address(self) -> int: ...
    def number_of_instructions(self) -> int: ...
    def number_of_blocks(self) -> int: ...
    def average_instructions_per_block(self) -> float: ...
    def entropy(self) -> float | None: ...
    def edges(self) -> int: ...
    def sha256(self) -> str | None: ...
    def minhash(self) -> str | None: ...
    def tlsh(self) -> str | None: ...
    def ssdeep(self) -> str | None: ...
    def markov(self) -> dict[int, float] | None: ...
    def chromosome(self) -> Chromosome | None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...
    def print(self) -> None: ...

class GraphQueue:
    """Track discovery and processing state for instructions, blocks, or functions."""

    def insert_invalid(self, address: int) -> None: ...
    def is_invalid(self, address: int) -> bool: ...
    def valid_addresses(self) -> set[int]: ...
    def invalid_addresses(self) -> set[int]: ...
    def processed_addresses(self) -> set[int]: ...
    def is_valid(self, address: int) -> bool: ...
    def insert_valid(self, address: int) -> None: ...
    def insert_processed_extend(self, addresses: set[int]) -> None: ...
    def insert_processed(self, address: int) -> None: ...
    def is_processed(self, address: int) -> bool: ...
    def enqueue_extend(self, addresses: set[int]) -> None: ...
    def enqueue(self, address: int) -> bool: ...
    def dequeue(self) -> Optional[int]: ...
    def dequeue_all(self) -> set[int]: ...

class Graph:
    def __init__(self, architecture: Architecture, config: Configuration) -> None: ...
    def instructions(self) -> list[Instruction]: ...
    def blocks(self) -> list[Block]: ...
    def functions(self) -> list[Function]: ...
    def mutations(self) -> int: ...
    @property
    def queue_instructions(self) -> GraphQueue: ...
    @property
    def queue_blocks(self) -> GraphQueue: ...
    @property
    def queue_functions(self) -> GraphQueue: ...
    def set_block(self, address: int) -> bool: ...
    def set_function(self, address: int) -> bool: ...
    def extend_instruction_edges(self, address: int, addresses: set[int]) -> bool: ...
    def get_instruction(self, address: int) -> Instruction | None: ...
    def get_block(self, address: int) -> Block | None: ...
    def get_function(self, address: int) -> Function | None: ...

__all__: list[str]
