from __future__ import annotations

from collections.abc import Mapping, Set
from typing import Optional

from binlex import Architecture, Config, Magic
from binlex.types import MemoryMappedFile

class File:
    def __init__(self, path: str, config: Config) -> None: ...
    def magic(self) -> Magic: ...
    def tlsh(self) -> Optional[str]: ...
    def sha256(self) -> Optional[str]: ...
    def size(self) -> int: ...
    def read(self) -> None: ...
    def json(self) -> str: ...
class ELF:
    def image(self) -> MemoryMappedFile: ...
    def file(self) -> File: ...

class MACHO:
    def image(self, slice: int) -> MemoryMappedFile: ...
    def file(self) -> File: ...

class PE:
    def __init__(self, path: str, config: Config) -> None: ...
    @classmethod
    def from_bytes(cls, bytes: bytes, config: Config) -> PE: ...
    def is_dotnet(self) -> bool: ...
    def virtual_address_to_relative_virtual_address(self, virtual_address: int) -> int: ...
    def virtual_address_to_file_offset(self, virtual_address: int) -> int | None: ...
    def relative_virtual_address_to_virtual_address(self, relative_virtual_address: int) -> int: ...
    def file_offset_to_virtual_address(self, file_offset: int) -> int | None: ...
    def architecture(self) -> Architecture: ...
    def dotnet_metadata_token_virtual_addresses(self) -> dict[int, int]: ...
    def dotnet_executable_virtual_address_ranges(self) -> dict[int, int]: ...
    def executable_virtual_address_ranges(self) -> dict[int, int]: ...
    def pogo_virtual_addresses(self) -> dict[int, str]: ...
    def tlscallbacks(self) -> set[int]: ...
    def dotnet_entrypoint_virtual_addresses(self) -> set[int]: ...
    def entrypoint_virtual_addresses(self) -> set[int]: ...
    def entrypoint_virtual_address(self) -> int: ...
    def sizeofheaders(self) -> int: ...
    def image(self) -> MemoryMappedFile: ...
    def size(self) -> int: ...
    @staticmethod
    def align_section_virtual_address(value: int, section_alignment: int, file_alignment: int) -> int: ...
    def export_virtual_addresses(self) -> set[int]: ...
    def tlsh(self) -> Optional[str]: ...
    def sha256(self) -> Optional[str]: ...
    def entropy(self) -> Optional[float]: ...
    def file(self) -> File: ...
    def imagebase(self) -> int: ...
    def section_alignment(self) -> int: ...
    def file_alignment(self) -> int: ...

__all__: list[str]
