all:
	cp blserver.toml.bak blserver.toml
	cp milvus.yaml.bak milvus.yaml
	cp nginx.conf.bak nginx.conf
	cp nginx.key.bak nginx.key
	cp nginx.crt.bak nginx.crt

clean:
	rm -f blserver.toml
	rm -f milvus.yaml
	rm -f nginx.conf
	rm -f nginx.crt
	rm -f nginx.key
