all:
	cp blserver.toml.bak blserver.toml
	cp milvus.yaml.bak milvus.yaml
	cp blserver-proxy.conf.bak blserver-proxy.conf
	cp blserver-proxy.key.bak blserver-proxy.key
	cp blserver-proxy.crt.bak blserver-proxy.crt
	cp attu-proxy.conf.bak attu-proxy.conf
	cp attu-proxy.key.bak attu-proxy.key
	cp attu-proxy.crt.bak attu-proxy.crt
	cp minio-proxy.conf.bak minio-proxy.conf
	cp minio-proxy.key.bak minio-proxy.key
	cp minio-proxy.crt.bak minio-proxy.crt

clean:
	rm -f blserver.toml
	rm -f milvus.yaml
	rm -f blserver-proxy.conf
	rm -f blserver-proxy.crt
	rm -f blserver-proxy.key
	rm -f attu-proxy.conf
	rm -f attu-proxy.crt
	rm -f attu-proxy.key
	rm -f minio-proxy.conf
	rm -f minio-proxy.crt
	rm -f minio-proxy.key
