from __future__ import annotations

from binlex import Config
from binlex.hashing import MinHash32, SHA256, TLSH
from binlex.imaging import PNG, SVG


class Gene:
    @staticmethod
    def from_char(c: str) -> Gene: ...
    @staticmethod
    def from_value(v: int) -> Gene: ...
    @staticmethod
    def from_wildcard() -> Gene: ...
    def mutate(self, c: str) -> None: ...
    def wildcard(self) -> str | None: ...
    def mutations(self) -> int: ...
    def is_wildcard(self) -> bool: ...
    def is_value(self) -> bool: ...
    def to_char(self) -> str: ...
    def print(self) -> None: ...


class AllelePair:
    def __init__(self, low: Gene, high: Gene) -> None: ...
    def mutations(self) -> int: ...
    def mutate(self, low: Gene, high: Gene) -> None: ...
    def genes(self) -> list[Gene]: ...
    @staticmethod
    def from_string(pair: str) -> AllelePair: ...
    def low(self) -> Gene: ...
    def high(self) -> Gene: ...
    def print(self) -> None: ...


class Chromosome:
    def __init__(self, pattern: str, config: Config) -> None: ...
    def allelepairs(self) -> list[AllelePair]: ...
    def mutations(self) -> int: ...
    def mutate(self, pattern: str) -> None: ...
    def pattern(self) -> str: ...
    def vector(self) -> list[int]: ...
    def tlsh(self) -> TLSH | None: ...
    def minhash(self) -> MinHash32 | None: ...
    def sha256(self) -> SHA256 | None: ...
    def entropy(self) -> float | None: ...
    def bytes(self) -> bytes: ...
    def png(self) -> PNG: ...
    def svg(self) -> SVG: ...
    def print(self) -> None: ...
    def to_dict(self) -> dict[str, object]: ...
    def json(self) -> str: ...


__all__ = ["AllelePair", "Chromosome", "Gene"]
