from __future__ import annotations

from typing import Any


class HirValue:
    @classmethod
    def from_dict(cls, data: Any) -> HirValue: ...
    def to_dict(self) -> Any: ...
    def json(self) -> str: ...


class HirExpression:
    @classmethod
    def from_dict(cls, data: Any) -> HirExpression: ...
    def to_dict(self) -> Any: ...
    def json(self) -> str: ...


class HirStatement:
    @classmethod
    def from_dict(cls, data: Any) -> HirStatement: ...
    def to_dict(self) -> Any: ...
    def json(self) -> str: ...


class HirBlock:
    @classmethod
    def from_dict(cls, data: Any) -> HirBlock: ...
    def statements(self) -> list[HirStatement]: ...
    def to_dict(self) -> Any: ...
    def json(self) -> str: ...


class HirFunction:
    def __init__(self, name: str | None = None) -> None: ...
    @classmethod
    def from_dict(cls, data: Any) -> HirFunction: ...
    @classmethod
    def from_mir(cls, mir_function: Any, name: str | None = None) -> HirFunction: ...
    @classmethod
    def from_lir(cls, lir_function: Any, name: str | None = None) -> HirFunction: ...
    def append_block(self, block: HirBlock) -> None: ...
    def blocks(self) -> list[HirBlock]: ...
    def verify(self) -> None: ...
    def optimize_inline_temps(self) -> None: ...
    def optimize_algebraic(self) -> None: ...
    def optimize_condition_idioms(self) -> None: ...
    def optimize_boolean(self) -> None: ...
    def optimize_load_hoisting(self) -> None: ...
    def optimize_call_arguments(self) -> None: ...
    def optimize_memory_forms(self) -> None: ...
    def optimize_pointer_reads(self) -> None: ...
    def optimize_cfg(self) -> None: ...
    def optimize_locals(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def to_dict(self) -> Any: ...
    def json(self) -> str: ...


class HirModule:
    def __init__(self, name: str | None = None) -> None: ...
    @classmethod
    def from_dict(cls, data: Any) -> HirModule: ...
    @classmethod
    def from_mir(cls, mir_module: Any, name: str | None = None) -> HirModule: ...
    @classmethod
    def from_lir(cls, lir_module: Any, name: str | None = None) -> HirModule: ...
    def append_function(self, function: HirFunction) -> None: ...
    def functions(self) -> list[HirFunction]: ...
    def verify(self) -> None: ...
    def optimize_inline_temps(self) -> None: ...
    def optimize_algebraic(self) -> None: ...
    def optimize_condition_idioms(self) -> None: ...
    def optimize_boolean(self) -> None: ...
    def optimize_load_hoisting(self) -> None: ...
    def optimize_call_arguments(self) -> None: ...
    def optimize_memory_forms(self) -> None: ...
    def optimize_pointer_reads(self) -> None: ...
    def optimize_cfg(self) -> None: ...
    def optimize_locals(self) -> None: ...
    def optimize(self) -> None: ...
    def text(self) -> str: ...
    def print(self) -> None: ...
    def to_dict(self) -> Any: ...
    def json(self) -> str: ...


__all__: list[str]
