from __future__ import annotations

from collections.abc import Mapping, Set
from typing import Optional

from binlex import Architecture, Config, Magic
from binlex.hashing import SHA256, TLSH

class Image:
    """Writable binary image helper backed by the native image implementation."""

    def __init__(self, path: str, cache: bool) -> None: ...
    @classmethod
    def from_binding(cls, binding: object) -> Image: ...
    def is_cached(self) -> bool: ...
    def path(self) -> str: ...
    def write(self, data: bytes) -> int: ...
    def write_padding(self, length: int) -> None: ...
    def seek_to_end(self) -> int: ...
    def seek(self, offset: int) -> int: ...
    def size(self) -> int: ...
    def mmap(self) -> memoryview: ...
    def mmap_mut(self) -> memoryview: ...

class File:
    """High-level wrapper around a file binding with typed helpers."""

    def __init__(self, path: str, config: Config) -> None: ...
    @classmethod
    def from_binding(cls, binding: object) -> File: ...
    def magic(self) -> Magic: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def size(self) -> int: ...
    def read(self) -> None: ...
    def json(self) -> str: ...

class ELF:
    """Executable and Linkable Format wrapper with address translation helpers."""

    def __init__(self, path: str, config: Config) -> None: ...
    @classmethod
    def from_bytes(cls, bytes: bytes, config: Config) -> ELF: ...
    def architecture(self) -> Architecture: ...
    def executable_virtual_address_ranges(self) -> dict[int, int]: ...
    def relative_virtual_address_to_virtual_address(self, relative_virtual_address: int) -> int: ...
    def file_offset_to_virtual_address(self, file_offset: int) -> int | None: ...
    def entrypoint_virtual_addresses(self) -> set[int]: ...
    def entrypoint_virtual_address(self) -> int: ...
    def image(self) -> Image: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def size(self) -> int: ...
    def export_virtual_addresses(self) -> set[int]: ...
    def entropy(self) -> float | None: ...
    def file(self) -> File: ...

class MACHO:
    """Mach-O wrapper for single-arch and fat binaries with slice-aware helpers."""

    def __init__(self, path: str, config: Config) -> None: ...
    @classmethod
    def from_bytes(cls, bytes: bytes, config: Config) -> MACHO: ...
    def relative_virtual_address_to_virtual_address(self, relative_virtual_address: int, slice: int) -> int | None: ...
    def file_offset_to_virtual_address(self, file_offset: int, slice: int) -> int | None: ...
    def number_of_slices(self) -> int: ...
    def entrypoint_virtual_address(self, slice: int) -> int | None: ...
    def imagebase(self, slice: int) -> int | None: ...
    def sizeofheaders(self, slice: int) -> int | None: ...
    def architecture(self, slice: int) -> Architecture | None: ...
    def entrypoint_virtual_addresses(self, slice: int) -> set[int]: ...
    def export_virtual_addresses(self, slice: int) -> set[int]: ...
    def executable_virtual_address_ranges(self, slice: int) -> dict[int, int]: ...
    def image(self, slice: int) -> Image: ...
    def size(self) -> int: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def entropy(self) -> float | None: ...
    def file(self) -> File: ...

class PE:
    """Portable Executable wrapper with address translation helpers."""

    def __init__(self, path: str, config: Config) -> None: ...
    @classmethod
    def from_bytes(cls, bytes: bytes, config: Config) -> PE: ...
    def is_dotnet(self) -> bool: ...
    def virtual_address_to_relative_virtual_address(self, virtual_address: int) -> int: ...
    def virtual_address_to_file_offset(self, virtual_address: int) -> int | None: ...
    def relative_virtual_address_to_virtual_address(self, relative_virtual_address: int) -> int: ...
    def file_offset_to_virtual_address(self, file_offset: int) -> int | None: ...
    def architecture(self) -> Architecture: ...
    def dotnet_metadata_token_virtual_addresses(self) -> dict[int, int]: ...
    def dotnet_executable_virtual_address_ranges(self) -> dict[int, int]: ...
    def executable_virtual_address_ranges(self) -> dict[int, int]: ...
    def pogo_virtual_addresses(self) -> dict[int, str]: ...
    def tlscallbacks(self) -> set[int]: ...
    def dotnet_entrypoint_virtual_addresses(self) -> set[int]: ...
    def entrypoint_virtual_addresses(self) -> set[int]: ...
    def entrypoint_virtual_address(self) -> int: ...
    def sizeofheaders(self) -> int: ...
    def image(self) -> Image: ...
    def size(self) -> int: ...
    @staticmethod
    def align_section_virtual_address(value: int, section_alignment: int, file_alignment: int) -> int: ...
    def export_virtual_addresses(self) -> set[int]: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def entropy(self) -> Optional[float]: ...
    def file(self) -> File: ...
    def imagebase(self) -> int: ...
    def section_alignment(self) -> int: ...
    def file_alignment(self) -> int: ...

__all__: list[str]
