from __future__ import annotations

from collections.abc import Mapping, Set
from typing import Optional

from binlex import Architecture, Configuration, Magic
from binlex.hashing import SHA256, SSDeep, TLSH

class SymbolKind:
    Function: SymbolKind
    Import: SymbolKind
    Export: SymbolKind
    Unknown: SymbolKind

class Symbol:
    def name(self) -> str: ...
    def file_offset(self) -> int: ...
    def virtual_address(self) -> int | None: ...
    def relative_virtual_address(self) -> int | None: ...
    def kind(self) -> SymbolKind: ...

class ImagePermissions:
    def __init__(
        self,
        read: bool = True,
        write: bool = False,
        execute: bool = False,
    ) -> None: ...
    @classmethod
    def readable(cls) -> ImagePermissions: ...
    @classmethod
    def executable(cls) -> ImagePermissions: ...
    @property
    def read(self) -> bool: ...
    @property
    def write(self) -> bool: ...
    @property
    def execute(self) -> bool: ...

class ImageSegment:
    @classmethod
    def bytes(
        cls,
        name: str | None,
        virtual_address: int,
        data: bytes | bytearray | list[int],
        permissions: ImagePermissions,
    ) -> ImageSegment: ...
    @classmethod
    def zeroes(
        cls,
        name: str | None,
        virtual_address: int,
        size: int,
        permissions: ImagePermissions,
    ) -> ImageSegment: ...
    @property
    def name(self) -> str | None: ...
    @property
    def virtual_address(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def permissions(self) -> ImagePermissions: ...
    def end(self) -> int: ...
    def contains(self, address: int) -> bool: ...

class Image:
    """Virtual binary image backed by mapped segments."""

    def __init__(self) -> None: ...
    @classmethod
    def _from_binding(cls, binding: object) -> Image: ...
    @classmethod
    def from_snapshot(cls, snapshot: object) -> Image: ...
    def snapshot(self) -> object: ...
    def __getstate__(self) -> object: ...
    def __setstate__(self, state: object) -> None: ...
    def add_segment(self, segment: ImageSegment) -> None: ...
    def segments(self) -> list[ImageSegment]: ...
    def read_virtual_address(self, address: int, size: int) -> bytes | None: ...
    def is_virtual_address(self, address: int) -> bool: ...
    def mapped_size(self) -> int: ...
    def executable_virtual_address_ranges(self) -> dict[int, int]: ...
    def virtual_min(self) -> int | None: ...
    def virtual_max(self) -> int | None: ...
    def __getitem__(self, key: int | slice) -> int | bytes: ...
    def __contains__(self, address: int) -> bool: ...

class File:
    """High-level wrapper around a file binding with typed helpers."""

    def __init__(self, path: str, configuration: Configuration) -> None: ...
    @classmethod
    def from_binding(cls, binding: object) -> File: ...
    def magic(self) -> Magic: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def ssdeep(self) -> SSDeep | None: ...
    def size(self) -> int: ...
    def read(self) -> None: ...

class ELF:
    """Executable and Linkable Format wrapper with address translation helpers."""

    def __init__(
        self, data: bytes | bytearray | memoryview, configuration: Configuration
    ) -> None: ...
    def architecture(self) -> Architecture: ...
    def executable_virtual_address_ranges(self) -> dict[int, int]: ...
    def relative_virtual_address_to_virtual_address(
        self, relative_virtual_address: int
    ) -> int: ...
    def file_offset_to_virtual_address(self, file_offset: int) -> int | None: ...
    def entrypoint_virtual_addresses(self) -> set[int]: ...
    def entrypoint_virtual_address(self) -> int: ...
    def image(self) -> Image: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def ssdeep(self) -> SSDeep | None: ...
    def size(self) -> int: ...
    def bytes(self) -> bytes: ...
    def symbols(self) -> list[Symbol]: ...
    def virtual_address_to_symbol(self, virtual_address: int) -> Symbol | None: ...
    def symbol_name_to_virtual_address(self, name: str) -> int | None: ...
    def symbol_name_to_file_offset(self, name: str) -> int | None: ...
    def relative_virtual_address_to_symbol(
        self, relative_virtual_address: int
    ) -> Symbol | None: ...
    def file_offset_to_symbol(self, file_offset: int) -> Symbol | None: ...
    def export_virtual_addresses(self) -> set[int]: ...
    def entropy(self) -> float | None: ...
    def file(self) -> File: ...

class COFF:
    """COFF object wrapper with section/symbol oriented helpers."""

    def __init__(
        self, data: bytes | bytearray | memoryview, configuration: Configuration
    ) -> None: ...
    def architecture(self) -> Architecture: ...
    def executable_file_offset_ranges(self) -> dict[int, int]: ...
    def bytes(self) -> bytes: ...
    def size(self) -> int: ...
    def symbols(self) -> list[Symbol]: ...
    def file_offset_to_symbol(self, file_offset: int) -> Symbol | None: ...
    def symbol_name_to_file_offset(self, name: str) -> int | None: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def ssdeep(self) -> SSDeep | None: ...
    def entropy(self) -> float | None: ...
    def file(self) -> File: ...

class MACHO:
    """Mach-O wrapper for single-arch and fat binaries with slice-aware helpers."""

    class Section:
        def name(self) -> str: ...
        def segment_name(self) -> str: ...
        def file_offset(self) -> int: ...
        def size(self) -> int: ...
        def virtual_address(self) -> int: ...
        def bytes(self) -> bytes: ...

    class Slice:
        def bytes(self) -> bytes: ...
        def index(self) -> int: ...
        def relative_virtual_address_to_virtual_address(
            self, relative_virtual_address: int
        ) -> int | None: ...
        def file_offset_to_virtual_address(self, file_offset: int) -> int | None: ...
        def entrypoint_virtual_address(self) -> int | None: ...
        def imagebase(self) -> int | None: ...
        def sizeofheaders(self) -> int | None: ...
        def architecture(self) -> Architecture: ...
        def symbols(self) -> list[Symbol]: ...
        def sections(self) -> list[MACHO.Section]: ...
        def section_name_to_section(self, name: str) -> MACHO.Section | None: ...
        def segment_and_section_name_to_section(
            self, segment_name: str, section_name: str
        ) -> MACHO.Section | None: ...
        def virtual_address_to_symbol(self, virtual_address: int) -> Symbol | None: ...
        def symbol_name_to_virtual_address(self, name: str) -> int | None: ...
        def symbol_name_to_file_offset(self, name: str) -> int | None: ...
        def relative_virtual_address_to_symbol(
            self, relative_virtual_address: int
        ) -> Symbol | None: ...
        def file_offset_to_symbol(self, file_offset: int) -> Symbol | None: ...
        def entrypoint_virtual_addresses(self) -> set[int]: ...
        def export_virtual_addresses(self) -> set[int]: ...
        def executable_virtual_address_ranges(self) -> dict[int, int]: ...
        def image(self) -> Image: ...

    def __init__(
        self, data: bytes | bytearray | memoryview, configuration: Configuration
    ) -> None: ...
    def bytes(self) -> bytes: ...
    def relative_virtual_address_to_virtual_address(
        self, relative_virtual_address: int, slice: int
    ) -> int | None: ...
    def file_offset_to_virtual_address(
        self, file_offset: int, slice: int
    ) -> int | None: ...
    def number_of_slices(self) -> int: ...
    def slice(self, index: int) -> MACHO.Slice | None: ...
    def slices(self) -> list[MACHO.Slice]: ...
    def entrypoint_virtual_address(self, slice: int) -> int | None: ...
    def imagebase(self, slice: int) -> int | None: ...
    def sizeofheaders(self, slice: int) -> int | None: ...
    def architecture(self, slice: int) -> Architecture: ...
    def symbols(self, slice: int) -> list[Symbol]: ...
    def virtual_address_to_symbol(
        self, virtual_address: int, slice: int
    ) -> Symbol | None: ...
    def symbol_name_to_virtual_address(self, name: str, slice: int) -> int | None: ...
    def symbol_name_to_file_offset(self, name: str, slice: int) -> int | None: ...
    def relative_virtual_address_to_symbol(
        self, relative_virtual_address: int, slice: int
    ) -> Symbol | None: ...
    def file_offset_to_symbol(self, file_offset: int, slice: int) -> Symbol | None: ...
    def entrypoint_virtual_addresses(self, slice: int) -> set[int]: ...
    def export_virtual_addresses(self, slice: int) -> set[int]: ...
    def executable_virtual_address_ranges(self, slice: int) -> dict[int, int]: ...
    def image(self, slice: int) -> Image: ...
    def size(self) -> int: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def ssdeep(self) -> SSDeep | None: ...
    def entropy(self) -> float | None: ...
    def file(self) -> File: ...

class PE:
    """Portable Executable wrapper with address translation helpers."""

    def __init__(
        self, data: bytes | bytearray | memoryview, configuration: Configuration
    ) -> None: ...
    def is_dotnet(self) -> bool: ...
    def virtual_address_to_relative_virtual_address(
        self, virtual_address: int
    ) -> int: ...
    def virtual_address_to_file_offset(self, virtual_address: int) -> int | None: ...
    def relative_virtual_address_to_file_offset(
        self, relative_virtual_address: int
    ) -> int | None: ...
    def relative_virtual_address_to_virtual_address(
        self, relative_virtual_address: int
    ) -> int: ...
    def file_offset_to_relative_virtual_address(
        self, file_offset: int
    ) -> int | None: ...
    def file_offset_to_virtual_address(self, file_offset: int) -> int | None: ...
    def architecture(self) -> Architecture: ...
    def dotnet_metadata_token_virtual_addresses(self) -> dict[int, int]: ...
    def dotnet_metadata_token_to_virtual_address(
        self, metadata_token: int
    ) -> int | None: ...
    def dotnet_metadata_token_to_relative_virtual_address(
        self, metadata_token: int
    ) -> int | None: ...
    def dotnet_metadata_token_to_file_offset(
        self, metadata_token: int
    ) -> int | None: ...
    def dotnet_virtual_address_to_metadata_token(
        self, virtual_address: int
    ) -> int | None: ...
    def dotnet_relative_virtual_address_to_metadata_token(
        self, relative_virtual_address: int
    ) -> int | None: ...
    def dotnet_file_offset_to_metadata_token(self, file_offset: int) -> int | None: ...
    def dotnet_executable_virtual_address_ranges(self) -> dict[int, int]: ...
    def executable_virtual_address_ranges(self) -> dict[int, int]: ...
    def bytes(self) -> bytes: ...
    def symbols(self) -> list[Symbol]: ...
    def metadata(self) -> dict[str, object]: ...
    def virtual_address_to_symbol(self, virtual_address: int) -> Symbol | None: ...
    def symbol_name_to_virtual_address(self, name: str) -> int | None: ...
    def symbol_name_to_file_offset(self, name: str) -> int | None: ...
    def relative_virtual_address_to_symbol(
        self, relative_virtual_address: int
    ) -> Symbol | None: ...
    def file_offset_to_symbol(self, file_offset: int) -> Symbol | None: ...
    def pogo_virtual_addresses(self) -> dict[int, str]: ...
    def tlscallbacks(self) -> set[int]: ...
    def dotnet_entrypoint_virtual_addresses(self) -> set[int]: ...
    def entrypoint_virtual_addresses(self) -> set[int]: ...
    def entrypoint_virtual_address(self) -> int: ...
    def sizeofheaders(self) -> int: ...
    def image(self) -> Image: ...
    def size(self) -> int: ...
    @staticmethod
    def align_section_virtual_address(
        value: int, section_alignment: int, file_alignment: int
    ) -> int: ...
    def export_virtual_addresses(self) -> set[int]: ...
    def tlsh(self) -> TLSH | None: ...
    def sha256(self) -> SHA256 | None: ...
    def ssdeep(self) -> SSDeep | None: ...
    def entropy(self) -> Optional[float]: ...
    def file(self) -> File: ...
    def imagebase(self) -> int: ...
    def section_alignment(self) -> int: ...
    def file_alignment(self) -> int: ...

__all__: list[str]
