from __future__ import annotations

class _ConfigEnabled:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class _ConfigTLSH(_ConfigEnabled):
    @property
    def minimum_byte_size(self) -> int: ...
    @minimum_byte_size.setter
    def minimum_byte_size(self, value: int) -> None: ...

class _ConfigMinhash(_ConfigEnabled):
    @property
    def number_of_hashes(self) -> int: ...
    @number_of_hashes.setter
    def number_of_hashes(self, value: int) -> None: ...
    @property
    def shingle_size(self) -> int: ...
    @shingle_size.setter
    def shingle_size(self, value: int) -> None: ...
    @property
    def maximum_byte_size_enabled(self) -> bool: ...
    @maximum_byte_size_enabled.setter
    def maximum_byte_size_enabled(self, value: bool) -> None: ...
    @property
    def maximum_byte_size(self) -> int: ...
    @maximum_byte_size.setter
    def maximum_byte_size(self, value: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

class _ConfigHashing:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...

class _ConfigChromosomesHashing(_ConfigHashing): ...
class _ConfigFunctionsHashing(_ConfigHashing): ...
class _ConfigBlocksHashing(_ConfigHashing): ...
class ConfigEntityLifterLLVM:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class ConfigEntityLifterVex:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class ConfigEntityLifters:
    @property
    def llvm(self) -> ConfigEntityLifterLLVM: ...
    @property
    def vex(self) -> ConfigEntityLifterVex: ...

class _ConfigFormatsFileHashing:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...

class ConfigChromosomes:
    @property
    def mask(self) -> _ConfigEnabled: ...
    @property
    def masked(self) -> _ConfigEnabled: ...
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...
    @property
    def vector(self) -> _ConfigEnabled: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...

class ConfigSemantics:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class ConfigFunctions(_ConfigEnabled):
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...
    @property
    def markov(self) -> _ConfigMarkov: ...
    @property
    def lifters(self) -> ConfigEntityLifters: ...
    @property
    def embeddings(self) -> ConfigEntityEmbeddings: ...

class _ConfigMarkov(_ConfigEnabled):
    @property
    def damping(self) -> float: ...
    @damping.setter
    def damping(self, value: float) -> None: ...
    @property
    def tolerance(self) -> float: ...
    @tolerance.setter
    def tolerance(self, value: float) -> None: ...
    @property
    def max_iterations(self) -> int: ...
    @max_iterations.setter
    def max_iterations(self, value: int) -> None: ...

class ConfigBlocks(_ConfigEnabled):
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...
    @property
    def lifters(self) -> ConfigEntityLifters: ...
    @property
    def embeddings(self) -> ConfigEntityEmbeddings: ...

class ConfigInstructions(_ConfigEnabled):
    @property
    def lifters(self) -> ConfigEntityLifters: ...
    @property
    def embeddings(self) -> ConfigEntityEmbeddings: ...

class ConfigFormatsFile:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...

class ConfigFormats:
    @property
    def file(self) -> ConfigFormatsFile: ...

class _ConfigHashingEnabled:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class _ConfigHashingTLSH(_ConfigHashingEnabled):
    @property
    def minimum_byte_size(self) -> int: ...
    @minimum_byte_size.setter
    def minimum_byte_size(self, value: int) -> None: ...

class _ConfigHashingMinhash(_ConfigHashingEnabled):
    @property
    def number_of_hashes(self) -> int: ...
    @number_of_hashes.setter
    def number_of_hashes(self, value: int) -> None: ...
    @property
    def shingle_size(self) -> int: ...
    @shingle_size.setter
    def shingle_size(self, value: int) -> None: ...
    @property
    def maximum_byte_size_enabled(self) -> bool: ...
    @maximum_byte_size_enabled.setter
    def maximum_byte_size_enabled(self, value: bool) -> None: ...
    @property
    def maximum_byte_size(self) -> int: ...
    @maximum_byte_size.setter
    def maximum_byte_size(self, value: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

class ConfigImagingTLSH:
    @property
    def minimum_byte_size(self) -> int: ...
    @minimum_byte_size.setter
    def minimum_byte_size(self, value: int) -> None: ...

class ConfigImagingMinhash:
    @property
    def number_of_hashes(self) -> int: ...
    @number_of_hashes.setter
    def number_of_hashes(self, value: int) -> None: ...
    @property
    def shingle_size(self) -> int: ...
    @shingle_size.setter
    def shingle_size(self, value: int) -> None: ...
    @property
    def maximum_byte_size_enabled(self) -> bool: ...
    @maximum_byte_size_enabled.setter
    def maximum_byte_size_enabled(self, value: bool) -> None: ...
    @property
    def maximum_byte_size(self) -> int: ...
    @maximum_byte_size.setter
    def maximum_byte_size(self, value: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

class ConfigImaging:
    @property
    def tlsh(self) -> ConfigImagingTLSH: ...
    @property
    def minhash(self) -> ConfigImagingMinhash: ...

class ConfigLiftersLLVM:
    @property
    def module_name(self) -> str: ...
    @module_name.setter
    def module_name(self, value: str) -> None: ...
    @property
    def verify(self) -> bool: ...
    @verify.setter
    def verify(self, value: bool) -> None: ...

class ConfigLiftersVex:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class ConfigLifters:
    @property
    def llvm(self) -> ConfigLiftersLLVM: ...
    @property
    def vex(self) -> ConfigLiftersVex: ...

class ConfigEntityEmbeddingsLLVM:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class ConfigEntityEmbeddings:
    @property
    def llvm(self) -> ConfigEntityEmbeddingsLLVM: ...

class ConfigEmbeddingsLLVM:
    @property
    def dimensions(self) -> int: ...
    @dimensions.setter
    def dimensions(self, value: int) -> None: ...
    @property
    def device(self) -> str: ...
    @device.setter
    def device(self, value: str) -> None: ...

class ConfigEmbeddings:
    @property
    def llvm(self) -> ConfigEmbeddingsLLVM: ...

class ConfigMmapCache:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class ConfigMmap:
    @property
    def directory(self) -> str: ...
    @directory.setter
    def directory(self, value: str) -> None: ...
    @property
    def cache(self) -> ConfigMmapCache: ...

class Config:
    @property
    def threads(self) -> int: ...
    @threads.setter
    def threads(self, value: int) -> None: ...
    @property
    def minimal(self) -> bool: ...
    @minimal.setter
    def minimal(self, value: bool) -> None: ...
    @property
    def debug(self) -> bool: ...
    @debug.setter
    def debug(self, value: bool) -> None: ...
    @property
    def chromosomes(self) -> ConfigChromosomes: ...
    @property
    def functions(self) -> ConfigFunctions: ...
    @property
    def blocks(self) -> ConfigBlocks: ...
    @property
    def instructions(self) -> ConfigInstructions: ...
    @property
    def semantics(self) -> ConfigSemantics: ...
    @property
    def formats(self) -> ConfigFormats: ...
    @property
    def imaging(self) -> ConfigImaging: ...
    @property
    def mmap(self) -> ConfigMmap: ...
    @property
    def lifters(self) -> ConfigLifters: ...
    @property
    def embeddings(self) -> ConfigEmbeddings: ...
    def disable_chromosome_hashing(self) -> None: ...
    def disable_chromosome_heuristics(self) -> None: ...

__all__ = ["Config"]
