from __future__ import annotations

class _ConfigEnabled:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class _ConfigTLSH(_ConfigEnabled):
    @property
    def minimum_byte_size(self) -> int: ...
    @minimum_byte_size.setter
    def minimum_byte_size(self, value: int) -> None: ...

class _ConfigMinhash(_ConfigEnabled):
    @property
    def number_of_hashes(self) -> int: ...
    @number_of_hashes.setter
    def number_of_hashes(self, value: int) -> None: ...
    @property
    def shingle_size(self) -> int: ...
    @shingle_size.setter
    def shingle_size(self, value: int) -> None: ...
    @property
    def maximum_byte_size_enabled(self) -> bool: ...
    @maximum_byte_size_enabled.setter
    def maximum_byte_size_enabled(self, value: bool) -> None: ...
    @property
    def maximum_byte_size(self) -> int: ...
    @maximum_byte_size.setter
    def maximum_byte_size(self, value: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

class _ConfigHashing:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...

class _ConfigChromosomesHashing(_ConfigHashing): ...
class _ConfigFunctionsHashing(_ConfigHashing): ...
class _ConfigBlocksHashing(_ConfigHashing): ...
class _ConfigFormatsFileHashing:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...

class ConfigChromosomes:
    @property
    def mask(self) -> _ConfigEnabled: ...
    @property
    def masked(self) -> _ConfigEnabled: ...
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...
    @property
    def vector(self) -> _ConfigEnabled: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...

class ConfigFunctions(_ConfigEnabled):
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...
    @property
    def markov(self) -> _ConfigMarkov: ...

class _ConfigMarkov(_ConfigEnabled):
    @property
    def damping(self) -> float: ...
    @damping.setter
    def damping(self, value: float) -> None: ...
    @property
    def tolerance(self) -> float: ...
    @tolerance.setter
    def tolerance(self, value: float) -> None: ...
    @property
    def max_iterations(self) -> int: ...
    @max_iterations.setter
    def max_iterations(self, value: int) -> None: ...

class ConfigBlocks(_ConfigEnabled):
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...

class ConfigInstructions(_ConfigEnabled):
    pass

class ConfigFormatsFile:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...

class ConfigFormats:
    @property
    def file(self) -> ConfigFormatsFile: ...

class _ConfigHashingEnabled:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class _ConfigHashingTLSH(_ConfigHashingEnabled):
    @property
    def minimum_byte_size(self) -> int: ...
    @minimum_byte_size.setter
    def minimum_byte_size(self, value: int) -> None: ...

class _ConfigHashingMinhash(_ConfigHashingEnabled):
    @property
    def number_of_hashes(self) -> int: ...
    @number_of_hashes.setter
    def number_of_hashes(self, value: int) -> None: ...
    @property
    def shingle_size(self) -> int: ...
    @shingle_size.setter
    def shingle_size(self, value: int) -> None: ...
    @property
    def maximum_byte_size_enabled(self) -> bool: ...
    @maximum_byte_size_enabled.setter
    def maximum_byte_size_enabled(self, value: bool) -> None: ...
    @property
    def maximum_byte_size(self) -> int: ...
    @maximum_byte_size.setter
    def maximum_byte_size(self, value: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

class ConfigImagingHashing:
    @property
    def sha256(self) -> _ConfigHashingEnabled: ...
    @property
    def tlsh(self) -> _ConfigHashingTLSH: ...
    @property
    def minhash(self) -> _ConfigHashingMinhash: ...
    @property
    def ahash(self) -> _ConfigHashingEnabled: ...
    @property
    def dhash(self) -> _ConfigHashingEnabled: ...
    @property
    def phash(self) -> _ConfigHashingEnabled: ...

class ConfigImaging:
    @property
    def sha256(self) -> _ConfigHashingEnabled: ...
    @property
    def tlsh(self) -> _ConfigHashingTLSH: ...
    @property
    def minhash(self) -> _ConfigHashingMinhash: ...
    @property
    def ahash(self) -> _ConfigHashingEnabled: ...
    @property
    def dhash(self) -> _ConfigHashingEnabled: ...
    @property
    def phash(self) -> _ConfigHashingEnabled: ...

class ConfigMmapCache:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class ConfigMmap:
    @property
    def directory(self) -> str: ...
    @directory.setter
    def directory(self, value: str) -> None: ...
    @property
    def cache(self) -> ConfigMmapCache: ...

class Config:
    @property
    def threads(self) -> int: ...
    @threads.setter
    def threads(self, value: int) -> None: ...
    @property
    def minimal(self) -> bool: ...
    @minimal.setter
    def minimal(self, value: bool) -> None: ...
    @property
    def debug(self) -> bool: ...
    @debug.setter
    def debug(self, value: bool) -> None: ...
    @property
    def chromosomes(self) -> ConfigChromosomes: ...
    @property
    def functions(self) -> ConfigFunctions: ...
    @property
    def blocks(self) -> ConfigBlocks: ...
    @property
    def instructions(self) -> ConfigInstructions: ...
    @property
    def formats(self) -> ConfigFormats: ...
    @property
    def imaging(self) -> ConfigImaging: ...
    @property
    def mmap(self) -> ConfigMmap: ...
    def disable_imaging_hashing(self) -> None: ...
    def disable_chromosome_hashing(self) -> None: ...
    def disable_chromosome_heuristics(self) -> None: ...

__all__ = ["Config"]
