from __future__ import annotations

class ConfigTLSH:
    @property
    def minimum_byte_size(self) -> int: ...
    @minimum_byte_size.setter
    def minimum_byte_size(self, value: int) -> None: ...

class ConfigMinhash:
    @property
    def number_of_hashes(self) -> int: ...
    @number_of_hashes.setter
    def number_of_hashes(self, value: int) -> None: ...
    @property
    def shingle_size(self) -> int: ...
    @shingle_size.setter
    def shingle_size(self, value: int) -> None: ...
    @property
    def maximum_byte_size_enabled(self) -> bool: ...
    @maximum_byte_size_enabled.setter
    def maximum_byte_size_enabled(self, value: bool) -> None: ...
    @property
    def maximum_byte_size(self) -> int: ...
    @maximum_byte_size.setter
    def maximum_byte_size(self, value: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

class ConfigHashing:
    @property
    def tlsh(self) -> ConfigTLSH: ...
    @property
    def minhash(self) -> ConfigMinhash: ...

class ConfigFunctions:
    @property
    def markov(self) -> ConfigMarkov: ...

class ConfigMarkov:
    @property
    def damping(self) -> float: ...
    @damping.setter
    def damping(self, value: float) -> None: ...
    @property
    def tolerance(self) -> float: ...
    @tolerance.setter
    def tolerance(self, value: float) -> None: ...
    @property
    def max_iterations(self) -> int: ...
    @max_iterations.setter
    def max_iterations(self, value: int) -> None: ...

class ConfigIrsLLVM:
    @property
    def module_name(self) -> str: ...
    @module_name.setter
    def module_name(self, value: str) -> None: ...
    @property
    def verify(self) -> bool: ...
    @verify.setter
    def verify(self, value: bool) -> None: ...
    @property
    def mode(self) -> str: ...
    @mode.setter
    def mode(self, value: str) -> None: ...

class ConfigIrs:
    @property
    def llvm(self) -> ConfigIrsLLVM: ...

class ConfigEmbeddingsLLVM:
    @property
    def dimensions(self) -> int: ...
    @dimensions.setter
    def dimensions(self, value: int) -> None: ...
    @property
    def device(self) -> str: ...
    @device.setter
    def device(self, value: str) -> None: ...

class ConfigEmbeddings:
    @property
    def llvm(self) -> ConfigEmbeddingsLLVM: ...

class ConfigMmapCache:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class ConfigMmap:
    @property
    def directory(self) -> str: ...
    @directory.setter
    def directory(self, value: str) -> None: ...
    @property
    def cache(self) -> ConfigMmapCache: ...

class ConfigDisassemblerSweep:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class ConfigDisassembler:
    @property
    def sweep(self) -> ConfigDisassemblerSweep: ...

class Configuration:
    @classmethod
    def from_snapshot(cls, snapshot: object) -> Configuration: ...
    def snapshot(self) -> object: ...
    def __getstate__(self) -> object: ...
    def __setstate__(self, state: object) -> None: ...
    @property
    def threads(self) -> int: ...
    @threads.setter
    def threads(self, value: int) -> None: ...
    @property
    def debug(self) -> bool: ...
    @debug.setter
    def debug(self, value: bool) -> None: ...
    @property
    def hashing(self) -> ConfigHashing: ...
    @property
    def functions(self) -> ConfigFunctions: ...
    @property
    def mmap(self) -> ConfigMmap: ...
    @property
    def disassembler(self) -> ConfigDisassembler: ...
    @property
    def irs(self) -> ConfigIrs: ...
    @property
    def embeddings(self) -> ConfigEmbeddings: ...
    def clone(self) -> Configuration: ...
    def from_default(self) -> None: ...
    def to_string(self) -> str: ...
    def print(self) -> None: ...
    def write_default(self) -> None: ...
    def write_to_file(self, file_path: str) -> None: ...

__all__ = ["Configuration"]
