from __future__ import annotations

class _ConfigEnabled:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class _ConfigTLSH(_ConfigEnabled):
    @property
    def minimum_byte_size(self) -> int: ...
    @minimum_byte_size.setter
    def minimum_byte_size(self, value: int) -> None: ...

class _ConfigMinhash(_ConfigEnabled):
    @property
    def number_of_hashes(self) -> int: ...
    @number_of_hashes.setter
    def number_of_hashes(self, value: int) -> None: ...
    @property
    def shingle_size(self) -> int: ...
    @shingle_size.setter
    def shingle_size(self, value: int) -> None: ...
    @property
    def maximum_byte_size_enabled(self) -> bool: ...
    @maximum_byte_size_enabled.setter
    def maximum_byte_size_enabled(self, value: bool) -> None: ...
    @property
    def maximum_byte_size(self) -> int: ...
    @maximum_byte_size.setter
    def maximum_byte_size(self, value: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

class _ConfigHashing:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...

class _ConfigChromosomesHashing(_ConfigHashing): ...
class _ConfigFunctionsHashing(_ConfigHashing): ...
class _ConfigBlocksHashing(_ConfigHashing): ...
class _ConfigFormatsFileHashing:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...

class ConfigChromosomes:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...
    @property
    def vector(self) -> _ConfigEnabled: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...

class ConfigFunctions(_ConfigEnabled):
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...

class ConfigBlocks(_ConfigEnabled):
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def minhash(self) -> _ConfigMinhash: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...

class ConfigInstructions(_ConfigEnabled):
    pass

class ConfigFormatsFile:
    @property
    def sha256(self) -> _ConfigEnabled: ...
    @property
    def tlsh(self) -> _ConfigTLSH: ...
    @property
    def entropy(self) -> _ConfigEnabled: ...

class ConfigFormats:
    @property
    def file(self) -> ConfigFormatsFile: ...

class _ConfigHashingEnabled:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...

class _ConfigHashingTLSH(_ConfigHashingEnabled):
    @property
    def minimum_byte_size(self) -> int: ...
    @minimum_byte_size.setter
    def minimum_byte_size(self, value: int) -> None: ...

class _ConfigHashingMinhash(_ConfigHashingEnabled):
    @property
    def number_of_hashes(self) -> int: ...
    @number_of_hashes.setter
    def number_of_hashes(self, value: int) -> None: ...
    @property
    def shingle_size(self) -> int: ...
    @shingle_size.setter
    def shingle_size(self, value: int) -> None: ...
    @property
    def maximum_byte_size_enabled(self) -> bool: ...
    @maximum_byte_size_enabled.setter
    def maximum_byte_size_enabled(self, value: bool) -> None: ...
    @property
    def maximum_byte_size(self) -> int: ...
    @maximum_byte_size.setter
    def maximum_byte_size(self, value: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @seed.setter
    def seed(self, value: int) -> None: ...

class ConfigImagingHashing:
    @property
    def sha256(self) -> _ConfigHashingEnabled: ...
    @property
    def tlsh(self) -> _ConfigHashingTLSH: ...
    @property
    def minhash(self) -> _ConfigHashingMinhash: ...
    @property
    def ahash(self) -> _ConfigHashingEnabled: ...
    @property
    def dhash(self) -> _ConfigHashingEnabled: ...
    @property
    def phash(self) -> _ConfigHashingEnabled: ...

class ConfigImaging:
    @property
    def sha256(self) -> _ConfigHashingEnabled: ...
    @property
    def tlsh(self) -> _ConfigHashingTLSH: ...
    @property
    def minhash(self) -> _ConfigHashingMinhash: ...
    @property
    def ahash(self) -> _ConfigHashingEnabled: ...
    @property
    def dhash(self) -> _ConfigHashingEnabled: ...
    @property
    def phash(self) -> _ConfigHashingEnabled: ...

class ConfigDisassemblerSweep(_ConfigEnabled): ...

class ConfigDisassembler:
    @property
    def sweep(self) -> ConfigDisassemblerSweep: ...

class ConfigMmapCache(_ConfigEnabled): ...

class ConfigIndexLocal:
    @property
    def directory(self) -> str: ...
    @directory.setter
    def directory(self, value: str) -> None: ...

class ConfigIndex:
    @property
    def local(self) -> ConfigIndexLocal: ...

class ConfigMmap:
    @property
    def directory(self) -> str: ...
    @directory.setter
    def directory(self, value: str) -> None: ...
    @property
    def cache(self) -> ConfigMmapCache: ...

class ConfigGeneral:
    @property
    def threads(self) -> int: ...
    @threads.setter
    def threads(self, value: int) -> None: ...
    @property
    def minimal(self) -> bool: ...
    @minimal.setter
    def minimal(self, value: bool) -> None: ...
    @property
    def debug(self) -> bool: ...
    @debug.setter
    def debug(self, value: bool) -> None: ...

class ConfigProcessor:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...
    @property
    def dimensions(self) -> int | None: ...
    @dimensions.setter
    def dimensions(self, value: int | None) -> None: ...
    @property
    def device(self) -> str | None: ...
    @device.setter
    def device(self, value: str | None) -> None: ...
    @property
    def instructions(self) -> _ConfigEnabled: ...
    @property
    def blocks(self) -> _ConfigEnabled: ...
    @property
    def functions(self) -> _ConfigEnabled: ...
    @property
    def transport(self) -> ConfigProcessorTransports: ...

class ConfigProcessorTransport:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...
    @property
    def url(self) -> str | None: ...
    @url.setter
    def url(self, value: str | None) -> None: ...
    @property
    def verify(self) -> bool | None: ...
    @verify.setter
    def verify(self, value: bool | None) -> None: ...

class ConfigProcessorTransports:
    @property
    def inline(self) -> ConfigProcessorTransport: ...
    @property
    def ipc(self) -> ConfigProcessorTransport: ...
    @property
    def http(self) -> ConfigProcessorTransport: ...

class ConfigProcessors:
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...
    @property
    def path(self) -> str | None: ...
    @path.setter
    def path(self, value: str | None) -> None: ...
    @property
    def processes(self) -> int: ...
    @processes.setter
    def processes(self, value: int) -> None: ...
    @property
    def compression(self) -> bool: ...
    @compression.setter
    def compression(self, value: bool) -> None: ...
    @property
    def restart_on_crash(self) -> bool: ...
    @restart_on_crash.setter
    def restart_on_crash(self, value: bool) -> None: ...
    @property
    def max_payload_bytes(self) -> int: ...
    @max_payload_bytes.setter
    def max_payload_bytes(self, value: int) -> None: ...
    @property
    def idle_timeout_ms(self) -> int: ...
    @idle_timeout_ms.setter
    def idle_timeout_ms(self, value: int) -> None: ...
    @property
    def max_queue_depth(self) -> int: ...
    @max_queue_depth.setter
    def max_queue_depth(self, value: int) -> None: ...
    @property
    def vex(self) -> ConfigProcessor: ...
    @property
    def embeddings(self) -> ConfigProcessor: ...
    def processor(self, name: str) -> ConfigProcessor: ...

class Config:
    def __init__(self) -> None: ...
    @property
    def general(self) -> ConfigGeneral: ...
    @property
    def index(self) -> ConfigIndex: ...
    @property
    def processors(self) -> ConfigProcessors: ...
    @property
    def formats(self) -> ConfigFormats: ...
    @property
    def imaging(self) -> ConfigImaging: ...
    @property
    def blocks(self) -> ConfigBlocks: ...
    @property
    def instructions(self) -> ConfigInstructions: ...
    @property
    def functions(self) -> ConfigFunctions: ...
    @property
    def chromosomes(self) -> ConfigChromosomes: ...
    @property
    def mmap(self) -> ConfigMmap: ...
    @property
    def disassembler(self) -> ConfigDisassembler: ...
    def enable_minimal(self) -> None: ...
    def disable_hashing(self) -> None: ...
    def disable_heuristics(self) -> None: ...
    def disable_chromosome_heuristics(self) -> None: ...
    def disable_chromosome_hashing(self) -> None: ...
    def disable_block_hashing(self) -> None: ...
    def disable_function_hashing(self) -> None: ...
    def disable_function_heuristics(self) -> None: ...
    def disable_block_heuristics(self) -> None: ...
    def from_default(self) -> None: ...
    def to_string(self) -> str: ...
    def print(self) -> None: ...
    def write_default(self) -> None: ...
    def write_to_file(self, file_path: str) -> None: ...

class Magic:
    @staticmethod
    def from_file(path: str) -> Magic: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Magic: ...
    @staticmethod
    def from_value(value: int) -> Magic: ...
    @staticmethod
    def from_string(s: str) -> Magic: ...
    @property
    def value(self) -> int: ...
    def __str__(self) -> str: ...

__all__: list[str]
